force-app/main/default/objects/Partner_Event_Log__c/Partner_Event_Log__c.object-meta.xml
<CustomObject>
    <label>Partner Event Log</label>
    <nameField>
        <displayFormat>PEL-{000000000}</displayFormat>
        <label>Log ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Event Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Partner_Event_Log__c/fields/Event_Type__c.field-meta.xml
<CustomField>
    <fullName>Event_Type__c</fullName>
    <label>Event Type</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Partner_Event_Log__c/fields/Partner_Order__c.field-meta.xml
<CustomField>
    <fullName>Partner_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner Order</label>
    <referenceTo>Partner_Order__c</referenceTo>
    <relationshipLabel>Partner Event Logs</relationshipLabel>
    <relationshipName>Partner_Event_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Partner_Event_Log__c/fields/Response_Payload__c.field-meta.xml
<CustomField>
    <fullName>Response_Payload__c</fullName>
    <label>Response Payload</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Partner_Order__c/Partner_Order__c.object-meta.xml
<CustomObject>
    <label>Partner Order</label>
    <nameField>
        <displayFormat>PO-{000000000}</displayFormat>
        <label>Order ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Partner_Order__c/fields/Retail_Partner__c.field-meta.xml
<CustomField>
    <fullName>Retail_Partner__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Retail Partner</label>
    <referenceTo>PartnerClientMap__c</referenceTo>
    <relationshipLabel>Partner Orders</relationshipLabel>
    <relationshipName>Partner_Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Partner_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
                <default>true</default>
                <label>Created</label>
            </value>
            <value>
                <fullName>Ordered</fullName>
            </value>
            <value>
                <fullName>Acknowledged</fullName>
            </value>
            <value>
                <fullName>Shipped</fullName>
            </value>
            <value>
                <fullName>Received</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
                <isActive>false</isActive>
                <label>Closed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PartnerClientMap__c/PartnerClientMap__c.object-meta.xml
<CustomObject>
    <label>Partner Client Map</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PartnerClientMaps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PartnerClientMap__c/fields/Fulfillment_Location_API_Key__c.field-meta.xml
<CustomField>
    <fullName>Fulfillment_Location_API_Key__c</fullName>
    <label>Fulfillment Location API Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GBFShipmentConfirmation.cls
global with sharing class GBFShipmentConfirmation implements Database.Batchable<SObject>, Database.AllowsCallouts{
    public String query;
    public String status;
    public String Id;

    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<Partner_Order__c> openOrders) {

        if(!openOrders.isEmpty())
        {

            List<Partner_Event_Log__c> logs = new List<Partner_Event_Log__c>();
            Organization a_ORG = [Select Id, Name, IsSandbox from Organization];
 
            if(a_ORG.IsSandbox)
            {
                
                for (Partner_Order__c order : openOrders)
                {
                    List<OMS_Shipment_Payload__c> payloads = [select Partner_Order__c,Payload__c from OMS_Shipment_Payload__c where Partner_Order__c =:order.id];
                    if(payloads.size() > 0)
                    {
                        // Partner_Event_Log__c log = new Partner_Event_Log__c(); 
                        // log.Event_Type__c= 'Shipment';
                        // log.Partner_Order__c = order.id;
                        // log.Payload__c = generateRequest(order.id);
                        OMS_Shipment_Payload__c payload =payloads[0];
                        String shipmentPayload = payload.Payload__c;
                        // String eventLogPayload = shipmentPayload;
                        // if(shipmentPayload.length() > 131072)
                        // {
                        //     eventLogPayload = shipmentPayload.substring(0, 131071);
                        // }
                        HttpResponse res = new HttpResponse();
                        res.setHeader('Content-Type', 'application/json');
                        res.setStatusCode(200);
                        res.setBody(shipmentPayload);

                        Partner_Event_Log__c log = parseResponse(order.id,generateRequest(order.id),res);                
                        logs.add(log);

                        // log.Response_Payload__c = eventLogPayload;
                        // log.Status__c = 'Success';
                        // Map<String, Object> payloadMap = (Map<String, Object>) JSON.deserializeUntyped(shipmentPayload);
                        // System.debug('Map: ' + payloadMap);
                        // List<Object> dataArray = (List<Object>) payloadMap.get('dataArray');
                        // if(!dataArray.isEmpty())
                        // { 
                        //     System.debug(' Calling GBF Parser with Data Array : ' + dataArray);                       
                        //     GBFShipmentConfirmationParser.processShipmentConfirmation(dataArray);
                        // }
                        // logs.add(log);
                    }
                }
            }
            else{
                System.debug('This is Production'); 
                
                for (Partner_Order__c order : openOrders)
                {
                    String requestStr = generateRequest(order.id);
                    System.debug(requestStr);

                HttpRequest request = new HttpRequest();
                    request.setEndpoint(Label.GBF_Confirm_API_Endpoint);
                    request.setMethod('POST');
                    request.setHeader('Content-Type','application/json');
                    request.setHeader('Authorization','Bearer ' + order.Retail_Partner__r.Fulfillment_Location_API_Key__c);
                    request.setTimeout(30000);

                    request.setBody(requestStr);

                Http http = new Http();
                HttpResponse res = http.send(request);
                Partner_Event_Log__c log = parseResponse(order.id,requestStr,res);                
                logs.add(log);
                }
               
            }

            insert logs;
            
        
        }
    }

    private String generateRequest(String orderId)
    {
        JSONGenerator gen = JSON.createGenerator(true);
        gen.writeStartObject();
            gen.writeStringField('orderNumber',orderId);
            gen.writeStringField('format','xml');
        gen.writeEndObject();
        return gen.getAsString();
    }

    @TestVisible
    private Partner_Event_Log__c parseResponse (String orderId, String request,HttpResponse res)
    {
        Partner_Event_Log__c log = new Partner_Event_Log__c();
        try 
                {
                    log.Event_Type__c= 'Shipment';
                    log.Partner_Order__c = orderId;
                    log.Payload__c = request;

                    if(res.getStatusCode() == 200)
                    {
                        String payload =res.getBody();
                        String eventLogPayload = payload;
                        System.debug('Response: ' + payload + ' and Length: ' + payload.length());
                        if(payload.length() > 131072)
                        {
                            eventLogPayload = payload.substring(0, 131071);
                        }
                        log.Response_Payload__c = eventLogPayload;
                        log.Status__c = 'Success';
                        System.debug('Response: ' + payload);
                        Map<String, Object> payloadMap = (Map<String, Object>) JSON.deserializeUntyped(payload);
                        System.debug('Map: ' + payloadMap);
                        List<Object> dataArray = (List<Object>) payloadMap.get('dataArray');
                        System.debug('List: ' + dataArray);
                        if(!dataArray.isEmpty())
                        {                        
                            GBFShipmentConfirmationParser.processShipmentConfirmation(dataArray);
                        }
                            
                    }
                    else {
                        constructErrorResponse(log,res,'');
                    }
                } 
                catch (Exception e)  {
                       constructErrorResponse(log,res,e.getMessage());
                        log.Status__c = 'Error';
                }

                return log;
    }

    private void constructErrorResponse(Partner_Event_Log__c log,HttpResponse res,String exceptionMessage )
    {
                    String payload =res.getBody();
                    log.Response_Payload__c = payload +  ' ' + exceptionMessage;
                    log.Status__c = 'Error';
    } 

    global void finish(Database.BatchableContext BC) {
       
    }
}