force-app/main/default/objects/Order/fields/Client_Id__c.field-meta.xml
<CustomField>
    <fullName>Client_Id__c</fullName>
    <label>Client_Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Partner_Order__c/Partner_Order__c.object-meta.xml
<CustomObject>
    <label>Partner Order</label>
    <nameField>
        <displayFormat>PO-{000000000}</displayFormat>
        <label>Order ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Partner_Order__c/fields/Address_Line_1__c.field-meta.xml
<CustomField>
    <fullName>Address_Line_1__c</fullName>
    <label>Address Line 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Partner_Order__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <defaultValue>&quot;US&quot;</defaultValue>
    <label>Country</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Partner_Order__c/fields/PhoneNumber__c.field-meta.xml
<CustomField>
    <fullName>PhoneNumber__c</fullName>
    <label>Phone Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Partner_Order__c/fields/Retail_Partner__c.field-meta.xml
<CustomField>
    <fullName>Retail_Partner__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Retail Partner</label>
    <referenceTo>PartnerClientMap__c</referenceTo>
    <relationshipLabel>Partner Orders</relationshipLabel>
    <relationshipName>Partner_Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Partner_Order__c/fields/Shipping_Method__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Method__c</fullName>
    <label>Shipping Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FedEx Ground</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Partner_Order__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
            <value>
                <fullName>NV</fullName>
            </value>
            <value>
                <fullName>NH</fullName>
            </value>
            <value>
                <fullName>NJ</fullName>
            </value>
            <value>
                <fullName>NY</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Partner_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
                <default>true</default>
                <label>Created</label>
            </value>
            <value>
                <fullName>Ordered</fullName>
            </value>
            <value>
                <fullName>Acknowledged</fullName>
            </value>
            <value>
                <fullName>Shipped</fullName>
            </value>
            <value>
                <fullName>Received</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
                <isActive>false</isActive>
                <label>Closed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Partner_Order__c/fields/ZipCode__c.field-meta.xml
<CustomField>
    <fullName>ZipCode__c</fullName>
    <label>ZipCode</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PartnerClientMap__c/PartnerClientMap__c.object-meta.xml
<CustomObject>
    <label>Partner Client Map</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PartnerClientMaps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PartnerClientMap__c/fields/Fulfillment_Location_API_Key__c.field-meta.xml
<CustomField>
    <fullName>Fulfillment_Location_API_Key__c</fullName>
    <label>Fulfillment Location API Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PartnerClientMap__c/fields/Partner_Name__c.field-meta.xml
<CustomField>
    <fullName>Partner_Name__c</fullName>
    <label>Partner Name</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/PartnerClientMap__c/fields/Short_Code__c.field-meta.xml
<CustomField>
    <fullName>Short_Code__c</fullName>
    <label>Short Code</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GBFOrderStatusCheckerTest.cls
@IsTest
public with sharing class GBFOrderStatusCheckerTest {
    
    public static String partnerOrderId = getPartnerOrder().Id;

    private class MockHttpResponseGeneratorSuccess implements HttpCalloutMock {
        public HttpResponse respond(HttpRequest req) {

            JSONGenerator gen= JSON.createGenerator(true);
            gen.writeStartObject();
                gen.writeBooleanField('success', true);
                gen.writeStringField('errorMessage', '');
                gen.writeFieldName('statuses');
                gen.writeStartArray();
                
                // First status object
                    gen.writeStartObject();
                    gen.writeStringField('orderNumber',  partnerOrderId);
                    gen.writeStringField('orderStatus', 'SHIPPED (SIMULATED)');
                    gen.writeStringField('statusMessage', '');
                    gen.writeEndObject();
                gen.writeEndArray();
            gen.writeEndObject();
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json');
            res.setStatusCode(200);
            res.setBody(gen.getAsString());
            return res;
        }
    }

    @IsTest (SeeAllData=true)
    static void validateStatusCheckTest()
    {
        

        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGeneratorSuccess());
        Test.startTest();
        GBFOrderStatusChecker btch= new GBFOrderStatusChecker();
      //  btch.Id=partnerOrderId;
        btch.status = 'Acknowledged';
        btch.query = 'SELECT Id,  Status__c,Partner_Order__c.Retail_Partner__r.Fulfillment_Location_API_Key__c FROM Partner_Order__c WHERE Status__c =: status and Id=\'' + partnerOrderId+'\'';
        Database.executeBatch(btch,1);
        Test.stopTest();
        
    }

    @IsTest (SeeAllData=true)
    static void validateStatusCheckScheduleTest () {
        GBFOrderStatusCheckerSchedule  obj = new GBFOrderStatusCheckerSchedule();
        String sch = '0 0 23 * * ?'; 
        system.schedule('Test Territory Check', sch, obj); 
  }      








    private static Partner_Order__c getPartnerOrder()
    {

        PartnerClientMap__c partner= new PartnerClientMap__c();
        partner.Client_ID__c= 'test1';
        partner.Partner_Name__c='test1';
        partner.Short_Code__c='test';
         partner.Fulfillment_Location_API_Key__c = '12345';

        insert partner;
        Partner_Order__c order = new Partner_Order__c();
        order.Retail_Partner__c = partner.Id;
        order.Address_Line_1__c='123 Test';
        order.City__c = 'Test';
        order.State__c='NY';
        order.ZipCode__c='12345';
        order.Country__c='US';
        order.Company_Name__c='Test Company';
        order.Shipping_Method__c='FedEx Ground';
        order.Email__c='test@gmail.com';
        order.PhoneNumber__c='1234567890';
        order.Status__c='Acknowledged';

        insert order;

        Product2 product = new Product2();
            product.Name = 'Test';
            product.Description = 'Test';
            product.ProductCode = 'Test123';
            product.StockKeepingUnit = 'Test123' + String.valueOf(12345);
            product.DisplayUrl = '';
            product.ExternalId = 'Test123';
            product.IsActive = true;
            insert  product;

        Partner_Order_Line_Item__c line= new Partner_Order_Line_Item__c();
        line.Partner_Order__c=order.Id;
        line.Product__c=product.Id;
        line.Quantity__c=1000;

        insert line;

        return order;
    }
}