force-app/main/default/objects/FulfillmentOrder/fields/CustomerId__c.field-meta.xml
<CustomField>
    <fullName>CustomerId__c</fullName>
    <label>Customer Id</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FulfillmentOrder/fields/Days_past_Confirm__c.field-meta.xml
<CustomField>
    <fullName>Days_past_Confirm__c</fullName>
    <formula>TODAY() -  DATEVALUE(OrderSummary.OrderedDate)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Days past Confirm</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FulfillmentOrder/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <formula>IF(ISBLANK(PWN_Status_Date__c), DATEVALUE( CreatedDate )  +65,PWN_Status_Date__c+65)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FulfillmentOrder/fields/HUB_Success__c.field-meta.xml
<CustomField>
    <fullName>HUB_Success__c</fullName>
    <defaultValue>false</defaultValue>
    <label>HUB Success</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FulfillmentOrderLineItem/fields/Date_of_Collection__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Collection__c</fullName>
    <label>Date of Collection</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OrderSummary/fields/CustomerId__c.field-meta.xml
<CustomField>
    <fullName>CustomerId__c</fullName>
    <label>Customer Id</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AppointmentRemainderSchedule.cls
global with sharing class AppointmentRemainderSchedule implements Schedulable{
    global void execute(SchedulableContext sc) {   
        AppointmentRemainderEmailOutbound btch= new AppointmentRemainderEmailOutbound();
        List<String> statusList = new List<String>{'PA Approved','Pending Approval'};
        btch.statusList = statusList;
        btch.type = Label.SFOM_In_Person_Record_Type_Id;
        //btch.query = 'SELECT FulfillmentOrder.Id, FulfillmentOrder.orderSummary.OrderedDate,FulfillmentOrder.OrderSummary.OrderNumber,FulfillmentOrder.orderSummary.GrandTotalAmount,FulfillmentOrder.OrderSummary.BillingEmailAddress,FulfillmentOrder.OrderSummary.CustomerId__c,FulfillmentOrder.orderSummary.Account.PersonEmail,FulfillmentOrder.Expiration_Date__c,FulfillmentOrder.Days_Past_Confirm__c,FulfillmentOrder.OrderSummaryId FROM FulfillmentOrderLineItem WHERE FulfillmentOrder.Status =: status  and FulfillmentOrder.Days_past_Confirm__c in (6,12) and Date_of_Collection__c = null and Type!= : type and FulfillmentOrder.HUB_Success__c = true';
        btch.query = 'SELECT Id, orderSummary.OrderedDate,OrderSummary.OrderNumber,orderSummary.GrandTotalAmount,OrderSummary.BillingEmailAddress,OrderSummary.CustomerId__c,orderSummary.Account.PersonEmail,Expiration_Date__c,Days_Past_Confirm__c,OrderSummaryId FROM FulfillmentOrder WHERE RecordTypeId = :type and  Status IN : statusList  and Days_past_Confirm__c in (6,12) and HUB_Success__c = true';
        Database.executeBatch(btch,1);
      }
}