force-app/main/default/objects/FulfillmentOrder/fields/CustomerId__c.field-meta.xml
<CustomField>
    <fullName>CustomerId__c</fullName>
    <label>Customer Id</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FulfillmentOrder/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <label>Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FulfillmentOrder/fields/FulfilledToAddressLine1__c.field-meta.xml
<CustomField>
    <fullName>FulfilledToAddressLine1__c</fullName>
    <label>FulfilledToAddressLine1</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FulfillmentOrder/fields/FulfilledToAddressLine2__c.field-meta.xml
<CustomField>
    <fullName>FulfilledToAddressLine2__c</fullName>
    <label>FulfilledToAddressLine2</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FulfillmentOrder/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <label>Last Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FulfillmentOrder/fields/LID__c.field-meta.xml
<CustomField>
    <fullName>LID__c</fullName>
    <formula>&apos;SF000000000000&apos;+CASESAFEID(Id)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>LID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FulfillmentOrder/fields/MiddleName__c.field-meta.xml
<CustomField>
    <fullName>MiddleName__c</fullName>
    <label>Middle Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FulfillmentOrder/fields/Partner_Name__c.field-meta.xml
<CustomField>
    <fullName>Partner_Name__c</fullName>
    <formula>OrderSummary.Partner_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Partner Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FulfillmentOrder/fields/Physician_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Physician_First_Name__c</fullName>
    <label>Physician First Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FulfillmentOrder/fields/Physician_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Physician_Last_Name__c</fullName>
    <label>Physician Last Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FulfillmentOrder/fields/Physician_Npi__c.field-meta.xml
<CustomField>
    <fullName>Physician_Npi__c</fullName>
    <label>Physician Npi</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FulfillmentOrder/fields/Physician_Upin__c.field-meta.xml
<CustomField>
    <fullName>Physician_Upin__c</fullName>
    <label>Physician Upin</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FulfillmentOrder/fields/PWN_ID__c.field-meta.xml
<CustomField>
    <fullName>PWN_ID__c</fullName>
    <label>PA ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FulfillmentOrderLineItem/fields/AttestationJSON__c.field-meta.xml
<CustomField>
    <fullName>AttestationJSON__c</fullName>
    <label>Attestation JSON</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FulfillmentOrderLineItem/fields/PerformingSite__c.field-meta.xml
<CustomField>
    <fullName>PerformingSite__c</fullName>
    <label>Performing Site</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FulfillmentOrderLineItem/fields/Questionnaire_Submitted__c.field-meta.xml
<CustomField>
    <fullName>Questionnaire_Submitted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Questionnaire Submitted?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FulfillmentOrderLineItem/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending Approval</fullName>
                <default>true</default>
                <label>Pending Approval</label>
            </value>
            <value>
                <fullName>PA Acknowledged</fullName>
            </value>
            <value>
                <fullName>Waiting For Fulfillment</fullName>
            </value>
            <value>
                <fullName>Order Acknowledged</fullName>
            </value>
            <value>
                <fullName>Kit Shipped</fullName>
            </value>
            <value>
                <fullName>Kit Delivered</fullName>
            </value>
            <value>
                <fullName>Kit Activated</fullName>
            </value>
            <value>
                <fullName>PA Approved</fullName>
            </value>
            <value>
                <fullName>PA Rejected</fullName>
            </value>
            <value>
                <fullName>Kit PA Approved</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Sample Received</fullName>
            </value>
            <value>
                <fullName>DNA Extracted</fullName>
            </value>
            <value>
                <fullName>DNA Analyzed</fullName>
            </value>
            <value>
                <fullName>Pending Results</fullName>
            </value>
            <value>
                <fullName>Results Ready</fullName>
            </value>
            <value>
                <fullName>Order Complete</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>TNP</fullName>
            </value>
            <value>
                <fullName>DNA Extraction Failed</fullName>
                <isActive>false</isActive>
                <label>DNA Extraction Failed</label>
            </value>
            <value>
                <fullName>Kit PWN Approved</fullName>
                <isActive>false</isActive>
                <label>Kit PWN Approved</label>
            </value>
            <value>
                <fullName>PWN Acknowledged</fullName>
                <isActive>false</isActive>
                <label>PWN Acknowledged</label>
            </value>
            <value>
                <fullName>PWN Approved</fullName>
                <isActive>false</isActive>
                <label>PWN Approved</label>
            </value>
            <value>
                <fullName>PWN Rejected</fullName>
                <isActive>false</isActive>
                <label>PWN Rejected</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FulfillmentOrderLineItem/fields/Test_Type__c.field-meta.xml
<CustomField>
    <fullName>Test_Type__c</fullName>
    <formula>OrderItemSummary.TestType__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Test Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Client_Id__c.field-meta.xml
<CustomField>
    <fullName>Client_Id__c</fullName>
    <label>Client_Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/CustomerDOB__c.field-meta.xml
<CustomField>
    <fullName>CustomerDOB__c</fullName>
    <label>CustomerDOB</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/CustomerId__c.field-meta.xml
<CustomField>
    <fullName>CustomerId__c</fullName>
    <label>Customer Id</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/PreferredGender__c.field-meta.xml
<CustomField>
    <fullName>PreferredGender__c</fullName>
    <label>PreferredGender</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItemSummary/fields/attestationJSON__c.field-meta.xml
<CustomField>
    <fullName>attestationJSON__c</fullName>
    <label>Attestation JSON</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/OrderItemSummary/fields/customerID__c.field-meta.xml
<CustomField>
    <fullName>customerID__c</fullName>
    <label>Customer ID</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItemSummary/fields/HRAReq__c.field-meta.xml
<CustomField>
    <fullName>HRAReq__c</fullName>
    <defaultValue>false</defaultValue>
    <label>HRA Flag</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OrderItemSummary/fields/performingSite__c.field-meta.xml
<CustomField>
    <fullName>performingSite__c</fullName>
    <label>Performing Site</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderSummary/fields/Client_Id__c.field-meta.xml
<CustomField>
    <fullName>Client_Id__c</fullName>
    <defaultValue>TEXT(97554902)</defaultValue>
    <label>Client Id</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderSummary/fields/CustomerDOB__c.field-meta.xml
<CustomField>
    <fullName>CustomerDOB__c</fullName>
    <label>CustomerDOB</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderSummary/fields/CustomerId__c.field-meta.xml
<CustomField>
    <fullName>CustomerId__c</fullName>
    <label>Customer Id</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderSummary/fields/Partner_Name__c.field-meta.xml
<CustomField>
    <fullName>Partner_Name__c</fullName>
    <label>Partner Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderSummary/fields/PreferredGender__c.field-meta.xml
<CustomField>
    <fullName>PreferredGender__c</fullName>
    <label>PreferredGender</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Both</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Male</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/performingSite__c.field-meta.xml
<CustomField>
    <fullName>performingSite__c</fullName>
    <label>performingSite</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CancelHUBOrder.cls
public with sharing class CancelHUBOrder {
    public class CancelHUBOrderInput {
        @InvocableVariable(label='Ping Fed Token' description='Ping Fed Token')
        public String token;
        @InvocableVariable(label='FulfillmentOrderID' description='Fulfillment order ID')
        public String FOID; 
    }

    public class CancelHUBOrderOutput {
        @InvocableVariable(label='Response Message' description='Response Message from HUB Service')
        public String responseMessage;
        @InvocableVariable(label='Response Code' description='Response Code from HUB Service')
        public String responseCode;
        @InvocableVariable(label='Request Payload' description='Request Payload')
        public String requestPayload;
        @InvocableVariable(label='Response Payload' description='Response Payload')
        public String responsePayload;
        @InvocableVariable(label='SummaryID' description='SummaryID')
        public String summaryId;
        @InvocableVariable(label='Status' description='Status')
        public String status;
    }

    @InvocableMethod(label='Cancel HUB Order' description='Cancels HUB Order')
    public static List<CancelHUBOrderOutput> cancelHUBOrder(List<CancelHUBOrderInput> inputs)
    {
        List<CancelHUBOrderOutput> output = new List<CancelHUBOrderOutput>();

        for(CancelHUBOrderInput serviceInput : inputs)
        {
        CancelHUBOrderOutput serviceOutput = new CancelHUBOrderOutput();
        String foId = serviceInput.FOID;
        String token = serviceInput.token;
        
        Integer statusCode;
        String responseMessage = '';

        FulfillmentOrder fo = [select Id,OrderSummaryId,FirstName__c,LastName__c,MiddleName__c,
        OrderSummary.Client_Id__c,OrderSummary.BillingPhoneNumber,OrderSummary.CustomerId__c,
        OrderSummary.CustomerDOB__c,OrderSummary.Gender__c,OrderSummary.PreferredGender__c,
        OrderSummary.Account.FirstName,OrderSummary.Account.LastName,OrderSummary.Partner_Name__c,
        OrderSummary.BillingEmailAddress,FulfilledToAddressLine1__c,FulfilledToAddressLine2__c,
        OrderSummary.OrderNumber,LID__c,PWN_ID__c,Physician_First_Name__c,Physician_Last_Name__c,Physician_Upin__c,Physician_Npi__c,FulfilledToPhone,
                FulfilledToAddress
                                from FulfillmentOrder where Id =: foId];
            
                                Address address = fo.FulfilledToAddress;

                                                             
        List<FulfillmentOrderLineItem> items = [select Id,PerformingSite__c,Test_Type__c,Quantity,Status__c,
        FulfillmentOrderLineItem.OrderItemSummary.Name,
        FulfillmentOrderLineItem.OrderItemSummary.Description,
        FulfillmentOrderLineItem.OrderItemSummary.Product2.ProductCode,
         FulfillmentOrderLineItem.OrderItemSummary.HRAReq__c,Questionnaire_Submitted__c,
         FulfillmentOrderLineItem.OrderItemSummary.attestationJSON__c from FulfillmentOrderLineItem where FulfillmentOrderId =: foId and Test_Type__c = 'PSC'];

         String testType = items[0].Test_Type__c;
         String performingSite = items[0].PerformingSite__c;
         String gender = '';
         String addressLine1 = '';
         if(fo.OrderSummary.Gender__c == 'Male')
         {
            gender = 'M';
         }
         else if (fo.OrderSummary.Gender__c == 'Female')
         {
            gender = 'F';
         }
         if(fo.OrderSummary.Partner_Name__c == 'Google')
         {
            addressLine1 = address.street;
         }
         else {
            addressLine1 = fo.FulfilledToAddressLine1__c;
         }
         String phoneNumber = '';

         if(fo.OrderSummary.BillingPhoneNumber != null)
         {
            phoneNumber = fo.OrderSummary.BillingPhoneNumber;
         }
         else {
            phoneNumber = fo.FulfilledToPhone;
         }

         JSONGenerator gen = JSON.createGenerator(true);
        gen.writeStartObject();
            gen.writefieldName('customers');
            gen.writeStartArray();
                gen.writeStartObject();
                    gen.writeStringField('customerId', FO.OrderSummary.CustomerId__c);
                    gen.writeStringField('lastName', FO.LastName__c != null ? FO.LastName__c : fo.OrderSummary.Account.LastName );
                    gen.writeStringField('firstName', FO.FirstName__c != null ? FO.FirstName__c : fo.OrderSummary.Account.FirstName);
                    gen.writeStringField('middleName', FO.MiddleName__c != null ? FO.MiddleName__c : '');
                    gen.writeStringField('gender', gender); //we need to bring this SFCC
                    gen.writeStringField('preferredGender', '7'); //we need to bring this SFCC
                    gen.writeStringField('email', fo.OrderSummary.BillingEmailAddress);
                    gen.writefieldName('billingAddress');
                        gen.writeStartObject();
                            gen.writeStringField('addressLine1', addressLine1);
                            gen.writeStringField('addressLine2', FO.FulfilledToAddressLine2__c != null ? FO.FulfilledToAddressLine2__c : '');
                            gen.writeStringField('zip', address.PostalCode);
                            gen.writeStringField('city', address.City);
                            gen.writeStringField('state', address.State);
                            gen.writeStringField('country', address.Country);
                        gen.writeEndObject();
                    gen.writeStringField('mobilePhone', phoneNumber!= null? phoneNumber.replaceAll('[^0-9]', '') : '');
                    gen.writeStringField('homePhone', phoneNumber!= null? phoneNumber.replaceAll('[^0-9]', '') : '');
                    gen.writeStringField('birthDate', FO.OrderSummary.CustomerDOB__c != null ? FO.OrderSummary.CustomerDOB__c :'');
                    gen.writefieldName('orderSummaries');
                    gen.writeStartArray();
                        gen.writeStartObject();
                            gen.writeStringField('id', FO.OrderSummaryId);
                            gen.writeStringField('clientId', FO.OrderSummary.Client_Id__c);
                            gen.writeStringField('ecommOrderId', FO.OrderSummary.OrderNumber); 
                            gen.writeStringField('omsHomePhone', phoneNumber!= null? phoneNumber.replaceAll('[^0-9]', '') : ''); 
                            gen.writefieldName('fullfillmentOrders');
                            gen.writeStartArray();
                                gen.writeStartObject();
                                    gen.writeStringField('id', FO.Id);
                                    gen.writeStringField('pwnOrderId',Fo.PWN_ID__c); 
                                    gen.writeStringField('performingSite', performingSite); 
                                    gen.writeStringField('testType', testType);
                                    gen.writeStringField('status', 'cancelled');
                                    gen.writeStringField('lid', FO.LID__c);                                
                                gen.writefieldName('physician');
                                gen.writeStartObject();
                                    gen.writeStringField('name', FO.Physician_First_Name__c + ' ' + FO.Physician_Last_Name__c);
                                    gen.writeStringField('firstName', FO.Physician_First_Name__c != null ? FO.Physician_First_Name__c : '');
                                    gen.writeStringField('lastName', FO.Physician_Last_Name__c != null ? FO.Physician_Last_Name__c : '');
                                    gen.writeStringField('upin', FO.Physician_Upin__c != null ? FO.Physician_Upin__c : '');
                                    gen.writeStringField('npi', FO.Physician_Npi__c != null ? FO.Physician_Npi__c : '');
                                gen.writeEndObject();
                                gen.writefieldName('fullfillmentOrderItems');
                                gen.writeStartArray();
                                    for(FulfillmentOrderLineItem item : items){
                                        gen.writeStartObject();                                           
                                            gen.writeStringField('id', item.Id);
                                            gen.writeStringField('testName', item.OrderItemSummary.Name);
                                            gen.writeStringField('testCode', item.OrderItemSummary.Product2.ProductCode);
                                            gen.writeStringField('testType', item.Test_Type__c);
                                            gen.writeStringField('testDesc', item.OrderItemSummary.Description);
                                            gen.writeStringField('quantity', String.valueOf(item.Quantity));
                                            gen.writeStringField('status', 'cancelled');
                                            gen.writeBooleanField('isHra', item.OrderItemSummary.HRAReq__c);
                                            gen.writeBooleanField('questionnaireSubmitted', item.Questionnaire_Submitted__c);
                                            gen.writeBooleanField('kitActivated', false);
                                            if(item.OrderItemSummary.attestationJSON__c != null)
                                            {
                                                List<Object> aoeList = (List<Object>) JSON.deserializeUntyped(item.OrderItemSummary.attestationJSON__c);

                                                List<Map<String, Object>> attestationJSON = new List<Map<String, Object>>();
                                                for (Object obj : aoeList) {
                                                    if (obj instanceof Map<String, Object>) {
                                                        attestationJSON.add((Map<String, Object>)obj);
                                                    }
                                                }

                                                gen.writeFieldName('aoes');
                                                    gen.writeStartArray();
                                                    for (Map<String, Object> aoe : attestationJSON) {
                                                        gen.writeStartObject();  
                                                          for (String fieldName : aoe.keySet()) {
                                                            Object value = aoe.get(fieldName);
                                                            if(value != null)
                                                            {
                                                                if (value instanceof String) {
                                                                    gen.writeStringField(fieldName, (String)value);
                                                                } else if (value instanceof Decimal) {
                                                                    gen.writeStringField(fieldName, String.valueOf(value));
                                                                } else if (value instanceof Boolean) {
                                                                    gen.writeBooleanField(fieldName, (Boolean)value);
                                                                }
                                                            }
                                                        }
                                                        gen.writeEndObject();
                                                    }                                                    
                                                    gen.writeEndArray();
                                            }
                                        gen.writeEndObject();
                                    }                                    
                                gen.writeEndArray();
                            gen.writeEndObject();
                        gen.writeEndArray();
                    gen.writeEndObject();
                gen.writeEndArray();
            gen.writeEndObject();
        gen.writeEndArray();
    gen.writeEndObject();

        System.debug(gen.getAsString());

        serviceOutput = callHubService(gen.getAsString(),token,FO.OrderSummaryId);
        output.add(serviceOutput);
        }
        return output;

    }
    
    private static CancelHUBOrderOutput callHubService(String requestJSON,String token,String orderSummaryId)
    {
        CancelHUBOrderOutput serviceOutput= new CancelHUBOrderOutput();
        Http http = new Http();
        HttpResponse response;
        HttpRequest request = new HttpRequest();
        
        Integer statusCode;
        try{
            
            String endpoint = Label.OMS_Mule_Proxy_Ednpoint;
            request.setEndpoint(endpoint+'qdx-quanum-hub-proxy-api/orders');
            request.setMethod('PATCH');
            request.setHeader('Content-Type','application/json');
            request.setHeader('Authorization','Bearer ' + token);
            request.setTimeout(60000);
            request.setBody(requestJSON);
            System.debug('Request::'+request);

            serviceOutput.summaryId = orderSummaryId;
            serviceOutput.requestPayload = requestJSON;

            response = http.send(request); 
            statusCode = response.getStatusCode(); 

            Map<String, Object> jsonResponseMap = (Map<String, Object>)JSON.deserializeUntyped(response.getBody());
            
           
            
            serviceOutput.responsePayload = response.getBody();

                if(statusCode==200){
                    serviceOutput.responseCode=String.valueOf(statusCode);
                    serviceOutput.responseMessage='Success';
                    serviceOutput.status='Success';
                }
                else if(statusCode==504){
                    serviceOutput.responseCode=String.valueOf(statusCode);
                    serviceOutput.responseMessage='Timeout';
                    serviceOutput.status='Timeout Error';
                }
                else {      
                    String errorMessage='';          
                    if (jsonResponseMap.containsKey('error')) {
                        Map<String, Object> errorMap = (Map<String, Object>) jsonResponseMap.get('error');
                        Map<String, Object> faultMap = (Map<String, Object>) errorMap.get('fault');
                        List<Object> messageList = (List<Object>) faultMap.get('message');
                        errorMessage = String.join(messageList, ' ');
                    }
                    serviceOutput.responseCode=String.valueOf(statusCode);
                    serviceOutput.responseMessage=errorMessage;
                    serviceOutput.status='Error';
                }

                
          }
          catch(Exception e){
            if(response != null)
            {
                serviceOutput.responseCode=String.valueOf(statusCode);
                serviceOutput.responseMessage=response.getStatus() + ' Message: ' + response.getBody();
                serviceOutput.responsePayload = response.getBody();
            }
            else {
                serviceOutput.responseMessage=e.getMessage();
                serviceOutput.responsePayload = e.getMessage();
                serviceOutput.responseCode='504';
            }
            serviceOutput.status='Error';
            System.debug('Failed to create Transaction' + e.getMessage());
          }
          
          return serviceOutput;
    } 
}