force-app/main/default/objects/FulfillmentOrder/fields/CustomerId__c.field-meta.xml
<CustomField>
    <fullName>CustomerId__c</fullName>
    <label>Customer Id</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FulfillmentOrder/fields/Days_to_expire__c.field-meta.xml
<CustomField>
    <fullName>Days_to_expire__c</fullName>
    <formula>IF(AND(RecordType.DeveloperName = &apos;InPerson&apos;,
  ISPICKVAL(Status, &apos;PWN Approved&apos;)
  ), 
   PWN_Status_Date__c +65 - TODAY(),9999
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Days to expire</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FulfillmentOrder/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <formula>IF(ISBLANK(PWN_Status_Date__c), DATEVALUE( CreatedDate )  +65,PWN_Status_Date__c+65)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OrderSummary/fields/CustomerId__c.field-meta.xml
<CustomField>
    <fullName>CustomerId__c</fullName>
    <label>Customer Id</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ExpiryEmailSchedule.cls
global with sharing class ExpiryEmailSchedule implements Schedulable{
    global void execute(SchedulableContext sc) {   
        ExpiryEmailOutbound btch= new ExpiryEmailOutbound();
        btch.status = 'PA Approved';
        btch.query = 'SELECT Id, orderSummary.OrderedDate,OrderSummary.OrderNumber,orderSummary.GrandTotalAmount,OrderSummary.BillingEmailAddress,OrderSummary.CustomerId__c,orderSummary.Account.PersonEmail,Expiration_Date__c,Days_to_expire__c,OrderSummaryId FROM FulfillmentOrder WHERE Status =: status  and Days_to_Expire__c in (30,10,7,3)';
        Database.executeBatch(btch,1);
      }
}