force-app/main/default/objects/FulfillmentOrder/fields/Eligible_to_Expire__c.field-meta.xml
<CustomField>
    <fullName>Eligible_to_Expire__c</fullName>
    <formula>IF(RecordType.DeveloperName = &apos;InPerson&apos;,

AND(  
ISPICKVAL(Status, &apos;Pending Approval&apos;),
TODAY()&gt; DATEVALUE(CreatedDate)+ 65
),
No_Of_Expired_Items__c = ItemCount
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Eligible to Expire?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FulfillmentOrder/fields/Service_Fee__c.field-meta.xml
<CustomField>
    <fullName>Service_Fee__c</fullName>
    <label>Cancellation Charge</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/SFOMFOExpirationBatchSchedule.cls
/**
  Class Name:: SFOMFOExpirationBatchSchedule
  Description:: Schedulable class for SFOMFulfillmentOrderExpirationBatch
**/

global class SFOMFOExpirationBatchSchedule implements Schedulable {

   global void execute(SchedulableContext sc) {   
    SFOMFulfillmentOrderExpirationBatch btch = new SFOMFulfillmentOrderExpirationBatch();
    btch.StatusExpired = Label.SFOM_FO_Status_Expired;
    btch.recordType=Label.SFOM_In_Person_Record_Type_Id;
     btch.recordcreatedDate = Date.today() - 90;
    btch.Query = 'Select Id,RecordTypeId,InvoiceId,Status,OrderSummaryId,GrandTotalAmount,Service_Fee__c from FulfillmentOrder where Eligible_to_Expire__c = true and RecordTypeId=: recordType and  Status!=:StatusExpired AND CreatedDate >=:recordcreatedDate ';
    Database.executeBatch(btch,1);
   }
   
}