force-app/main/default/objects/FulfillmentOrder/fields/Eligible_to_Expire__c.field-meta.xml
<CustomField>
    <fullName>Eligible_to_Expire__c</fullName>
    <formula>IF(RecordType.DeveloperName = &apos;InPerson&apos;,

AND(  
ISPICKVAL(Status, &apos;Pending Approval&apos;),
TODAY()&gt; DATEVALUE(CreatedDate)+ 65
),
No_Of_Expired_Items__c = ItemCount
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Eligible to Expire?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FulfillmentOrder/fields/Service_Fee__c.field-meta.xml
<CustomField>
    <fullName>Service_Fee__c</fullName>
    <label>Cancellation Charge</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FulfillmentOrder/recordTypes/InPerson.recordType-meta.xml
<RecordType>
    <fullName>InPerson</fullName>
    <active>true</active>
    <label>In Person</label>
</RecordType>

force-app/main/default/objects/Lab_Order__c/Lab_Order__c.object-meta.xml
<CustomObject>
    <label>Lab Order</label>
    <nameField>
        <label>Lab Order ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lab Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lab_Order__c/fields/Eligible_To_Expire__c.field-meta.xml
<CustomField>
    <fullName>Eligible_To_Expire__c</fullName>
    <formula>IF(AND(
ISPICKVAL(Status__c, &apos;PA Approved&apos;),
TODAY() &gt;
PWN_Status_Date__c + 65
), true, false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Eligible To Expire</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/FO_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>FO_Record_Type__c</fullName>
    <formula>IF( Is_Kit__c , Kit_Detail__r.Type__c , &apos;InPerson&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>FO Record Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Fulfillment_Order__c.field-meta.xml
<CustomField>
    <fullName>Fulfillment_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fulfillment Order</label>
    <referenceTo>FulfillmentOrder</referenceTo>
    <relationshipLabel>Lab Orders</relationshipLabel>
    <relationshipName>Lab_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Is_Partner__c.field-meta.xml
<CustomField>
    <fullName>Is_Partner__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Partner</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Order_Summary__c.field-meta.xml
<CustomField>
    <fullName>Order_Summary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Summary</label>
    <referenceTo>OrderSummary</referenceTo>
    <relationshipLabel>Lab Orders</relationshipLabel>
    <relationshipName>Lab_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderSummary/fields/Service_Fee__c.field-meta.xml
<CustomField>
    <fullName>Service_Fee__c</fullName>
    <label>Non-Refundable Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/LabOrderExpiryBatchSchedule.cls
global with sharing class LabOrderExpiryBatchSchedule implements Schedulable{
    global void execute(SchedulableContext sc) {   
        LabOrderExpiryBatch btch= new LabOrderExpiryBatch();
        btch.recordType='InPerson';
        btch.query = 'SELECT Id, Is_Partner__c,Order_Summary__c,Order_Summary__r.OriginalOrderId,Fulfillment_Order__c,Fulfillment_Order__r.GrandTotalAmount,Fulfillment_Order__r.Service_Fee__c FROM Lab_Order__c WHERE Eligible_To_Expire__c =true  and FO_Record_Type__c =: recordType   ';
        Database.executeBatch(btch,1);
      }
}