force-app/main/default/objects/FulfillmentOrder/fields/Location_Name__c.field-meta.xml
<CustomField>
    <fullName>Location_Name__c</fullName>
    <formula>FulfilledFromLocation.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Location Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FulfillmentOrder/fields/Shipment_Success__c.field-meta.xml
<CustomField>
    <fullName>Shipment_Success__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Shipment Success</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/QuestTPTShipmentSchedule.cls
global with sharing class QuestTPTShipmentSchedule implements Schedulable{
    global void execute(SchedulableContext sc) {   
        QuestTPTShipmentBatch btch= new QuestTPTShipmentBatch();
        btch.status = 'Order Acknowledged';
        btch.query = 'SELECT Id, OrderSummaryId,Location_Name__c FROM FulfillmentOrder WHERE Status =: status and Shipment_Success__c =true ';
        Database.executeBatch(btch,1);
      }
    }