force-app/main/default/objects/Lab_Order__c/Lab_Order__c.object-meta.xml
<CustomObject>
    <label>Lab Order</label>
    <nameField>
        <label>Lab Order ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lab Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lab_Order__c/fields/Cancellation_Service_Fee__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Service_Fee__c</fullName>
    <label>Cancellation Service Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Client_ID__c.field-meta.xml
<CustomField>
    <fullName>Client_ID__c</fullName>
    <label>Client ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Client_Name__c.field-meta.xml
<CustomField>
    <fullName>Client_Name__c</fullName>
    <label>Partner Client Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/External_Partner_Order_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Partner_Order_Id__c</fullName>
    <externalId>true</externalId>
    <label>External Partner Order Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Is_Partner__c.field-meta.xml
<CustomField>
    <fullName>Is_Partner__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Partner</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Partner_Client_Map__c.field-meta.xml
<CustomField>
    <fullName>Partner_Client_Map__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner Client Map</label>
    <referenceTo>PartnerClientMap__c</referenceTo>
    <relationshipLabel>Lab Orders</relationshipLabel>
    <relationshipName>Lab_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Payment_Transaction_Id__c.field-meta.xml
<CustomField>
    <fullName>Payment_Transaction_Id__c</fullName>
    <externalId>true</externalId>
    <label>Payment Transaction Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Person_Record__c.field-meta.xml
<CustomField>
    <fullName>Person_Record__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Person Record</label>
    <referenceTo>Person_Record__c</referenceTo>
    <relationshipLabel>Lab Orders</relationshipLabel>
    <relationshipName>Lab_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Refund_Amount__c.field-meta.xml
<CustomField>
    <fullName>Refund_Amount__c</fullName>
    <label>Refund Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Refund_Attempts__c.field-meta.xml
<CustomField>
    <fullName>Refund_Attempts__c</fullName>
    <label>Refund Attempts</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/shl_encryption_key__c.field-meta.xml
<CustomField>
    <fullName>shl_encryption_key__c</fullName>
    <description>smart on FHIR encryption key</description>
    <label>shl_key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/shl_location__c.field-meta.xml
<CustomField>
    <fullName>shl_location__c</fullName>
    <description>location reference for apple health record</description>
    <externalId>true</externalId>
    <label>shl_location</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>PA Acknowledged</fullName>
            </value>
            <value>
                <fullName>PA Approved</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Partial Results Ready</fullName>
            </value>
            <value>
                <fullName>Results Ready</fullName>
            </value>
            <value>
                <fullName>PA Rejected</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>PWN Acknowledged</fullName>
                <isActive>false</isActive>
                <label>PWN Acknowledged</label>
            </value>
            <value>
                <fullName>PWN Approved</fullName>
                <isActive>false</isActive>
                <label>PWN Approved</label>
            </value>
            <value>
                <fullName>PWN Rejected</fullName>
                <isActive>false</isActive>
                <label>PWN Rejected</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lab_Order_Panel__c/Lab_Order_Panel__c.object-meta.xml
<CustomObject>
    <label>Lab Order Panel</label>
    <nameField>
        <displayFormat>PNID- {000000000}</displayFormat>
        <label>Lab Panel ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lab Order Panels</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Lab_Order_Panel__c/fields/Lab_Order__c.field-meta.xml
<CustomField>
    <fullName>Lab_Order__c</fullName>
    <label>Lab Order</label>
    <referenceTo>Lab_Order__c</referenceTo>
    <relationshipName>Lab_Order_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Lab_Order_Panel__c/fields/Panel__c.field-meta.xml
<CustomField>
    <fullName>Panel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Panel</label>
    <referenceTo>Panel__c</referenceTo>
    <relationshipName>Lab_Order_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lab_Order_Panel__c/fields/Panel_Code__c.field-meta.xml
<CustomField>
    <fullName>Panel_Code__c</fullName>
    <formula>Panel__r.Panel_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Panel Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lab_Order_Panel__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Results Ready</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>TNP</fullName>
            </value>
            <value>
                <fullName>PA Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Partial Results Ready</fullName>
            </value>
            <value>
                <fullName>PWN Rejected</fullName>
                <isActive>false</isActive>
                <label>PWN Rejected</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lab_Panel_Test__c/Lab_Panel_Test__c.object-meta.xml
<CustomObject>
    <label>Lab Panel Test</label>
    <nameField>
        <displayFormat>TID - {00000000}</displayFormat>
        <label>Lab Panel Test ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lab Panel Tests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Lab_Panel_Test__c/fields/Lab_Order__c.field-meta.xml
<CustomField>
    <fullName>Lab_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lab Order</label>
    <referenceTo>Lab_Order__c</referenceTo>
    <relationshipLabel>Lab Panel Tests</relationshipLabel>
    <relationshipName>Lab_Panel_Tests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lab_Panel_Test__c/fields/Lab_Order_Panel__c.field-meta.xml
<CustomField>
    <fullName>Lab_Order_Panel__c</fullName>
    <label>Lab Order Panel</label>
    <referenceTo>Lab_Order_Panel__c</referenceTo>
    <relationshipName>Lab_Panel_Analytes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Lab_Panel_Test__c/fields/Panel_Test__c.field-meta.xml
<CustomField>
    <fullName>Panel_Test__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Panel Test ID</label>
    <referenceTo>Panel_Test__c</referenceTo>
    <relationshipLabel>Lab Panel Tests</relationshipLabel>
    <relationshipName>Lab_Panel_Analytes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lab_Panel_Test__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Test Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>TNP</fullName>
            </value>
            <value>
                <fullName>Results Ready</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>PA Rejected</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Partial Results Ready</fullName>
            </value>
            <value>
                <fullName>PWN Rejected</fullName>
                <isActive>false</isActive>
                <label>PWN Rejected</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lab_Panel_Test__c/fields/Test_Code__c.field-meta.xml
<CustomField>
    <fullName>Test_Code__c</fullName>
    <formula>Panel_Test__r.Test__r.Test_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Test Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lab_Panel_Test__c/fields/Test_Name__c.field-meta.xml
<CustomField>
    <fullName>Test_Name__c</fullName>
    <formula>Panel_Test__r.Test__r.Test_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Test Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Panel__c/Panel__c.object-meta.xml
<CustomObject>
    <label>Panel</label>
    <nameField>
        <displayFormat>PR-{00000000}</displayFormat>
        <label>Panel Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Panels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Panel__c/fields/Panel_Code__c.field-meta.xml
<CustomField>
    <fullName>Panel_Code__c</fullName>
    <label>Panel Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Panel__c/fields/Panel_Name__c.field-meta.xml
<CustomField>
    <fullName>Panel_Name__c</fullName>
    <label>Panel Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Panel_Test__c/Panel_Test__c.object-meta.xml
<CustomObject>
    <label>Panel Test</label>
    <nameField>
        <displayFormat>PTR - {000000000}</displayFormat>
        <label>Panel Test ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Panel Tests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Panel_Test__c/fields/Panel__c.field-meta.xml
<CustomField>
    <fullName>Panel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Panel</label>
    <referenceTo>Panel__c</referenceTo>
    <relationshipName>Panel_Analytes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Panel_Test__c/fields/Test__c.field-meta.xml
<CustomField>
    <fullName>Test__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Test</label>
    <referenceTo>Test__c</referenceTo>
    <relationshipLabel>Panel Tests</relationshipLabel>
    <relationshipName>Panel_Analytes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PartnerClientMap__c/PartnerClientMap__c.object-meta.xml
<CustomObject>
    <label>Partner Client Map</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PartnerClientMaps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PartnerClientMap__c/fields/Partner_Name__c.field-meta.xml
<CustomField>
    <fullName>Partner_Name__c</fullName>
    <label>Partner Name</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/PartnerClientMap__c/fields/Payment_Key__c.field-meta.xml
<CustomField>
    <fullName>Payment_Key__c</fullName>
    <label>Payment Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PartnerClientMap__c/fields/Sales_Channel__c.field-meta.xml
<CustomField>
    <fullName>Sales_Channel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Channel</label>
    <referenceTo>SalesChannel</referenceTo>
    <relationshipLabel>PartnerClientMaps</relationshipLabel>
    <relationshipName>PartnerClientMaps</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PartnerClientMap__c/fields/Suppress_Reminder_Email__c.field-meta.xml
<CustomField>
    <fullName>Suppress_Reminder_Email__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Suppress Reminder Email</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/PartnerLabOrderRefundTest.cls
@isTest

public class PartnerLabOrderRefundTest {

    private static Id testSetupMethod(){
        SFMC_OMS_Config__c config = new SFMC_OMS_Config__c();
        config.Channel__c = 'QD-CIT';
        config.API__c = 'Common';
        config.Auth_Token__c = 'TestAuthToken';
        insert config;
        
        // Create mock Lab_Order__c and Lab_Panel_Test__c records
        Account ac = new Account();
        ac.Name = 'Test account';
        insert ac;
        
        Contact con = new Contact();
        con.lastName = 'test con';
        con.Email = 'test@gmail.com';
        con.AccountId = ac.Id;
        con.Phone = '234-234-2342' ;
        insert con;
        
        SalesChannel SC = new SalesChannel();	
        SC.SalesChannelName = 'QDCIT Partner';
        SC.Description = 'QDCIT Partner';
        insert SC;
        
        PartnerClientMap__c PCM = new PartnerClientMap__c();
        PCM.Name = 'Google'; 
        PCM.Sales_Channel__c = SC.Id;
        PCM.Partner_Name__c = 'Google';
        PCM.Client_ID__c = '34566';
        PCM.Suppress_Reminder_Email__c = false;
        pcm.Payment_Key__c='hhgasskkhkj';
        insert PCM;
        
        
        Panel__c p = new Panel__c();
        p.Panel_Code__c = '12767';
        p.Panel_Name__c = 'test panel';
        insert p;
        
        Test__c t = new Test__c();
        t.Test_Code__c = '12767';
        t.Test_Name__c = 'demo test';
        insert t;
        
        
        Person_Record__c pr = new Person_Record__c();
        pr.Email__c= 'test@gmail.com';
        pr.First_Name__c= 'Fname';
        pr.Last_Name__c= 'LName';
        pr.Phone__c= '4569990422';
        pr.Gender__c = 'Male';
        pr.Contact__c = con.Id;
        pr.Date_of_Birth__c=  date.valueOf('2000-12-12');
        pr.Address_Line_1__c= 'gfds';
        pr.City__c= 'Santa Barbara';
        pr.State__c= 'CA';
        pr.Postal_Code__c= '93110';
        pr.Country__c = 'US';
        pr.Unique_Identifier__c = 'test@gmail.com'+':'+'2000-12-12'+':'+'LName';
        insert pr;
        
        Lab_order__c lb = new Lab_Order__c();
        lb.Person_Record__c = pr.id;
        lb.Partner_Client_Map__c = PCM.id;
        lb.Client_Name__c = 'saturn';
        lb.Name = 'clientName';
        lb.Status__c = 'Registered';
        lb.Is_Partner__c = true;
        lb.External_Partner_Order_Id__c = '123';
        lb.shl_encryption_key__c = 'shl_encryption';
        lb.shl_location__c = 'shl_location';
         lb.Payment_Transaction_Id__c = 'dasdasdasdasdasd';
          lb.Cancellation_Service_Fee__c = 10.00;
          lb.Refund_Amount__c=80.00;
          lb.Refund_Attempts__c=1;
        insert lb;
        
        Panel_Test__c pt = new Panel_Test__c();
        pt.Panel__c = p.id;
        pt.Test__c = t.Id;
        insert pt;
        
        Lab_Order_Panel__c LOP = new Lab_Order_Panel__c();
        LOP.HRA_Req__c = true;
        LOP.Lab_Order__c = lb.id;
        LOP.Panel__c = p.id;
        insert LOP;
        
        Lab_Panel_Test__c lbt = new Lab_Panel_Test__c();
        lbt.Lab_Order_Panel__c = LOP.id;
        lbt.Status__c = 'Registered';
        lbt.Panel_Test__c = pt.id;
        insert lbt;

        return lb.id;
    }

    @IsTest 
    public static void PartnerLabOrderRefundTest3 () {
          
        System.Test.setMock(HttpCalloutMock.class, new MockPRSProxyHelperHttpResponse(200,'{"amount_received":100.00}'));
       
       Id labOrderId = testSetupMethod();
        PartnerLabOrderRefund.Request PLR = new PartnerLabOrderRefund.Request();
        PLR.paymentIntentId = 'shsnkidvekdbdk283463';
        PLR.fullRefund = true;
        PLR.labOrderId = labOrderId;
        PLR.paymentKey = 'sdfghjkjhgfdrtyujk';
        PLR.cancellationFee = 10.00;
	    Test.startTest();
		List<PartnerLabOrderRefund.Request> lstPLR = new List<PartnerLabOrderRefund.Request>();
        lstPLR.add(PLR);
        PartnerLabOrderRefund.refundPartnerOrder(lstPLR);
        Test.stopTest();
    }
    
    @IsTest 
    public static void PartnerLabOrderRefundTest1 () {
          
        System.Test.setMock(HttpCalloutMock.class, new MockPRSProxyHelperHttpResponse(200,'{"amount_received":100.00}'));
       
        Id labOrderId = testSetupMethod();
        PartnerLabOrderRefund.Request PLR = new PartnerLabOrderRefund.Request();
        PLR.paymentIntentId = 'shsnkidvekdbdk283463';
        PLR.fullRefund = true;
        PLR.labOrderId = labOrderId;
        PLR.paymentKey = 'sdfghjkjhgfdrtyujk';
        PLR.cancellationFee = 10.00;
	    Test.startTest();
		List<PartnerLabOrderRefund.Request> lstPLR = new List<PartnerLabOrderRefund.Request>();
        lstPLR.add(PLR);
        PartnerLabOrderRefund.refundPartnerOrder(lstPLR);
        Test.stopTest();
    }
    
     @IsTest 
    public static void PartnerLabOrderRefundTest2 () {
          
        System.Test.setMock(HttpCalloutMock.class, new MockPRSProxyHelperHttpResponse(400,'{"amount_received":100.00}'));
       
         Id labOrderId = testSetupMethod();
        PartnerLabOrderRefund.Request PLR = new PartnerLabOrderRefund.Request();
        PLR.paymentIntentId = 'shsnkidvekdbdk283463';
        PLR.fullRefund = true;
        PLR.labOrderId = labOrderId;
        PLR.paymentKey = 'sdfghjkjhgfdrtyujk';
        PLR.cancellationFee = 10.00;
	    Test.startTest();
		List<PartnerLabOrderRefund.Request> lstPLR = new List<PartnerLabOrderRefund.Request>();
        lstPLR.add(PLR);
        PartnerLabOrderRefund.refundPartnerOrder(lstPLR);
        Test.stopTest();
    }
    
    @IsTest 
    public static void PartnerLabOrderRefundTest5 () {
           System.Test.setMock(HttpCalloutMock.class, new SendOrderDetailsToPHMock1());
       
       
         Id labOrderId = testSetupMethod();
        PartnerLabOrderRefund.Request PLR = new PartnerLabOrderRefund.Request();
        PLR.paymentIntentId = 'shsnkidvekdbdk283463';
        PLR.fullRefund = true;
        PLR.labOrderId = labOrderId;
        PLR.paymentKey = 'sdfghjkjhgfdrtyujk';
        PLR.cancellationFee = 10.00;
	    Test.startTest();
		List<PartnerLabOrderRefund.Request> lstPLR = new List<PartnerLabOrderRefund.Request>();
        lstPLR.add(PLR);
        PartnerLabOrderRefund.refundPartnerOrder(lstPLR);
        Test.stopTest();
    }

    @IsTest 
    public static void PartnerLabOrderRefundTest6 () {
           System.Test.setMock(HttpCalloutMock.class, new SendOrderDetailsToPHMock1());
       
       
         Id labOrderId = testSetupMethod();
       
	    Test.startTest();
		PartnerLabOrderRefundRetryBatch btch= new PartnerLabOrderRefundRetryBatch();
        btch.labOrderId= labOrderId;
        btch.query = 'SELECT Id, Payment_Transaction_Id__c,Captured_Amount__c,Cancellation_Service_Fee__c,Refund_Amount__c,Refund_Attempts__c,Partner_Client_Map__r.Payment_Key__c FROM Lab_Order__c WHERE Id =:labOrderId';
        Database.executeBatch(btch,1);
        Test.stopTest();
    }

     @IsTest 
    public static void PartnerLabOrderRefundTest7 () {
           System.Test.setMock(HttpCalloutMock.class, new SendOrderDetailsToPHMock());
       
       
         Id labOrderId = testSetupMethod();
       
	    Test.startTest();
		PartnerLabOrderRefundRetryBatch btch= new PartnerLabOrderRefundRetryBatch();
        btch.labOrderId= labOrderId;
        btch.query = 'SELECT Id, Payment_Transaction_Id__c,Captured_Amount__c,Cancellation_Service_Fee__c,Refund_Amount__c,Refund_Attempts__c,Partner_Client_Map__r.Payment_Key__c FROM Lab_Order__c WHERE Id =:labOrderId';
        Database.executeBatch(btch,1);
        Test.stopTest();
    }
    
    @IsTest 
    public static void PartnerLabOrderRefundTest4 () {
           System.Test.setMock(HttpCalloutMock.class, new SendOrderDetailsToPHMock());
       
       
       Id labOrderId = testSetupMethod();
        PartnerLabOrderRefund.Request PLR = new PartnerLabOrderRefund.Request();
        PLR.paymentIntentId = 'shsnkidvekdbdk283463';
        PLR.fullRefund = true;
        PLR.labOrderId = labOrderId;
        PLR.paymentKey = 'sdfghjkjhgfdrtyujk';
        PLR.cancellationFee = 10.00;
	    Test.startTest();
		List<PartnerLabOrderRefund.Request> lstPLR = new List<PartnerLabOrderRefund.Request>();
        lstPLR.add(PLR);
        PartnerLabOrderRefund.refundPartnerOrder(lstPLR);
        Test.stopTest();
    }

     @IsTest 
    static void ScheduleClassTerritoryCheck () {
        PartnerLabOrderRefundRetryBatchSchedule  obj = new PartnerLabOrderRefundRetryBatchSchedule();
        String sch = '0 0 23 * * ?'; 
        system.schedule('Test Territory Check', sch, obj); 
  }   
    
     public class SendOrderDetailsToPHMock implements HttpCalloutMock{
        public HttpResponse respond(HttpRequest req1){
            HttpResponse res1 = new HttpResponse();
            res1.setHeader('Content-Type', 'application/x-www-form-urlencoded');
            if(req1.getEndPoint().contains('refunds')){
                res1.setBody('{"amount_received":10000.00}');
                res1.setStatusCode(400);
            }
            else{
                res1.setbody('{"amount_received":10000.00}');
                res1.setStatusCode(200);
            }
            return res1;
        }
    }
    
    public class SendOrderDetailsToPHMock1 implements HttpCalloutMock{
        public HttpResponse respond(HttpRequest req1){
            HttpResponse res1 = new HttpResponse();
            res1.setHeader('Content-Type', 'application/x-www-form-urlencoded');
            if(req1.getEndPoint().contains('refunds')){
                res1.setBody('{"amount_received":10000.00}');
                res1.setStatusCode(200);
            }
            else{
                res1.setbody('{"amount_received":10000.00}');
                res1.setStatusCode(200);
            }
            return res1;
        }
    }

    
     private class MockPRSProxyHelperHttpResponse implements HttpCalloutMock {
        private Integer statusCode;
        private String responseBody;
        
        public MockPRSProxyHelperHttpResponse(Integer statusCode, String responseBody) {
            this.statusCode = statusCode;
            this.responseBody = responseBody;
        }
        
        public HTTPResponse respond(HTTPRequest req) {
            HttpResponse res = new HttpResponse();
            res.setStatusCode(statusCode);
            res.setBody(responseBody);
            return res;
        }
    }
}