force-app/main/default/objects/Lab_Order__c/Lab_Order__c.object-meta.xml
<CustomObject>
    <label>Lab Order</label>
    <nameField>
        <label>Lab Order ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lab Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lab_Order__c/fields/FO_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>FO_Record_Type__c</fullName>
    <formula>IF( Is_Kit__c , Kit_Detail__r.Type__c , &apos;InPerson&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>FO Record Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Is_Kit__c.field-meta.xml
<CustomField>
    <fullName>Is_Kit__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Kit</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Is_PWN_Approved__c.field-meta.xml
<CustomField>
    <fullName>Is_PWN_Approved__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is PA Approved</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Kit_Detail__c.field-meta.xml
<CustomField>
    <fullName>Kit_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Kit Detail</label>
    <referenceTo>Kit_Details__c</referenceTo>
    <relationshipLabel>Lab Orders</relationshipLabel>
    <relationshipName>Lab_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Prescriptive_Authority__c.field-meta.xml
<CustomField>
    <fullName>Prescriptive_Authority__c</fullName>
    <description>Used to determine the prescriptive authority on Partner Lab Orders</description>
    <label>Prescriptive Authority</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/PWN_ID__c.field-meta.xml
<CustomField>
    <fullName>PWN_ID__c</fullName>
    <externalId>true</externalId>
    <label>PA External ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/PWN_Success__c.field-meta.xml
<CustomField>
    <fullName>PWN_Success__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PA Success</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>PA Acknowledged</fullName>
            </value>
            <value>
                <fullName>PA Approved</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Partial Results Ready</fullName>
            </value>
            <value>
                <fullName>Results Ready</fullName>
            </value>
            <value>
                <fullName>PA Rejected</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>PWN Acknowledged</fullName>
                <isActive>false</isActive>
                <label>PWN Acknowledged</label>
            </value>
            <value>
                <fullName>PWN Approved</fullName>
                <isActive>false</isActive>
                <label>PWN Approved</label>
            </value>
            <value>
                <fullName>PWN Rejected</fullName>
                <isActive>false</isActive>
                <label>PWN Rejected</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/GSSPWNPollingschedule.cls
global with sharing class GSSPWNPollingschedule implements Schedulable{
    global void execute(SchedulableContext sc) {   
        GSSPWNPollingJob btch= new GSSPWNPollingJob();
        List<String> statusList = new List<String>{'Cancelled','Expired','PA Rejected'};
        String recordType = 'GSS';
        btch.type= recordType;
        btch.statusList = statusList;
        btch.query = 'SELECT Id,Is_Kit__c,Kit_Detail__c, PWN_ID__c FROM Lab_Order__c WHERE Status__c NOT IN : statusList  and Is_PWN_Approved__c = false and PWN_Success__c = true and FO_Record_Type__c = : type AND Prescriptive_Authority__c != \'SMD\' Order by createdDate LIMIT 100';
        Database.executeBatch(btch,100);
      }
}