force-app/main/default/objects/Lab_Order__c/Lab_Order__c.object-meta.xml
<CustomObject>
    <label>Lab Order</label>
    <nameField>
        <label>Lab Order ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lab Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lab_Order__c/fields/Appointment_Confirmation_Code__c.field-meta.xml
<CustomField>
    <fullName>Appointment_Confirmation_Code__c</fullName>
    <label>Appointment Confirmation Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Client_ID__c.field-meta.xml
<CustomField>
    <fullName>Client_ID__c</fullName>
    <label>Client ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Lab_Order_ID_Uppercase__c.field-meta.xml
<CustomField>
    <fullName>Lab_Order_ID_Uppercase__c</fullName>
    <formula>UPPER(CASESAFEID(Id))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Lab Order ID Uppercase</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Partner_Client_Map__c.field-meta.xml
<CustomField>
    <fullName>Partner_Client_Map__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner Client Map</label>
    <referenceTo>PartnerClientMap__c</referenceTo>
    <relationshipLabel>Lab Orders</relationshipLabel>
    <relationshipName>Lab_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lab_Order_Panel__c/Lab_Order_Panel__c.object-meta.xml
<CustomObject>
    <label>Lab Order Panel</label>
    <nameField>
        <displayFormat>PNID- {000000000}</displayFormat>
        <label>Lab Panel ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lab Order Panels</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Lab_Order_Panel__c/fields/Lab_Order__c.field-meta.xml
<CustomField>
    <fullName>Lab_Order__c</fullName>
    <label>Lab Order</label>
    <referenceTo>Lab_Order__c</referenceTo>
    <relationshipName>Lab_Order_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Lab_Order_Panel__c/fields/Performing_Site__c.field-meta.xml
<CustomField>
    <fullName>Performing_Site__c</fullName>
    <formula>IF(Lab_Order__r.Is_Kit__c , Lab_Order__r.Kit_Detail__r.PerformingSite__c ,IF( Lab_Order__r.Is_Partner__c, IF(ISBLANK(Panel__r.Product__r.performingSite__c),&apos;PHP&apos;,Panel__r.Product__r.performingSite__c) ,Fulfillment_Order_Product__r.PerformingSite__c) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Performing Site</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Client_Id__c.field-meta.xml
<CustomField>
    <fullName>Client_Id__c</fullName>
    <label>Client_Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PartnerClientMap__c/PartnerClientMap__c.object-meta.xml
<CustomObject>
    <label>Partner Client Map</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PartnerClientMaps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/PublishAppointmentConfirmation.cls
public without sharing class PublishAppointmentConfirmation {
    public class Request {
        @InvocableVariable(label='Lab Order id' description='Lab Order Id')
        public String labOrderId; 
    }

    public class Response {
        
        @InvocableVariable(label='Response Message' description='Response Message from PWN Service')
        public String responseMessage;
        @InvocableVariable(label='Response Code' description='Response Code from PWN Service')
        public String responseCode;
        @InvocableVariable(label='Request Payload' description='Request Payload')
        public String requestPayload;
        @InvocableVariable(label='Response Payload' description='Response Payload')
        public String responsePayload;
        @InvocableVariable(label='Lab Order Id' description='LabOrderId')
        public String labOrderId;
        @InvocableVariable(label='Status' description='Status')
        public String status;
    }

    @InvocableMethod(label='Publish Appointment Confirmation' description='Publish Appointment Confirmation')
    public static List<Response> sendRequest(List<Request> requests)    
    {
        List<Response> responses = new List<Response>();

       
            for(Request request : requests)
            {
                Integer statusCode;
                String responseMessage = '';
                Http http = new Http();
                HttpResponse httpResponse;
                HttpRequest httpRequest = new HttpRequest();
                Response response = new Response();
                Lab_Order__c labOrder = [select Id,Lab_Order_ID_Uppercase__c,Partner_Client_Map__r.Client_ID__c,Appointment_Confirmation_Code__c  from Lab_Order__c where Id =: request.labOrderId];

                List<Lab_Order_Panel__c> tests = [ SELECT Id, Performing_Site__c FROM Lab_Order_Panel__c WHERE Lab_Order__c =: request.labOrderId ];
                
                String performingSite = tests[0].Performing_Site__c;

                Map<String, Object> payload = new Map<String, Object>{
                    'appointmentConfirmation' => labOrder.Appointment_Confirmation_Code__c,
                    'labReferenceID' => labOrder.Lab_Order_ID_Uppercase__c,
                    'performingSite' => performingSite,
                    'clientNumber' => labOrder.Partner_Client_Map__r.Client_ID__c
                };

                String jsonPayload = JSON.serialize(payload);

                String endpoint =  'callout:Quest_Base_EndPoint/qdx-partner-testing-proxy-api/appointment/order';
                httpRequest.setEndpoint(endpoint);
                httpRequest.setMethod('POST');
                httpRequest.setHeader('Content-Type','application/json');
                httpRequest.setBody(jsonPayload);
                System.debug('Request::'+httpRequest);
                System.debug('Request 1 ::'+jsonPayload);

                response.labOrderId = request.labOrderId;
                response.requestPayload = jsonPayload;
                
                try 
                {
                httpResponse = http.send(httpRequest); 
                statusCode = httpResponse.getStatusCode(); 
                System.debug('Response ::'+httpResponse);
                System.debug('Response Status::'+httpResponse.getStatus());
                System.debug('Response Body::'+httpResponse.getBody());
                response.responsePayload = httpResponse.getBody();

                
                if(statusCode==201 || statusCode==200)
                {               
                    response.responseCode=String.valueOf(statusCode);     
                    response.responseMessage='Success';
                    response.status='Success';
                }
                else 
                {      
                        Map<String, Object> jsonResponseMap = (Map<String, Object>)JSON.deserializeUntyped(httpResponse.getBody());
                                        System.debug('jsonResponseMap ::'+jsonResponseMap);

                        String errorMessage='';          
                        if (jsonResponseMap.containsKey('error')) {
                            Map<String, Object> errorMap = (Map<String, Object>) jsonResponseMap.get('error');
                            Map<String, Object> faultMap = (Map<String, Object>) errorMap.get('fault');
                            List<Object> messageList = (List<Object>) faultMap.get('message');
                            errorMessage = String.join(messageList, ' ');
                        }
                        response.responseCode=String.valueOf(statusCode);
                        response.responseMessage=errorMessage;
                        response.status='Error';
                }

                  
            }
            catch(Exception e)
            {
            
            System.debug('response ::'+httpResponse);

            if(httpResponse != null)
            {
                response.responseCode='504';
                response.responseMessage=httpResponse.getStatus() + ' Message: ' + httpResponse.getBody();
                response.responsePayload = httpResponse.getBody();
            }
            else {
                response.responseMessage=e.getMessage();
                response.responsePayload = e.getMessage();
                response.responseCode='504';
            }
            
            response.status='Error';
            System.debug('Failed to create Transaction' + e.getMessage());
            
        }
          responses.add(response);
        }
        return responses;

    }
        
}