force-app/main/default/objects/Lab_Order__c/Lab_Order__c.object-meta.xml
<CustomObject>
    <label>Lab Order</label>
    <nameField>
        <label>Lab Order ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lab Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lab_Order__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Lab Orders</relationshipLabel>
    <relationshipName>Lab_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Client_ID__c.field-meta.xml
<CustomField>
    <fullName>Client_ID__c</fullName>
    <label>Client ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Client_Name__c.field-meta.xml
<CustomField>
    <fullName>Client_Name__c</fullName>
    <label>Partner Client Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Partner_Client_Map__c.field-meta.xml
<CustomField>
    <fullName>Partner_Client_Map__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner Client Map</label>
    <referenceTo>PartnerClientMap__c</referenceTo>
    <relationshipLabel>Lab Orders</relationshipLabel>
    <relationshipName>Lab_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/PerformingSite__c.field-meta.xml
<CustomField>
    <fullName>PerformingSite__c</fullName>
    <label>PerformingSite</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Person_Record__c.field-meta.xml
<CustomField>
    <fullName>Person_Record__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Person Record</label>
    <referenceTo>Person_Record__c</referenceTo>
    <relationshipLabel>Lab Orders</relationshipLabel>
    <relationshipName>Lab_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>PA Acknowledged</fullName>
            </value>
            <value>
                <fullName>PA Approved</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Partial Results Ready</fullName>
            </value>
            <value>
                <fullName>Results Ready</fullName>
            </value>
            <value>
                <fullName>PA Rejected</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>PWN Acknowledged</fullName>
                <isActive>false</isActive>
                <label>PWN Acknowledged</label>
            </value>
            <value>
                <fullName>PWN Approved</fullName>
                <isActive>false</isActive>
                <label>PWN Approved</label>
            </value>
            <value>
                <fullName>PWN Rejected</fullName>
                <isActive>false</isActive>
                <label>PWN Rejected</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lab_Order_Panel__c/Lab_Order_Panel__c.object-meta.xml
<CustomObject>
    <label>Lab Order Panel</label>
    <nameField>
        <displayFormat>PNID- {000000000}</displayFormat>
        <label>Lab Panel ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lab Order Panels</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Lab_Order_Panel__c/fields/Lab_Order__c.field-meta.xml
<CustomField>
    <fullName>Lab_Order__c</fullName>
    <label>Lab Order</label>
    <referenceTo>Lab_Order__c</referenceTo>
    <relationshipName>Lab_Order_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Lab_Order_Panel__c/fields/Panel__c.field-meta.xml
<CustomField>
    <fullName>Panel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Panel</label>
    <referenceTo>Panel__c</referenceTo>
    <relationshipName>Lab_Order_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lab_Order_Panel__c/fields/Panel_Code__c.field-meta.xml
<CustomField>
    <fullName>Panel_Code__c</fullName>
    <formula>Panel__r.Panel_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Panel Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lab_Order_Panel__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Results Ready</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>TNP</fullName>
            </value>
            <value>
                <fullName>PA Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Partial Results Ready</fullName>
            </value>
            <value>
                <fullName>PWN Rejected</fullName>
                <isActive>false</isActive>
                <label>PWN Rejected</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lab_Panel_Test__c/Lab_Panel_Test__c.object-meta.xml
<CustomObject>
    <label>Lab Panel Test</label>
    <nameField>
        <displayFormat>TID - {00000000}</displayFormat>
        <label>Lab Panel Test ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lab Panel Tests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Lab_Panel_Test__c/fields/Lab_Order__c.field-meta.xml
<CustomField>
    <fullName>Lab_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lab Order</label>
    <referenceTo>Lab_Order__c</referenceTo>
    <relationshipLabel>Lab Panel Tests</relationshipLabel>
    <relationshipName>Lab_Panel_Tests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lab_Panel_Test__c/fields/Lab_Order_Panel__c.field-meta.xml
<CustomField>
    <fullName>Lab_Order_Panel__c</fullName>
    <label>Lab Order Panel</label>
    <referenceTo>Lab_Order_Panel__c</referenceTo>
    <relationshipName>Lab_Panel_Analytes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Lab_Panel_Test__c/fields/Panel_Test__c.field-meta.xml
<CustomField>
    <fullName>Panel_Test__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Panel Test ID</label>
    <referenceTo>Panel_Test__c</referenceTo>
    <relationshipLabel>Lab Panel Tests</relationshipLabel>
    <relationshipName>Lab_Panel_Analytes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lab_Panel_Test__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Test Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>TNP</fullName>
            </value>
            <value>
                <fullName>Results Ready</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>PA Rejected</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Partial Results Ready</fullName>
            </value>
            <value>
                <fullName>PWN Rejected</fullName>
                <isActive>false</isActive>
                <label>PWN Rejected</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lab_Panel_Test__c/fields/Test_Code__c.field-meta.xml
<CustomField>
    <fullName>Test_Code__c</fullName>
    <formula>Panel_Test__r.Test__r.Test_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Test Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lab_Panel_Test__c/fields/Test_Name__c.field-meta.xml
<CustomField>
    <fullName>Test_Name__c</fullName>
    <formula>Panel_Test__r.Test__r.Test_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Test Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Client_Id__c.field-meta.xml
<CustomField>
    <fullName>Client_Id__c</fullName>
    <label>Client_Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Panel__c/Panel__c.object-meta.xml
<CustomObject>
    <label>Panel</label>
    <nameField>
        <displayFormat>PR-{00000000}</displayFormat>
        <label>Panel Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Panels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Panel__c/fields/Panel_Code__c.field-meta.xml
<CustomField>
    <fullName>Panel_Code__c</fullName>
    <label>Panel Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Panel__c/fields/Panel_Name__c.field-meta.xml
<CustomField>
    <fullName>Panel_Name__c</fullName>
    <label>Panel Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Panel_Test__c/Panel_Test__c.object-meta.xml
<CustomObject>
    <label>Panel Test</label>
    <nameField>
        <displayFormat>PTR - {000000000}</displayFormat>
        <label>Panel Test ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Panel Tests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Panel_Test__c/fields/Panel__c.field-meta.xml
<CustomField>
    <fullName>Panel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Panel</label>
    <referenceTo>Panel__c</referenceTo>
    <relationshipName>Panel_Analytes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Panel_Test__c/fields/Test__c.field-meta.xml
<CustomField>
    <fullName>Test__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Test</label>
    <referenceTo>Test__c</referenceTo>
    <relationshipLabel>Panel Tests</relationshipLabel>
    <relationshipName>Panel_Analytes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PartnerClientMap__c/PartnerClientMap__c.object-meta.xml
<CustomObject>
    <label>Partner Client Map</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PartnerClientMaps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PartnerClientMap__c/fields/Partner_Name__c.field-meta.xml
<CustomField>
    <fullName>Partner_Name__c</fullName>
    <label>Partner Name</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/PartnerClientMap__c/fields/Sales_Channel__c.field-meta.xml
<CustomField>
    <fullName>Sales_Channel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Channel</label>
    <referenceTo>SalesChannel</referenceTo>
    <relationshipLabel>PartnerClientMaps</relationshipLabel>
    <relationshipName>PartnerClientMaps</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Both</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Male</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Min_age__c.field-meta.xml
<CustomField>
    <fullName>Min_age__c</fullName>
    <label>Min age</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/performingSite__c.field-meta.xml
<CustomField>
    <fullName>performingSite__c</fullName>
    <label>performingSite</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/pwnEligible__c.field-meta.xml
<CustomField>
    <fullName>pwnEligible__c</fullName>
    <defaultValue>false</defaultValue>
    <label>pwnEligible</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/resultingRequired__c.field-meta.xml
<CustomField>
    <fullName>resultingRequired__c</fullName>
    <defaultValue>false</defaultValue>
    <label>resultingRequired</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/PartnerLabOrderResource_Test.cls
@isTest
public class PartnerLabOrderResource_Test {
    
    @testSetup
    static void prepareTestData(){
        
     Panel__c p = new Panel__c();
     p.Panel_Code__c = '7788';
     p.Panel_Name__c = 'test panel';
     insert p;
     
     Test__c t = new Test__c();
     t.Test_Code__c = '7788';
     t.Test_Name__c = 'demo test';
     insert t;

     Account accnt = new Account(Name='Test test');
        insert accnt;
        
        Contact con = new Contact();
        con.AccountId = accnt.id;
        con.LastName = 'test';
        insert con;

         // Insert mock Person and Lab_Order__c records
        Person_Record__c person = new Person_Record__c(
            First_Name__c = 'John',
            Last_Name__c = 'Doe',
            Email__c = 'john.doe@example.com',
            Address_Line_1__c = '123 Main St',
                     City__c = 'Anytown',
            Country__c = 'USA',
            State__c = 'CA',
            Postal_Code__c = '12345',
            Phone__c = '1234567890',
            Gender__c = 'Male',
            Date_of_Birth__c = Date.newInstance(1990, 1, 1),
            Contact__c = con.id,
            Unique_Identifier__c= 'fir@gmail.com:1985-09-09:lNe'
            
        );
        
        insert person;
     
     SalesChannel sc = new SalesChannel();
     sc.SalesChannelName = 'test';
     insert sc;
     SalesChannel sch =   [select id, SalesChannelName from SalesChannel where SalesChannelName = 'test' Limit 1];
     
     PartnerClientMap__c pmc = new PartnerClientMap__c();
     pmc.Sales_Channel__c = sch.Id;
     pmc.Partner_Name__c = 'google' ;
     pmc.Client_ID__c = 'google';
     pmc.Name = 'google';
     insert pmc;
     
     PartnerClientMap__c PCMt = [select id, Partner_Name__c, Client_ID__c from PartnerClientMap__c where Partner_Name__c = 'google' Limit 1];
     
     
     Lab_order__c lb = new Lab_Order__c();
     lb.Partner_Client_Map__c = PCMt.id;
     lb.Client_Name__c = 'lb';
     lb.Name = 'lb';
     lb.Status__c = 'Registered';
     lb.Person_Record__c = person.Id;
            lb.Account__c=accnt.Id;
     insert lb;
     
     Lab_order__c lb1 = new Lab_Order__c();
     lb1.Partner_Client_Map__c = PCMt.id;
     lb1.Client_Name__c = 'lb1';
     lb1.Name = 'lb1';
     lb1.Status__c = 'Registered';
      lb1.Person_Record__c = person.Id;
            lb1.Account__c=accnt.Id;
     insert lb1;
     
     Panel_Test__c pt = new Panel_Test__c();
     pt.Panel__c = p.id;
     pt.Test__c = t.Id;
     insert pt;
     
     Lab_Order_Panel__c LOP = new Lab_Order_Panel__c();
     LOP.Lab_Order__c = lb.id;
     LOP.Panel__c = p.id;
     insert LOP;
     
     Lab_Order_Panel__c LOP1 = new Lab_Order_Panel__c();
     LOP1.Lab_Order__c = lb1.id;
     LOP1.Panel__c = p.id;
     insert LOP1;
     
     Lab_Panel_Test__c lbt = new Lab_Panel_Test__c();
     lbt.Lab_Order_Panel__c = LOP.id;
     lbt.Status__c = 'Registered';
     lbt.Panel_Test__c = pt.id;
     lbt.Lab_Order__c= lb.id;
     insert lbt;
     
     
     Lab_Panel_Test__c lbt1 = new Lab_Panel_Test__c();
     lbt1.Lab_Order_Panel__c = LOP1.id;
     lbt1.Status__c = 'In Progress';
     lbt1.Panel_Test__c = pt.id;
     
     insert lbt1;
        
               
       
        
    }
    
    @isTest
    static void testSaveOrder(){
         string jsonBody ='{'+
            '"externalOrderId" : "AxK1Cs190",'+
            '"clientName" : "google",'+
            '"locationId" : "questLocation",'+
            '"paymentTransactionId": "not a required field",'+
            '"sh_app_secret": "11Zaes",'+
            '"appointmentCode": "11Zaes",'+
            '"customer": {'+
            '"firstName" : "fName",'+
             '"middleName" : "mName",'+
            '"lastName" : "lNe",'+
            '"dateOfBirth" : "1985-09-09",'+
            '"gender" : "Male",'+
            '"email" : "fir@gmail.com",'+
            '"phone": "4567890422",'+
            '"externalCustomerId": "11Zaes"'+
            '},'+
            '"address": {'+
            '"addressLine1" : "address1",'+
             '"addressLine2" : "address1",'+
            '"zip" : "15801",'+
            '"city" : "San Francisco",'+
            '"state" : "PA",'+
            '"country" : "US"'+
            '},'+
            '"orderSummaries": {'+
            '"orderItems" : [{'+
            '"testCode" : "7788",'+
            '"quantity" : 1,'+
            '"finalPrice" : "10.00"'+
            '		}]'+
            '	}'+
            '}';
        
        Test.startTest();
        system.debug(blob.valueOf(jsonBody));
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI  ='/services/apexrest/order/*';
        req.requestBody = blob.valueOf(jsonBody);
        req.httpMethod = 'Post';
        RestContext.request = req;
        RestContext.response= res;
        PartnerLabOrderResource.createOrder();
        //System.assertEquals(res.statusCode, 200);
        Test.stopTest();
    }
    
    
    @isTest
    static void testSaveOrder_Failure(){
        string jsonBody ='{'+
            '"externalOrderId" : "AxK1Cs190",'+
            '"clientName" : "goole",'+
            '"locationId" : "questLocation",'+
            '"paymentTransactionId": "not a required field",'+
            '"customer": {'+
            '"firstName" : "fName",'+
            '"lastName" : "lName",'+
            '"dateOfBirth" : "1988-10-18",'+
            '"gender" : "Male",'+
            '"email" : "sgh@yfredtpmail.com",'+
            '"phone": "4567890422",'+
            '"externalCustomerId": "11Zaes"'+
            '},'+
            '"address": {'+
            '"addressLine1" : "address1",'+
            '"zip" : "15801",'+
            '"city" : "San Francisco",'+
            '"state" : "PA",'+
            '"country" : "US"'+
            '},'+
            '"orderSummaries": {'+
            '"orderItems" : [{'+
            '"testCode" : "12767",'+
            '"quantity" : 1,'+
            '"finalPrice" : "10.00 "'+
            '		}]'+
            '	}'+
            '}';
        
        
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI  ='/services/apexrest/order/*';
        req.requestBody = blob.valueOf(jsonBody);
        req.httpMethod = 'Patch';
        RestContext.request = req;
        RestContext.response= res;
        Test.startTest();
        PartnerLabOrderResource.createOrder();
        System.assertEquals(res.statusCode, 400);
        Test.stopTest();
    }
    
    // @isTest
    // static void testSaveOrder_Update(){
    //     //Account acc =   [select id, PersonEmail from Account where PersonEmail = 'first@gmail.com' limit 1];
    //     // Contact con =   [select id, AccountId  from Contact where Email =: acc.PersonEmail];
        
    //     Person_Record__c ps = new Person_Record__c();
    //     ps.First_Name__c 		= 'FirstName';
    //     ps.Last_Name__c 		= 'lName';
    //     ps.Phone__c 			= '4569990422';
    //     ps.Date_of_Birth__c 	=  Date.parse('09/09/1985');
    //     ps.Gender__c 			= 'Male';
    //     ps.Email__c 			= 'first@gmail.com';
    //     ps.Address_Line_1__c 	= 'address';
    //     ps.City__c 				= 'kingston';
    //     ps.State__c 			= 'Newyork';
    //     ps.Country__c 			= 'US';
    //     ps.Postal_Code__c 		= '12041';
    //     ps.Unique_Identifier__c = 'first@gmail.com:'+'09/09/1985:' +'lName';
    //     // ps.Contact__c = con.id;
    //     insert ps;
        
    //     string jsonBody ='{'+
    //         '"externalOrderId" : "AxK1Cs190",'+
    //         '"clientName" : "google",'+
    //         '"locationId" : "questLocation",'+
    //         '"paymentTransactionId": "not a required field",'+
    //         '"sh_app_secret": "11Zaes",'+
    //         '"customer": {'+
    //         '"firstName" : "fName",'+
    //         '"lastName" : "lName",'+
    //         '"dateOfBirth" : "09/09/1985",'+
    //         '"gender" : "Male",'+
    //         '"email" : "first@gmail.com",'+
    //         '"phone": "4567890422",'+
    //         '"externalCustomerId": "11Zaes"'+
    //         '},'+
    //         '"address": {'+
    //         '"addressLine1" : "address1",'+
    //         '"zip" : "15801",'+
    //         '"city" : "San Francisco",'+
    //         '"state" : "PA",'+
    //         '"country" : "US"'+
    //         '},'+
    //         '"orderSummaries": {'+
    //         '"orderItems" : [{'+
    //         '"testCode" : "12767",'+
    //         '"quantity" : 1,'+
    //         '"finalPrice" : "10.00 "'+
    //         '		}]'+
    //         '	}'+
    //         '}';
        
    //     Test.startTest();
    //     RestRequest req = new RestRequest();
    //     RestResponse res = new RestResponse();
    //     req.requestURI  ='/services/apexrest/order/*';
    //     req.requestBody = blob.valueOf(jsonBody);
    //     req.httpMethod = 'Patch';
    //     RestContext.request = req;
    //     RestContext.response= res;
    //     PartnerLabOrderResource.createOrder();
    //     System.assertEquals(res.statusCode, 200);
    //     Test.stopTest();
    // }
    
    @isTest
    static void testSaveOrderCancel(){
        System.Test.setMock(HttpCalloutMock.class, new SendOrderDetailsToPHMock());
     PartnerClientMap__c partnerClientMap =    [select id, name, Partner_Name__c from PartnerClientMap__c where Partner_Name__c = 'google' Limit 1];
        Product2 productt = new Product2();
        productt.pwnEligible__c =true;
        productt.IsActive = true;
        productt.StockKeepingUnit = '1706';
        productt.performingSite__c = 'PHP';
        productt.Description = 'Vitamin D';
        productt.resultingRequired__c = true;
        productt.Min_age__c = '18';
     	productt.Name= 'Vitamin D Test';
        productt.Excluded_State_codes__c = 'AK;AZ;HI';
        productt.Franchise_Category__c = 'IDI';
        insert  productt;
        
        
        
        Product_Partner_Map__c pp = new Product_Partner_Map__c();
        pp.Cancellation_Fee__c = 10.00;
        pp.Product_Price__c = 5000.00;
        pp.Product__c = productt.id;
        pp.Partner_ID__c = partnerClientMap.id;
        insert pp;
        
         Product_Partner_Map__c pp1 = new Product_Partner_Map__c();
        pp1.Cancellation_Fee__c = 10.00;
        pp1.Product_Price__c = 5000.00;
        pp1.Product__c = productt.id;
        pp1.Partner_ID__c = partnerClientMap.id;
        insert pp1;
 		List<Product_Partner_Map__c> lstPP = [select id,Cancellation_Fee__c,Product_Price__c,Product__c,Partner_ID__c, Name from Product_Partner_Map__c where Partner_ID__c =:partnerClientMap.id AND  Product__c =:productt.id];
        string jsonBody ='{'+'"cancelReason" : "Cancel - Payment Capture Failure"'+'}';
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        Lab_order__c lb =   [select id, Name,Captured_Amount__c, Cancellation_Service_Fee__c,Refund_Amount__c, Status__c from Lab_order__c limit 1];
        lb.Status__c = 'Cancelled';
        lb.Refund_Amount__c= 50.00;
        update lb;
        req.requestURI  ='/services/apexrest/order/'+lb.Name;
        system.debug(req.requestURI);
        req.requestBody = blob.valueOf(jsonBody);
        req.httpMethod = 'Patch';
        RestContext.request = req;
        RestContext.response= res;
        Test.startTest();
        PartnerLabOrderResource.cancelOrder();
        //System.assertEquals(res.statusCode, 200);
        Test.stopTest();
    }    
    
    @isTest
    static void testSaveOrderCance2(){
         
       
        
        Lab_Panel_Test__c singleLPT = [select id,Status__c  from Lab_Panel_Test__c   Limit 1];
        singleLPT.Status__c = 'In Progress';
        update singleLPT;
        string jsonBody ='{'+'"cancelReason" : "Cancel - Payment Capture Failure"'+'}';
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI  ='/services/apexrest/order/*';
        system.debug(req.requestURI);
        req.requestBody = blob.valueOf(jsonBody);
        req.httpMethod = 'Patch';
        RestContext.request = req;
        RestContext.response= res;
        Test.startTest();
        PartnerLabOrderResource.cancelOrder();
        //System.assertEquals(res.statusCode, 500);
        Test.stopTest();
    }

	public class SendOrderDetailsToPHMock implements HttpCalloutMock{
        public HttpResponse respond(HttpRequest req1){
            HttpResponse res1 = new HttpResponse();
            res1.setHeader('Content-Type', 'application/x-www-form-urlencoded');
            if(req1.getEndPoint().contains('refunds')){
                res1.setBody('{"amount_received":10000.00}');
                res1.setStatusCode(400);
            }
            else{
                res1.setbody('{"amount_received":10000.00}');
                res1.setStatusCode(200);
            }
            return res1;
        }
    }
    
    public class SendOrderDetailsToPHMock1 implements HttpCalloutMock{
        public HttpResponse respond(HttpRequest req1){
            HttpResponse res1 = new HttpResponse();
            res1.setHeader('Content-Type', 'application/x-www-form-urlencoded');
            if(req1.getEndPoint().contains('refunds')){
                res1.setBody('{"amount_received":10000.00}');
                res1.setStatusCode(200);
            }
            else{
                res1.setbody('{"amount_received":10000.00}');
                res1.setStatusCode(200);
            }
            return res1;
        }
    }    
}