force-app/main/default/objects/Lab_Order__c/Lab_Order__c.object-meta.xml
<CustomObject>
    <label>Lab Order</label>
    <nameField>
        <label>Lab Order ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lab Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lab_Order__c/fields/Cancellation_Service_Fee__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Service_Fee__c</fullName>
    <label>Cancellation Service Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Captured_Amount__c.field-meta.xml
<CustomField>
    <fullName>Captured_Amount__c</fullName>
    <label>Captured Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Is_Partner__c.field-meta.xml
<CustomField>
    <fullName>Is_Partner__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Partner</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Is_Refund_Error__c.field-meta.xml
<CustomField>
    <fullName>Is_Refund_Error__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Refund Error</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Partner_Client_Map__c.field-meta.xml
<CustomField>
    <fullName>Partner_Client_Map__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner Client Map</label>
    <referenceTo>PartnerClientMap__c</referenceTo>
    <relationshipLabel>Lab Orders</relationshipLabel>
    <relationshipName>Lab_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Payment_Transaction_Id__c.field-meta.xml
<CustomField>
    <fullName>Payment_Transaction_Id__c</fullName>
    <externalId>true</externalId>
    <label>Payment Transaction Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Refund_Amount__c.field-meta.xml
<CustomField>
    <fullName>Refund_Amount__c</fullName>
    <label>Refund Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Refund_Attempts__c.field-meta.xml
<CustomField>
    <fullName>Refund_Attempts__c</fullName>
    <label>Refund Attempts</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PartnerClientMap__c/PartnerClientMap__c.object-meta.xml
<CustomObject>
    <label>Partner Client Map</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PartnerClientMaps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PartnerClientMap__c/fields/Payment_Key__c.field-meta.xml
<CustomField>
    <fullName>Payment_Key__c</fullName>
    <label>Payment Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PartnerLabOrderRefundRetryBatchSchedule.cls
global with sharing class  PartnerLabOrderRefundRetryBatchSchedule implements Schedulable{
    global void execute(SchedulableContext sc) {   
        PartnerLabOrderRefundRetryBatch btch= new PartnerLabOrderRefundRetryBatch();
        btch.query = 'SELECT Id, Payment_Transaction_Id__c,Captured_Amount__c,Cancellation_Service_Fee__c,Refund_Amount__c,Refund_Attempts__c,Partner_Client_Map__r.Payment_Key__c FROM Lab_Order__c WHERE Refund_Attempts__c < 4 and Is_Refund_Error__c = true and Is_Partner__c = true';
        Database.executeBatch(btch,1);
      }
}