force-app/main/default/objects/Lab_Order__c/Lab_Order__c.object-meta.xml
<CustomObject>
    <label>Lab Order</label>
    <nameField>
        <label>Lab Order ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lab Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lab_Order__c/fields/Client_ID__c.field-meta.xml
<CustomField>
    <fullName>Client_ID__c</fullName>
    <label>Client ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Full_Refund__c.field-meta.xml
<CustomField>
    <fullName>Full_Refund__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Full Refund</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Is_Kit__c.field-meta.xml
<CustomField>
    <fullName>Is_Kit__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Kit</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Is_Partner__c.field-meta.xml
<CustomField>
    <fullName>Is_Partner__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Partner</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Is_PWN_Approved__c.field-meta.xml
<CustomField>
    <fullName>Is_PWN_Approved__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is PA Approved</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Kit_Detail__c.field-meta.xml
<CustomField>
    <fullName>Kit_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Kit Detail</label>
    <referenceTo>Kit_Details__c</referenceTo>
    <relationshipLabel>Lab Orders</relationshipLabel>
    <relationshipName>Lab_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Person_Record__c.field-meta.xml
<CustomField>
    <fullName>Person_Record__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Person Record</label>
    <referenceTo>Person_Record__c</referenceTo>
    <relationshipLabel>Lab Orders</relationshipLabel>
    <relationshipName>Lab_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Physician_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Physician_First_Name__c</fullName>
    <label>Physician First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Physician_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Physician_Last_Name__c</fullName>
    <label>Physician Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Physician_Npi__c.field-meta.xml
<CustomField>
    <fullName>Physician_Npi__c</fullName>
    <label>Physician Npi</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Physician_Upin__c.field-meta.xml
<CustomField>
    <fullName>Physician_Upin__c</fullName>
    <label>Physician Upin</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/PWN_ID__c.field-meta.xml
<CustomField>
    <fullName>PWN_ID__c</fullName>
    <externalId>true</externalId>
    <label>PA External ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/PWN_Status_Date__c.field-meta.xml
<CustomField>
    <fullName>PWN_Status_Date__c</fullName>
    <label>PA Status Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/PWN_Success__c.field-meta.xml
<CustomField>
    <fullName>PWN_Success__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PA Success</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Refund_Amount__c.field-meta.xml
<CustomField>
    <fullName>Refund_Amount__c</fullName>
    <label>Refund Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>PA Acknowledged</fullName>
            </value>
            <value>
                <fullName>PA Approved</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Partial Results Ready</fullName>
            </value>
            <value>
                <fullName>Results Ready</fullName>
            </value>
            <value>
                <fullName>PA Rejected</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>PWN Acknowledged</fullName>
                <isActive>false</isActive>
                <label>PWN Acknowledged</label>
            </value>
            <value>
                <fullName>PWN Approved</fullName>
                <isActive>false</isActive>
                <label>PWN Approved</label>
            </value>
            <value>
                <fullName>PWN Rejected</fullName>
                <isActive>false</isActive>
                <label>PWN Rejected</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Client_Id__c.field-meta.xml
<CustomField>
    <fullName>Client_Id__c</fullName>
    <label>Client_Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PWNPollingJobTest.cls
@IsTest
public class PWNPollingJobTest {
    
    // Mock class for HTTP callout response
    private class MockHttpResponseGeneratorSuccess implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            // Create a mock HTTP response
            HttpResponse res = new HttpResponse();
            res.setStatusCode(200);
            res.setHeader('Content-Type', 'application/json');

            // Sample response for approved and rejected orders
            String responseBody = '{' +
                '"orders": [' +
                    '{"id": "PWN123", "status": "approved"}' +
                   
                ']' +
            '}';
            res.setBody(responseBody);

            return res;
        }
    }

    private class MockHttpResponseGeneratorReject implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            // Create a mock HTTP response
            HttpResponse res = new HttpResponse();
            res.setStatusCode(200);
            res.setHeader('Content-Type', 'application/json');

            // Sample response for approved and rejected orders
            String responseBody = '{' +
                '"orders": [' +
                     '{"id": "PWN456", "status": "rejected"}' +
                ']' +
            '}';
            res.setBody(responseBody);

            return res;
        }
    }

    @IsTest
    static void testPWNPollingJobSuccess() {

        Person_Record__c person = new Person_Record__c(
            First_Name__c = 'John',
            Last_Name__c = 'Doe',
            Email__c = 'john.doe@example.com',
            Address_Line_1__c = '123 Main St',
            Unique_Identifier__c ='Uniqu1',
            City__c = 'Anytown',
            Country__c = 'USA',
            State__c = 'CA',
            Postal_Code__c = '12345',
            Phone__c = '1234567890',
            Gender__c = 'Male',
            Date_of_Birth__c = Date.newInstance(1990, 1, 1)
        );
        insert person;


        // Set up test data
        Lab_Order__c labOrder1 = new Lab_Order__c(
           Is_Partner__c=true,
            Client_Id__c = '12345',
            Person_Record__c = person.Id,
            Name='TETS81892-12781',
            PWN_ID__C='PWN123',
            Status__c='PA Acknowledged',
            PWN_Success__c=true,
            Physician_First_Name__c='asasd',
            Physician_Last_Name__c='bcvm',
            Physician_Npi__c='122121',
            Physician_Upin__c='12121'
        );
        

        insert new List<Lab_Order__c> { labOrder1 };

        
        // Set the mock callout response
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGeneratorSuccess());

        Test.startTest();
        PWNPollingJob btch= new PWNPollingJob();
        List<String> statusList = new List<String>{'Cancelled','Expired','PA Rejected'};
        btch.statusList = statusList;
        btch.Id=labOrder1.Id;
        btch.query = 'SELECT Id,Is_Kit__c,Kit_Detail__c, PWN_ID__c FROM Lab_Order__c WHERE  Status__c NOT IN : statusList  and Is_PWN_Approved__c = false and PWN_Success__c = true and Id=:id ';
        Database.executeBatch(btch,1);

        Test.stopTest();

        // Reload the lab orders and kits to verify updates
        Lab_Order__c updatedOrder1 = [SELECT Id, Status__c,Is_PWN_Approved__c, PWN_Status_Date__c FROM Lab_Order__c WHERE Id = :labOrder1.Id];
       

        // // Validate updates for approved order
        System.assertEquals(true, updatedOrder1.Is_PWN_Approved__c, 'Order 1 should be approved');
        System.assertEquals(System.today(), updatedOrder1.PWN_Status_Date__c, 'Order 1 PWN_Status_Date__c should be today');
      

        // Validate updates for rejected order
        // System.assertEquals('PWN Rejected', updatedOrder2.Status__c, 'Order 2 status should be "PWN Rejected"');
        // System.assertEquals(true, updatedOrder2.Full_Refund__c, 'Order 2 Full_Refund__c should be true');
      
    }

    @IsTest
    static void testPWNPollingJobReject() {

        Account ac = new Account();
        ac.Name = 'Test account';
        insert ac;
        
        Contact con = new Contact();
        con.lastName = 'test con';
        con.Email = 'test@gmail.com';
        con.AccountId = ac.Id;
        insert con;

        Person_Record__c person = new Person_Record__c(
            First_Name__c = 'John',
            Last_Name__c = 'Doe',
            Email__c = 'john.doe@example.com',
            Address_Line_1__c = '123 Main St',
            Unique_Identifier__c ='Uniqu1',
            City__c = 'Anytown',
            Country__c = 'USA',
            Contact__c = con.Id,
            State__c = 'CA',
            Postal_Code__c = '12345',
            Phone__c = '1234567890',
            Gender__c = 'Male',
            Date_of_Birth__c = Date.newInstance(1990, 1, 1)
        );
        insert person;


        // Set up test data
        Lab_Order__c labOrder1 = new Lab_Order__c(
           Is_Partner__c=true,
            Client_Id__c = '12345',
            Person_Record__c = person.Id,
            Name='TETS81892-12781',
            PWN_ID__C='PWN456',
            Status__c='PA Acknowledged',
            PWN_Success__c=true,
            Physician_First_Name__c='asasd',
            Physician_Last_Name__c='bcvm',
            Physician_Npi__c='122121',
            Physician_Upin__c='12121',
            Refund_Amount__c=30.00
        );
        

        insert new List<Lab_Order__c> { labOrder1 };

        
        // Set the mock callout response
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGeneratorReject());

        Test.startTest();
        PWNPollingJob btch= new PWNPollingJob();
        List<String> statusList = new List<String>{'Cancelled','Expired','PA Rejected'};
        btch.statusList = statusList;
        btch.Id=labOrder1.Id;
        btch.query = 'SELECT Id,Is_Kit__c,Kit_Detail__c, PWN_ID__c FROM Lab_Order__c WHERE  Status__c NOT IN : statusList  and Is_PWN_Approved__c = false and PWN_Success__c = true and Id=:id ';
        Database.executeBatch(btch,1);

        Test.stopTest();

        // Reload the lab orders and kits to verify updates
        Lab_Order__c updatedOrder1 = [SELECT Id, Status__c, Full_Refund__c FROM Lab_Order__c WHERE Id = :labOrder1.Id];
       

        // // Validate updates for approved order
        // System.assertEquals(true, updatedOrder1.Is_PWN_Approved__c, 'Order 1 should be approved');
        // System.assertEquals(System.today(), updatedOrder1.PWN_Status_Date__c, 'Order 1 PWN_Status_Date__c should be today');
      

        // Validate updates for rejected order
        System.assertEquals('PA Rejected', updatedOrder1.Status__c, 'Order 2 status should be "PA Rejected"');
        System.assertEquals(true, updatedOrder1.Full_Refund__c, 'Order 2 Full_Refund__c should be true');


        
      
    }

    @IsTest
    static void testGSSPWNPollingJobSuccess() {

        Person_Record__c person = new Person_Record__c(
            First_Name__c = 'John',
            Last_Name__c = 'Doe',
            Email__c = 'john.doe@example.com',
            Address_Line_1__c = '123 Main St',
            Unique_Identifier__c ='Uniqu1',
            City__c = 'Anytown',
            Country__c = 'USA',
            State__c = 'CA',
            Postal_Code__c = '12345',
            Phone__c = '1234567890',
            Gender__c = 'Male',
            Date_of_Birth__c = Date.newInstance(1990, 1, 1)
        );
        insert person;


        // Set up test data
        Lab_Order__c labOrder1 = new Lab_Order__c(
           Is_Partner__c=true,
            Client_Id__c = '12345',
            Person_Record__c = person.Id,
            Name='TETS81892-12781',
            PWN_ID__C='PWN123',
            Status__c='PA Acknowledged',
            PWN_Success__c=true,
            Physician_First_Name__c='asasd',
            Physician_Last_Name__c='bcvm',
            Physician_Npi__c='122121',
            Physician_Upin__c='12121'
        );
        

        insert new List<Lab_Order__c> { labOrder1 };

        
        // Set the mock callout response
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGeneratorSuccess());

        Test.startTest();
        GSSPWNPollingJob btch= new GSSPWNPollingJob();
        List<String> statusList = new List<String>{'Cancelled','Expired','PA Rejected'};
        btch.statusList = statusList;
        btch.Id=labOrder1.Id;
        btch.query = 'SELECT Id,Is_Kit__c,Kit_Detail__c, PWN_ID__c FROM Lab_Order__c WHERE  Status__c NOT IN : statusList  and Is_PWN_Approved__c = false and PWN_Success__c = true and Id=:id ';
        Database.executeBatch(btch,1);

        Test.stopTest();

        // Reload the lab orders and kits to verify updates
        Lab_Order__c updatedOrder1 = [SELECT Id, Status__c,Is_PWN_Approved__c, PWN_Status_Date__c FROM Lab_Order__c WHERE Id = :labOrder1.Id];
       

        // // Validate updates for approved order
        System.assertEquals(true, updatedOrder1.Is_PWN_Approved__c, 'Order 1 should be approved');
        System.assertEquals(System.today(), updatedOrder1.PWN_Status_Date__c, 'Order 1 PWN_Status_Date__c should be today');
      

        // Validate updates for rejected order
        // System.assertEquals('PWN Rejected', updatedOrder2.Status__c, 'Order 2 status should be "PWN Rejected"');
        // System.assertEquals(true, updatedOrder2.Full_Refund__c, 'Order 2 Full_Refund__c should be true');
      
    }

    @IsTest
    static void testGSSPWNPollingJobReject() {
        Account ac = new Account();
        ac.Name = 'Test account';
        insert ac;
        
        Contact con = new Contact();
        con.lastName = 'test con';
        con.Email = 'test@gmail.com';
        con.AccountId = ac.Id;
        insert con;
     
        Person_Record__c person = new Person_Record__c(
            First_Name__c = 'John',
            Last_Name__c = 'Doe',
            Email__c = 'john.doe@example.com',
            Address_Line_1__c = '123 Main St',
            Unique_Identifier__c ='Uniqu1',
            City__c = 'Anytown',
            Country__c = 'USA',
            State__c = 'CA',
            Contact__c = con.Id,
            Postal_Code__c = '12345',
            Phone__c = '1234567890',
            Gender__c = 'Male',
            Date_of_Birth__c = Date.newInstance(1990, 1, 1)
        );
        insert person;


        // Set up test data
        Lab_Order__c labOrder1 = new Lab_Order__c(
           Is_Partner__c=true,
            Client_Id__c = '12345',
            Person_Record__c = person.Id,
            Name='TETS81892-12781',
            PWN_ID__C='PWN456',
            Status__c='PA Acknowledged',
            PWN_Success__c=true,
            Physician_First_Name__c='asasd',
            Physician_Last_Name__c='bcvm',
            Physician_Npi__c='122121',
            Physician_Upin__c='12121',
            Refund_Amount__c=30.00
        );
        

        insert new List<Lab_Order__c> { labOrder1 };

        
        // Set the mock callout response
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGeneratorReject());

        Test.startTest();
        GSSPWNPollingJob btch= new GSSPWNPollingJob();
        List<String> statusList = new List<String>{'Cancelled','Expired','PA Rejected'};
        btch.statusList = statusList;
        btch.Id=labOrder1.Id;
        btch.query = 'SELECT Id,Is_Kit__c,Kit_Detail__c, PWN_ID__c FROM Lab_Order__c WHERE  Status__c NOT IN : statusList  and Is_PWN_Approved__c = false and PWN_Success__c = true and Id=:id ';
        Database.executeBatch(btch,1);

        Test.stopTest();

        // Reload the lab orders and kits to verify updates
        Lab_Order__c updatedOrder1 = [SELECT Id, Status__c, Full_Refund__c FROM Lab_Order__c WHERE Id = :labOrder1.Id];
       

        // // Validate updates for approved order
        // System.assertEquals(true, updatedOrder1.Is_PWN_Approved__c, 'Order 1 should be approved');
        // System.assertEquals(System.today(), updatedOrder1.PWN_Status_Date__c, 'Order 1 PWN_Status_Date__c should be today');
      

        // Validate updates for rejected order
        System.assertEquals('PA Rejected', updatedOrder1.Status__c, 'Order 2 status should be "PA Rejected"');
        System.assertEquals(true, updatedOrder1.Full_Refund__c, 'Order 2 Full_Refund__c should be true');


        
      
    }

    @IsTest 
    static void validateStatusCheckScheduleTest () {
        PWNPollingSchedule testsche = new PWNPollingSchedule();

        GSSPWNPollingSchedule testsche1 = new GSSPWNPollingSchedule();
        String sch = '0 0 23 * * ?';
        
        Person_Record__c person = new Person_Record__c(
            First_Name__c = 'John',
            Last_Name__c = 'Doe',
            Email__c = 'john.doe@example.com',
            Address_Line_1__c = '123 Main St',
            Unique_Identifier__c ='Uniqu1',
            City__c = 'Anytown',
            Country__c = 'USA',
            State__c = 'CA',
            Postal_Code__c = '12345',
            Phone__c = '1234567890',
            Gender__c = 'Male',
            Date_of_Birth__c = Date.newInstance(1990, 1, 1)
        );
        insert person;


        // Set up test data
        Lab_Order__c labOrder1 = new Lab_Order__c(
           Is_Partner__c=true,
            Client_Id__c = '12345',
            Person_Record__c = person.Id,
            Name='TETS81892-12781',
            PWN_ID__C='PWN123',
            Status__c='PA Acknowledged',
            PWN_Success__c=true,
            Physician_First_Name__c='asasd',
            Physician_Last_Name__c='bcvm',
            Physician_Npi__c='122121',
            Physician_Upin__c='12121'
        );
        

        insert new List<Lab_Order__c> { labOrder1 };
        
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGeneratorSuccess());


        Test.startTest();
        system.schedule('Test status Check', sch, testsche );
        system.schedule('Test status Check 1', sch, testsche1 );
        Test.stopTest();
  }      
}