force-app/main/default/objects/Lab_Order__c/Lab_Order__c.object-meta.xml
<CustomObject>
    <label>Lab Order</label>
    <nameField>
        <label>Lab Order ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lab Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lab_Order__c/fields/Accession_ID__c.field-meta.xml
<CustomField>
    <fullName>Accession_ID__c</fullName>
    <label>Accession ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Client_ID__c.field-meta.xml
<CustomField>
    <fullName>Client_ID__c</fullName>
    <label>Client ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/PerformingSite__c.field-meta.xml
<CustomField>
    <fullName>PerformingSite__c</fullName>
    <label>PerformingSite</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Client_Id__c.field-meta.xml
<CustomField>
    <fullName>Client_Id__c</fullName>
    <label>Client_Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LaborderResultPageCtrlTest.cls
@IsTest
public class LaborderResultPageCtrlTest {
    @isTest static void getPDFTest(){
        PageReference pageRef = Page.LaborderResultPage;
        Test.setCurrentPage(pageRef);
        Lab_Order__c labOrder = new Lab_Order__c(
            Name = 'Test Lab Order',
            Client_Id__c='91801320',
            Accession_ID__c='Asaskhk',Date_Reported__c=Date.newInstance(2024, 8, 15),PerformingSite__c='PHP'
        );
        insert labOrder;
        Lab_Order__c labOrder1 = [select Id from Lab_Order__c WHERE Id =:labOrder.Id ];
        ApexPages.currentPage().getparameters().put('loid', labOrder1.Id);                    
        LaborderResultPageCtrl myController = new LaborderResultPageCtrl();
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        Test.startTest();
        myController.getPDF();
        Test.stopTest();
        // System.assertNotEquals(null, myController.pdfdata);
        // System.assertEquals('<html></html>', myController.pdfdata);
    }
    // Inner class to mock HTTP response
    public class MockHttpResponseGenerator implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            HttpResponse res = new HttpResponse();
            res.setStatusCode(200);
            if(req.getEndPoint().contains('token')){
            	res.setBody('{"access_token": "121212121"}');
            }else{
                res.setBody(EncodingUtil.base64Encode(Blob.valueOf('<html></html>')));
            }
            return res;
        }
    }
}