force-app/main/default/objects/Lab_Order__c/Lab_Order__c.object-meta.xml
<CustomObject>
    <label>Lab Order</label>
    <nameField>
        <label>Lab Order ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lab Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lab_Order__c/fields/Client_ID__c.field-meta.xml
<CustomField>
    <fullName>Client_ID__c</fullName>
    <label>Client ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Is_Partner__c.field-meta.xml
<CustomField>
    <fullName>Is_Partner__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Partner</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/PerformingSite__c.field-meta.xml
<CustomField>
    <fullName>PerformingSite__c</fullName>
    <label>PerformingSite</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Person_Record__c.field-meta.xml
<CustomField>
    <fullName>Person_Record__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Person Record</label>
    <referenceTo>Person_Record__c</referenceTo>
    <relationshipLabel>Lab Orders</relationshipLabel>
    <relationshipName>Lab_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Physician_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Physician_First_Name__c</fullName>
    <label>Physician First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Physician_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Physician_Last_Name__c</fullName>
    <label>Physician Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Physician_Npi__c.field-meta.xml
<CustomField>
    <fullName>Physician_Npi__c</fullName>
    <label>Physician Npi</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Physician_Upin__c.field-meta.xml
<CustomField>
    <fullName>Physician_Upin__c</fullName>
    <label>Physician Upin</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/PWN_ID__c.field-meta.xml
<CustomField>
    <fullName>PWN_ID__c</fullName>
    <externalId>true</externalId>
    <label>PA External ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Client_Id__c.field-meta.xml
<CustomField>
    <fullName>Client_Id__c</fullName>
    <label>Client_Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Panel__c/Panel__c.object-meta.xml
<CustomObject>
    <label>Panel</label>
    <nameField>
        <displayFormat>PR-{00000000}</displayFormat>
        <label>Panel Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Panels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Panel__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Panels</relationshipLabel>
    <relationshipName>Panels</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Panel_Test__c/Panel_Test__c.object-meta.xml
<CustomObject>
    <label>Panel Test</label>
    <nameField>
        <displayFormat>PTR - {000000000}</displayFormat>
        <label>Panel Test ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Panel Tests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Panel_Test__c/fields/Panel__c.field-meta.xml
<CustomField>
    <fullName>Panel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Panel</label>
    <referenceTo>Panel__c</referenceTo>
    <relationshipName>Panel_Analytes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Panel_Test__c/fields/Test__c.field-meta.xml
<CustomField>
    <fullName>Test__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Test</label>
    <referenceTo>Test__c</referenceTo>
    <relationshipLabel>Panel Tests</relationshipLabel>
    <relationshipName>Panel_Analytes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Both</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Male</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/performingSite__c.field-meta.xml
<CustomField>
    <fullName>performingSite__c</fullName>
    <label>performingSite</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/testType__c.field-meta.xml
<CustomField>
    <fullName>testType__c</fullName>
    <label>testType</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SlackNotifierTest.cls
@IsTest
public class SlackNotifierTest {
    @IsTest
    static void testCreateHUBOrder_Success() {
       
        

       Product2 product = new Product2();
            product.Name = 'Test';
            product.Description = 'Test';
            product.ProductCode = 'test';
            product.StockKeepingUnit = 'Test'+ String.valueOf(1);
            product.DisplayUrl = '';
            product.ExternalId = 'sku123';
            product.IsActive = true;
            product.testType__c='PSC';
            product.performingSite__c='PHP';
            insert product;

        Panel__c panel =  new Panel__c(Product__c=product.Id);
        insert panel;

        Test__c test =  new Test__c(Test_Code__c='test',Test_Name__c='test',Description__c='test');
        insert test;

        Panel_Test__c panelTest= new Panel_Test__c(Panel__c=panel.Id,Test__c=test.Id);
        insert panelTest;

        // Insert mock Person and Lab_Order__c records
        Person_Record__c person = new Person_Record__c(
            First_Name__c = 'John',
            Last_Name__c = 'Doe',
            Email__c = 'john.doe@example.com',
            Address_Line_1__c = '123 Main St',
            Unique_Identifier__c ='Uniqu1',
            City__c = 'Anytown',
            Country__c = 'USA',
            State__c = 'CA',
            Postal_Code__c = '12345',
            Phone__c = '1234567890',
            Gender__c = 'Male',
            Date_of_Birth__c = Date.newInstance(1990, 1, 1)
        );
        insert person;

        Lab_Order__c labOrder = new Lab_Order__c(
           Is_Partner__c=true,
            Client_Id__c = '12345',
            Person_Record__c = person.Id,
            Name='TETS81892-12782323',
            PWN_ID__C='12671281',
            Physician_First_Name__c='asasd',
            Physician_Last_Name__c='bcvm',
            Physician_Npi__c='122121',
            Physician_Upin__c='12121'
        );
        insert labOrder;
        List<SlackNotifier.RequestInput> inputs = new List<SlackNotifier.RequestInput>();
                System.Test.setMock(HttpCalloutMock.class, new MockSlackHttpResponse(201, '{"order"}'));
		 SlackNotifier.RequestInput input = new SlackNotifier.RequestInput();
        input.slackMessage = 'messageTest';
        input.labOrderId = labOrder.Name;
        inputs.add(input);
         System.Test.startTest();
         SlackNotifier.sendSlackMessage(inputs);
        System.Test.stopTest();
        
    }

    private class MockSlackHttpResponse implements HttpCalloutMock {
        private Integer statusCode;
        private String responseBody;

        public MockSlackHttpResponse(Integer statusCode, String responseBody) {
            this.statusCode = statusCode;
            this.responseBody = responseBody;
        }

        public HTTPResponse respond(HTTPRequest req) {
            HttpResponse res = new HttpResponse();
            res.setStatusCode(statusCode);
            res.setBody(responseBody);
            return res;
        }
    }
}