force-app/main/default/objects/Lab_Order__c/Lab_Order__c.object-meta.xml
<CustomObject>
    <label>Lab Order</label>
    <nameField>
        <label>Lab Order ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lab Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lab_Order__c/fields/Days_to_expire__c.field-meta.xml
<CustomField>
    <fullName>Days_to_expire__c</fullName>
    <formula>IF(AND(FO_Record_Type__c = &apos;InPerson&apos;,
ISPICKVAL(Status__c, &apos;PA Approved&apos;)
),
PWN_Status_Date__c +65 - TODAY(),9999)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Days to expire</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <formula>PWN_Status_Date__c +65</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/FO_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>FO_Record_Type__c</fullName>
    <formula>IF( Is_Kit__c , Kit_Detail__r.Type__c , &apos;InPerson&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>FO Record Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Is_Partner__c.field-meta.xml
<CustomField>
    <fullName>Is_Partner__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Partner</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Order_Summary__c.field-meta.xml
<CustomField>
    <fullName>Order_Summary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Summary</label>
    <referenceTo>OrderSummary</referenceTo>
    <relationshipLabel>Lab Orders</relationshipLabel>
    <relationshipName>Lab_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Partner_Client_Map__c.field-meta.xml
<CustomField>
    <fullName>Partner_Client_Map__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner Client Map</label>
    <referenceTo>PartnerClientMap__c</referenceTo>
    <relationshipLabel>Lab Orders</relationshipLabel>
    <relationshipName>Lab_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Person_Record__c.field-meta.xml
<CustomField>
    <fullName>Person_Record__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Person Record</label>
    <referenceTo>Person_Record__c</referenceTo>
    <relationshipLabel>Lab Orders</relationshipLabel>
    <relationshipName>Lab_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>PA Acknowledged</fullName>
            </value>
            <value>
                <fullName>PA Approved</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Partial Results Ready</fullName>
            </value>
            <value>
                <fullName>Results Ready</fullName>
            </value>
            <value>
                <fullName>PA Rejected</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>PWN Acknowledged</fullName>
                <isActive>false</isActive>
                <label>PWN Acknowledged</label>
            </value>
            <value>
                <fullName>PWN Approved</fullName>
                <isActive>false</isActive>
                <label>PWN Approved</label>
            </value>
            <value>
                <fullName>PWN Rejected</fullName>
                <isActive>false</isActive>
                <label>PWN Rejected</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PartnerClientMap__c/PartnerClientMap__c.object-meta.xml
<CustomObject>
    <label>Partner Client Map</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PartnerClientMaps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PartnerClientMap__c/fields/Suppress_Reminder_Email__c.field-meta.xml
<CustomField>
    <fullName>Suppress_Reminder_Email__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Suppress Reminder Email</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/LabOrderExpiryEmailSchedule.cls
global with sharing class LabOrderExpiryEmailSchedule implements Schedulable{
    global void execute(SchedulableContext sc) {   
        LabOrderExpiryEmailOutbound btch= new LabOrderExpiryEmailOutbound();
        btch.status = 'PA Approved';
        btch.type = 'InPerson';
        btch.query = 'SELECT Id, CreatedDate,Name,Order_Summary__c,Order_Summary__r.OrderNumber,Order_Summary__r.GrandTotalAmount,Person_Record__r.Id,Person_Record__r.Email__c,Expiration_Date__c,Days_to_expire__c,Order_Summary__r.Id,  Is_Partner__c,Partner_Client_Map__r.Suppress_Reminder_Email__c FROM Lab_Order__c WHERE Status__c =: status  and Days_to_expire__c in (30,10,7,3) and FO_Record_Type__c =: type';
        Database.executeBatch(btch,1);
      }
}