force-app/main/default/objects/Lab_Order__c/Lab_Order__c.object-meta.xml
<CustomObject>
    <label>Lab Order</label>
    <nameField>
        <label>Lab Order ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lab Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lab_Order__c/fields/Cancellation_Service_Fee__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Service_Fee__c</fullName>
    <label>Cancellation Service Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Captured_Amount__c.field-meta.xml
<CustomField>
    <fullName>Captured_Amount__c</fullName>
    <label>Captured Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Is_Refund_Error__c.field-meta.xml
<CustomField>
    <fullName>Is_Refund_Error__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Refund Error</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Partner_Client_Map__c.field-meta.xml
<CustomField>
    <fullName>Partner_Client_Map__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner Client Map</label>
    <referenceTo>PartnerClientMap__c</referenceTo>
    <relationshipLabel>Lab Orders</relationshipLabel>
    <relationshipName>Lab_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Payment_Transaction_Id__c.field-meta.xml
<CustomField>
    <fullName>Payment_Transaction_Id__c</fullName>
    <externalId>true</externalId>
    <label>Payment Transaction Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Refund_Amount__c.field-meta.xml
<CustomField>
    <fullName>Refund_Amount__c</fullName>
    <label>Refund Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Refund_Attempts__c.field-meta.xml
<CustomField>
    <fullName>Refund_Attempts__c</fullName>
    <label>Refund Attempts</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>PA Acknowledged</fullName>
            </value>
            <value>
                <fullName>PA Approved</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Partial Results Ready</fullName>
            </value>
            <value>
                <fullName>Results Ready</fullName>
            </value>
            <value>
                <fullName>PA Rejected</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>PWN Acknowledged</fullName>
                <isActive>false</isActive>
                <label>PWN Acknowledged</label>
            </value>
            <value>
                <fullName>PWN Approved</fullName>
                <isActive>false</isActive>
                <label>PWN Approved</label>
            </value>
            <value>
                <fullName>PWN Rejected</fullName>
                <isActive>false</isActive>
                <label>PWN Rejected</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PartnerClientMap__c/PartnerClientMap__c.object-meta.xml
<CustomObject>
    <label>Partner Client Map</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PartnerClientMaps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PartnerClientMap__c/fields/Payment_Key__c.field-meta.xml
<CustomField>
    <fullName>Payment_Key__c</fullName>
    <label>Payment Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PartnerLabOrderRefundRetryBatch.cls
global with sharing class PartnerLabOrderRefundRetryBatch implements Database.Batchable <SObject>, Database.AllowsCallouts {
 public  String Query;
 public String labOrderId;

 global Database.QueryLocator start(Database.BatchableContext bc){
 return Database.getQueryLocator(Query);
 }
 global void execute(Database.BatchableContext bc, List<Lab_Order__c> lstRecords){

    
    Decimal amountToRefund=0.0;
    

            for(Lab_Order__c order:lstRecords )
            {
                System.debug('order : ' + order);
                Lab_Order__c labOrderToUpdate =  new Lab_Order__c();
                labOrderToUpdate.Id=order.Id;

                amountToRefund = order.Refund_Amount__c;

                Decimal amountReceived = 0.0;
                Double cancellationFee = order.Cancellation_Service_Fee__c;
                Event_Log__c eventLog = new Event_Log__c();
                eventLog.Lab_Order__c =order.Id;                                
                eventLog.Event_Type__c ='Payment Refund'; 


                    Http http = new Http();
                    HttpRequest request = new HttpRequest();
                    HttpResponse response = new HttpResponse();
                    if(order.Captured_Amount__c == null)
                    {
                        request.setEndpoint(label.SFOM_Stripe_URL+order.Payment_Transaction_Id__c );
                        request.setMethod('GET');
                        request.setHeader('Content-Type','application/x-www-form-urlencoded');
                        request.setHeader('Authorization','Bearer '+order.Partner_Client_Map__r.Payment_Key__c);

                        response = http.send(request);
                        if (response.getStatusCode() == 200) {
                            Map<String, Object> responseMap = (Map<String, Object>) JSON.deserializeUntyped(response.getBody());
                            amountReceived = Double.valueOf(responseMap.get('amount_received'));
                            amountReceived = amountReceived != null ? amountReceived/100 : 0.0;
                            System.debug('response: ' + response + ' : amountReceived:  ' + amountReceived );
                            amountToRefund = amountReceived - cancellationFee;
                        } else {
                            System.debug('Error from Stripe for GET call: ' + response.getBody());
                            labOrderToUpdate.Is_Refund_Error__c=true;
                            labOrderToUpdate.Refund_Attempts__c= order.Refund_Attempts__c+1;
                            eventLog.Status__c='Error';
                            eventLog.Response_Payload__c='Stripe API call failed with status: ' + response.getBody()  + ' : '+ response.getStatus();                    
                        }
                    }
                
                if(amountToRefund > 0.0)
                {
                    
                                  
                    try
                    {
                        
                        request.setEndpoint(label.SFOM_Stripe_Refund_URL);
                        request.setMethod('POST');
                        request.setHeader('Content-Type','application/x-www-form-urlencoded');
                        request.setHeader('Authorization','Bearer '+order.Partner_Client_Map__r.Payment_Key__c );
                        String body = 'amount=' + (amountToRefund * 100).intValue() + '&payment_intent=' + order.Payment_Transaction_Id__c;
                        request.setBody(body);
                        eventLog.Payload__c=body;
                        
                        System.debug('request : ' + request + ' Body : ' + body);

                        // Send the HTTP request
                        http = new Http();
                        response = http.send(request);

                        System.debug('response : ' + response);

                        // Handle the response
                        if (response.getStatusCode() == 200) {
                            eventLog.Status__c='Success';
                            eventLog.Response_Payload__c=response.getBody();
                        } else {
                            Map<String, Object> parsedJson = (Map<String, Object>) JSON.deserializeUntyped(response.getBody());
                            Map<String, Object> errorMap = (Map<String, Object>) parsedJson.get('error');
                            // output.statusCode=response.getStatusCode();
                            String errorMessage=(String) errorMap.get('code') + ' : ' + (String) errorMap.get('message');
                            eventLog.Status__c='Error';
                            eventLog.Response_Payload__c=errorMessage + ' :  '+response.getBody();
                            labOrderToUpdate.Is_Refund_Error__c=true;
                            labOrderToUpdate.Refund_Attempts__c= order.Refund_Attempts__c+1;
                        }
                    
                    }
                    catch(Exception e)
                    {
                        System.debug('Error : ' + e.getMessage());
                        labOrderToUpdate.Is_Refund_Error__c=true;
                        labOrderToUpdate.Refund_Attempts__c= order.Refund_Attempts__c+1;
                        eventLog.Status__c='Error';
                        eventLog.Response_Payload__c='Failed to refund payment: ' + e.getMessage() ;
                    }

                    labOrderToUpdate.Refund_Amount__c=amountToRefund;
                    labOrderToUpdate.Captured_Amount__c= amountReceived;
                    labOrderToUpdate.Cancellation_Service_Fee__c= cancellationFee;

                    System.debug('labOrderToUpdate : ' + labOrderToUpdate);

                    insert eventLog;
                    
                }
                System.debug('labOrderToUpdate : ' + labOrderToUpdate);

                update labOrderToUpdate;
                
            }
 }
 global void finish(Database.BatchableContext bc) {
 }
}