force-app/main/default/objects/Lab_Order__c/Lab_Order__c.object-meta.xml
<CustomObject>
    <label>Lab Order</label>
    <nameField>
        <label>Lab Order ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lab Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lab_Order__c/fields/Client_ID__c.field-meta.xml
<CustomField>
    <fullName>Client_ID__c</fullName>
    <label>Client ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Customer_ID_Override__c.field-meta.xml
<CustomField>
    <fullName>Customer_ID_Override__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Customer_ID_Override</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Date_of_Collection__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Collection__c</fullName>
    <label>Date of Collection</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Is_Kit__c.field-meta.xml
<CustomField>
    <fullName>Is_Kit__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Kit</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Is_Partner__c.field-meta.xml
<CustomField>
    <fullName>Is_Partner__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Partner</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Kit_Detail__c.field-meta.xml
<CustomField>
    <fullName>Kit_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Kit Detail</label>
    <referenceTo>Kit_Details__c</referenceTo>
    <relationshipLabel>Lab Orders</relationshipLabel>
    <relationshipName>Lab_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/LabRefId__c.field-meta.xml
<CustomField>
    <fullName>LabRefId__c</fullName>
    <formula>BLANKVALUE(LabRefId_Override__c, &apos;SF000000000000&apos;+CASESAFEID(Id))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>LabRefId</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/LabRefId_Override__c.field-meta.xml
<CustomField>
    <fullName>LabRefId_Override__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>LabRefId_Override</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Minor_Customer_Id__c.field-meta.xml
<CustomField>
    <fullName>Minor_Customer_Id__c</fullName>
    <description>Customer ID to HUB when the order is a minor order</description>
    <displayFormat>A0YMINPID{000000000}</displayFormat>
    <label>Minor Customer Id</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Minor_Date_of_Birth__c.field-meta.xml
<CustomField>
    <fullName>Minor_Date_of_Birth__c</fullName>
    <label>Minor Date of Birth</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Minor_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Minor_First_Name__c</fullName>
    <label>Minor First Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Minor_Gender__c.field-meta.xml
<CustomField>
    <fullName>Minor_Gender__c</fullName>
    <label>Minor Gender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Minor_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Minor_Last_Name__c</fullName>
    <label>Minor Last Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Order_Number__c.field-meta.xml
<CustomField>
    <fullName>Order_Number__c</fullName>
    <externalId>true</externalId>
    <label>Order Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Order_Summary__c.field-meta.xml
<CustomField>
    <fullName>Order_Summary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Summary</label>
    <referenceTo>OrderSummary</referenceTo>
    <relationshipLabel>Lab Orders</relationshipLabel>
    <relationshipName>Lab_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Person_Record__c.field-meta.xml
<CustomField>
    <fullName>Person_Record__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Person Record</label>
    <referenceTo>Person_Record__c</referenceTo>
    <relationshipLabel>Lab Orders</relationshipLabel>
    <relationshipName>Lab_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Physician_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Physician_First_Name__c</fullName>
    <label>Physician First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Physician_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Physician_Last_Name__c</fullName>
    <label>Physician Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Physician_Npi__c.field-meta.xml
<CustomField>
    <fullName>Physician_Npi__c</fullName>
    <label>Physician Npi</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Physician_Upin__c.field-meta.xml
<CustomField>
    <fullName>Physician_Upin__c</fullName>
    <label>Physician Upin</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/PWN_ID__c.field-meta.xml
<CustomField>
    <fullName>PWN_ID__c</fullName>
    <externalId>true</externalId>
    <label>PA External ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>PA Acknowledged</fullName>
            </value>
            <value>
                <fullName>PA Approved</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Partial Results Ready</fullName>
            </value>
            <value>
                <fullName>Results Ready</fullName>
            </value>
            <value>
                <fullName>PA Rejected</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>PWN Acknowledged</fullName>
                <isActive>false</isActive>
                <label>PWN Acknowledged</label>
            </value>
            <value>
                <fullName>PWN Approved</fullName>
                <isActive>false</isActive>
                <label>PWN Approved</label>
            </value>
            <value>
                <fullName>PWN Rejected</fullName>
                <isActive>false</isActive>
                <label>PWN Rejected</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lab_Order_Panel__c/Lab_Order_Panel__c.object-meta.xml
<CustomObject>
    <label>Lab Order Panel</label>
    <nameField>
        <displayFormat>PNID- {000000000}</displayFormat>
        <label>Lab Panel ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lab Order Panels</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Lab_Order_Panel__c/fields/AOE__c.field-meta.xml
<CustomField>
    <fullName>AOE__c</fullName>
    <label>AOE</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Lab_Order_Panel__c/fields/Lab_Order__c.field-meta.xml
<CustomField>
    <fullName>Lab_Order__c</fullName>
    <label>Lab Order</label>
    <referenceTo>Lab_Order__c</referenceTo>
    <relationshipName>Lab_Order_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Lab_Order_Panel__c/fields/Performing_Site__c.field-meta.xml
<CustomField>
    <fullName>Performing_Site__c</fullName>
    <formula>IF(Lab_Order__r.Is_Kit__c , Lab_Order__r.Kit_Detail__r.PerformingSite__c ,IF( Lab_Order__r.Is_Partner__c, IF(ISBLANK(Panel__r.Product__r.performingSite__c),&apos;PHP&apos;,Panel__r.Product__r.performingSite__c) ,Fulfillment_Order_Product__r.PerformingSite__c) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Performing Site</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lab_Order_Panel__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Results Ready</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>TNP</fullName>
            </value>
            <value>
                <fullName>PA Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Partial Results Ready</fullName>
            </value>
            <value>
                <fullName>PWN Rejected</fullName>
                <isActive>false</isActive>
                <label>PWN Rejected</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lab_Order_Panel__c/fields/Test_Type__c.field-meta.xml
<CustomField>
    <fullName>Test_Type__c</fullName>
    <formula>IF( Lab_Order__r.Is_Kit__c , Lab_Order__r.Kit_Detail__r.Type__c ,IF( Lab_Order__r.Is_Partner__c , IF(ISBLANK(Panel__r.Product__r.testType__c) ,&apos;PSC&apos;,Panel__r.Product__r.testType__c),Fulfillment_Order_Product__r.Test_Type__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Test Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lab_Panel_Test__c/Lab_Panel_Test__c.object-meta.xml
<CustomObject>
    <label>Lab Panel Test</label>
    <nameField>
        <displayFormat>TID - {00000000}</displayFormat>
        <label>Lab Panel Test ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lab Panel Tests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Lab_Panel_Test__c/fields/Lab_Order__c.field-meta.xml
<CustomField>
    <fullName>Lab_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lab Order</label>
    <referenceTo>Lab_Order__c</referenceTo>
    <relationshipLabel>Lab Panel Tests</relationshipLabel>
    <relationshipName>Lab_Panel_Tests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lab_Panel_Test__c/fields/Lab_Order_Panel__c.field-meta.xml
<CustomField>
    <fullName>Lab_Order_Panel__c</fullName>
    <label>Lab Order Panel</label>
    <referenceTo>Lab_Order_Panel__c</referenceTo>
    <relationshipName>Lab_Panel_Analytes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Lab_Panel_Test__c/fields/Test_Code__c.field-meta.xml
<CustomField>
    <fullName>Test_Code__c</fullName>
    <formula>Panel_Test__r.Test__r.Test_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Test Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lab_Panel_Test__c/fields/Test_Description__c.field-meta.xml
<CustomField>
    <fullName>Test_Description__c</fullName>
    <formula>Panel_Test__r.Test__r.Description__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Test Description</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lab_Panel_Test__c/fields/Test_Name__c.field-meta.xml
<CustomField>
    <fullName>Test_Name__c</fullName>
    <formula>Panel_Test__r.Test__r.Test_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Test Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Client_Id__c.field-meta.xml
<CustomField>
    <fullName>Client_Id__c</fullName>
    <label>Client_Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Minor_Order__c.field-meta.xml
<CustomField>
    <fullName>Minor_Order__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Minor Order</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OrderSummary/fields/Client_Id__c.field-meta.xml
<CustomField>
    <fullName>Client_Id__c</fullName>
    <defaultValue>TEXT(97554902)</defaultValue>
    <label>Client Id</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderSummary/fields/Minor_Order__c.field-meta.xml
<CustomField>
    <fullName>Minor_Order__c</fullName>
    <formula>OriginalOrder.Minor_Order__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Minor Order</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CancelLabHUBOrder.cls
public with sharing class CancelLabHUBOrder {
    public class CancelLabHUBOrderInput {
        @InvocableVariable(label='Ping Fed Token' description='Ping Fed Token')
        public String token;
        @InvocableVariable(label='Lab Order Id' description='Lab Order Id')
        public String labOrderId;
        }

    public class CancelLabHUBOrderOutput {
        @InvocableVariable(label='Response Message' description='Response Message from HUB Service')
        public String responseMessage;
        @InvocableVariable(label='Response Code' description='Response Code from HUB Service')
        public String responseCode;
        @InvocableVariable(label='Request Payload' description='Request Payload')
        public String requestPayload;
        @InvocableVariable(label='Response Payload' description='Response Payload')
        public String responsePayload;
        @InvocableVariable(label='Lab Order Id' description='LabOrderId')
        public String labOrderId;
        @InvocableVariable(label='Status' description='Status')
        public String status;
    }

    @InvocableMethod(label='Lab HUB Order' description='Creates Lab HUB Order and Updates Lab Order ')
    public static List<CancelLabHUBOrderOutput> createHubOrder(List<CancelLabHUBOrderInput> inputs) {

        List<CancelLabHUBOrderOutput> output = new List<CancelLabHUBOrderOutput>();

        for(CancelLabHUBOrderInput serviceInput : inputs)
        {
            CancelLabHUBOrderOutput serviceOutput = new CancelLabHUBOrderOutput();
            String labOrderId = serviceInput.labOrderId;
            String token = serviceInput.token;
            

            Integer statusCode;
            String responseMessage = '';
            Http http = new Http();
            HttpResponse response;
            HttpRequest request = new HttpRequest();
            
                       Lab_Order__c labOrder = [select Id,Is_Partner__c,Name,Is_Kit__c,Kit_Detail__r.Date_of_Collection__c,Kit_Detail__r.Activation_Code__c,Order_Summary__r.OrderNumber,Order_Summary__c,Client_Id__c,Person_Record__r.First_Name__c,
            Person_Record__r.Last_Name__c,Person_Record__r.Email__c,Person_Record__r.Address_Line_1__c,Person_Record__r.Address_Line_2__c,Person_Record__r.City__c,
            Person_Record__r.Country__c,Person_Record__r.State__c,Person_Record__r.Postal_Code__c,Person_Record__r.Phone__c,
            Person_Record__r.Gender__c,Person_record__r.Date_of_Birth__c,PWN_ID__c,Physician_First_Name__c,Physician_Last_Name__c,Physician_Upin__c,Physician_Npi__c,LabRefId__c,
            Kit_Detail__r.Record_Type__c,Kit_Detail__r.Verification_ID__c,Kit_Detail__r.Sample_Received_Date__c,Kit_Detail__r.Order_Number__c,
            Order_Summary__r.Minor_Order__c, Minor_Customer_Id__c,Minor_Date_of_Birth__c,Minor_Gender__c,Minor_Last_Name__c,Minor_First_Name__c, LabRefId_Override__c,Customer_ID_Override__c
                                from Lab_Order__c where Id =: labOrderId];
            
                                                                                             
            List<Lab_Panel_Test__c> tests = [select Id, Test_Name__c,Test_Description__c,Test_Code__c,
            Lab_Order_Panel__r.AOE__c,Lab_Order_Panel__r.Performing_Site__c,Lab_Order_Panel__r.Test_Type__c,Lab_Order_Panel__r.Quantity__c,Lab_Order_Panel__r.Status__c,
            Lab_Order_Panel__r.HRA_Req__c,Lab_Order_Panel__r.Questionnaire_Submitted__c from Lab_Panel_Test__c where Lab_Order_Panel__r.Lab_Order__c =: labOrderId];


            String testType = tests[0].Lab_Order_Panel__r.Test_Type__c;
            String performingSite = tests[0].Lab_Order_Panel__r.Performing_Site__c;
            String gender = '';
            String addressLine1 = labOrder.Person_Record__r.Address_Line_1__c;

            //a better practice is to use a map for such mappings.
            Map<String, String> GENDER_MAP = new Map<String, String>{
                'Male' => 'M',
                'Female' => 'F'
            };
            //verify if it's a minor order.
            Boolean isMinorOrder = Boolean.valueOf(labOrder.Order_Summary__r.Minor_Order__c) == true;
            //get the correct gender depending on minor or not.
            String rawGender = isMinorOrder ? labOrder.Minor_Gender__c : labOrder.Person_Record__r.Gender__c;
            //get the correct gender.
            gender = GENDER_MAP.containsKey(rawGender) ? GENDER_MAP.get(rawGender) : '';
            
            //DOB formatting depending on minor or not.
            Date dobDate = isMinorOrder ? labOrder.Minor_Date_of_Birth__c : labOrder.Person_record__r.Date_of_Birth__c;
            String formattedDOB = dobDate != null ? DateTime.newInstance(dobDate.year(), dobDate.month(), dobDate.day()).format('yyyy-MM-dd') : '';

            String formattedCollectionDate = '';
            if(labOrder.Is_Kit__c)
            {
                DateTime collectionDateTime = DateTime.newInstance(labOrder.Kit_Detail__r.Date_of_Collection__c.year(), labOrder.Kit_Detail__r.Date_of_Collection__c.month(), labOrder.Kit_Detail__r.Date_of_Collection__c.day());
                formattedCollectionDate = collectionDateTime.format('yyyy-MM-dd');
            }

            System.debug('Lab Orders : ' + labOrder);

            System.debug(' Tests : ' + tests);

            JSONGenerator gen = JSON.createGenerator(true);
            gen.writeStartObject();
                gen.writefieldName('customers');
                gen.writeStartArray();
                    gen.writeStartObject();
                        gen.writeStringField('customerId', labOrder.Customer_ID_Override__c != null ? labOrder.Customer_ID_Override__c : (Boolean.valueOf(labOrder.Order_Summary__r.Minor_Order__c) ? labOrder.Minor_Customer_Id__c : labOrder.Person_record__c));
                        gen.writeStringField('lastName',  Boolean.valueOf(labOrder.Order_Summary__r.Minor_Order__c) ? labOrder.Minor_Last_Name__c :labOrder.Person_Record__r.Last_Name__c );
                        gen.writeStringField('firstName', Boolean.valueOf(labOrder.Order_Summary__r.Minor_Order__c) ? labOrder.Minor_First_Name__c : labOrder.Person_Record__r.First_Name__c);
                        gen.writeStringField('middleName',  '');
                        gen.writeStringField('gender', gender); 
                        gen.writeStringField('preferredGender', '7'); 
                        gen.writeStringField('email', labOrder.Person_Record__r.Email__c);
                        gen.writefieldName('billingAddress');
                            gen.writeStartObject();
                                gen.writeStringField('addressLine1', addressLine1 != null ? addressLine1 : '');
                                gen.writeStringField('addressLine2', labOrder.Person_Record__r.Address_Line_2__c != null ? labOrder.Person_Record__r.Address_Line_2__c : '');
                                gen.writeStringField('zip', labOrder.Person_Record__r.Postal_Code__c);
                                gen.writeStringField('city', labOrder.Person_Record__r.City__c);
                                gen.writeStringField('state', labOrder.Person_Record__r.State__c);
                                gen.writeStringField('country', labOrder.Person_Record__r.Country__c);
                            gen.writeEndObject();
                        gen.writeStringField('mobilePhone', labOrder.Person_Record__r.Phone__c.replaceAll('[^0-9]', ''));
                        gen.writeStringField('birthDate', formattedDOB) ;
                        gen.writefieldName('orderSummaries');
                        gen.writeStartArray();
                            gen.writeStartObject();
                                gen.writeStringField('id', labOrder.LabRefId_Override__c != null ? labOrder.LabRefId_Override__c : labOrderId);
                                gen.writeStringField('clientId', labOrder.Client_Id__c);
                                if(!labOrder.Is_Partner__c)
                                {
                                    if(labOrder.Order_Summary__c != null )
                                    {
                                        gen.writeStringField('ecommOrderId', labOrder.Order_Summary__r.OrderNumber);
                                    }
                                    else if(labOrder.Order_Summary__c == null && labOrder.Is_Kit__c)
                                    {
                                        gen.writeStringField('ecommOrderId', labOrder.Kit_Detail__r.Order_Number__c);
                                    }
                                    
                                }
                                else{
                                    gen.writeStringField('ecommOrderId', labOrder.Name); 
                                }
                                gen.writefieldName('fullfillmentOrders');
                                gen.writeStartArray();
                                    gen.writeStartObject();
                                        if(labOrder.Is_Kit__c)
                                        {
                                            gen.writeStringField('id', labOrder.Kit_Detail__r.Activation_Code__c);
                                            gen.writeStringField('verificationId',labOrder.Kit_Detail__r.Verification_ID__c);
                                            gen.writeStringField('collectionDate',formattedCollectionDate);
                                            gen.writeStringField('testType', labOrder.Kit_Detail__r.Record_Type__c);

                                        }
                                        else{
                                            gen.writeStringField('id', labOrder.LabRefId_Override__c != null ? labOrder.LabRefId_Override__c : labOrderId);
                                            gen.writeStringField('testType', testType);
                                        }
                                        gen.writeStringField('pwnOrderId',labOrder.PWN_ID__c); 
                                        gen.writeStringField('performingSite', performingSite); 
                                        gen.writeStringField('status', 'cancelled');
                                        gen.writeStringField('lid',  labOrder.LabRefId_Override__c != null ? Label.LabRefOverride_Prefix + labOrder.LabRefId_Override__c : labOrder.LabRefId__c);                                
                                    gen.writefieldName('physician');
                                    gen.writeStartObject();
                                        gen.writeStringField('name', labOrder.Physician_First_Name__c + ' ' + labOrder.Physician_Last_Name__c);
                                        gen.writeStringField('firstName', labOrder.Physician_First_Name__c != null ? labOrder.Physician_First_Name__c : '');
                                        gen.writeStringField('lastName', labOrder.Physician_Last_Name__c != null ? labOrder.Physician_Last_Name__c : '');
                                        gen.writeStringField('upin', labOrder.Physician_Upin__c != null ? labOrder.Physician_Upin__c : '');
                                        gen.writeStringField('npi', labOrder.Physician_Npi__c != null ? labOrder.Physician_Npi__c : '');
                                    gen.writeEndObject();
                                    gen.writefieldName('fullfillmentOrderItems');
                                    gen.writeStartArray();
                                    for (Lab_Panel_Test__c test : tests) {
                                            gen.writeStartObject();                                           
                                                gen.writeStringField('id', test.Id);
                                                gen.writeStringField('testName', test.Test_Name__c);
                                                string TestCode =  test.Test_Code__c;
                                                integer lastHyphen= TestCode.lastIndexOf('-');
                                                if(lastHyphen>-1)
                                                {
                                                    String suffix=TestCode.substring(lastHyphen+1);

                                                    if(suffix.toLowerCase().startsWith('m')){
                                                        TestCode=TestCode.substring(0,lastHyphen);
                                                    }

                                                }
                                                gen.writeStringField('testCode',TestCode);
                                                gen.writeStringField('testDesc', test.Test_Description__c);
                                                gen.writeStringField('quantity', String.valueOf(test.Lab_Order_Panel__r.Quantity__c));
                                                gen.writeStringField('status', 'cancelled');
                                                gen.writeBooleanField('isHra', test.Lab_Order_Panel__r.HRA_Req__c);
                                                gen.writeBooleanField('questionnaireSubmitted', test.Lab_Order_Panel__r.Questionnaire_Submitted__c);
                                                if(labOrder.Is_Kit__c)
                                                {
                                                    gen.writeStringField('activationCode', labOrder.Kit_Detail__r.Activation_Code__c);
                                                    gen.writeBooleanField('kitActivated', true);
                                                    gen.writeStringField('verificationId',labOrder.Kit_Detail__r.Verification_ID__c);
                                                    gen.writeStringField('collectionDate',formattedCollectionDate);
                                                    gen.writeStringField('testType', labOrder.Kit_Detail__r.Record_Type__c);
                                                }
                                                else {
                                                    gen.writeBooleanField('kitActivated', false);
                                                    gen.writeStringField('testType', test.Lab_Order_Panel__r.Test_Type__c);
                                                }
                                                
                                                if(test.Lab_Order_Panel__r.AOE__c != null)
                                                {
                                                   
                                                   List<Object> aoeList = (List<Object>) JSON.deserializeUntyped(test.Lab_Order_Panel__r.AOE__c.unescapeHtml4());

                                                    List<Map<String, Object>> attestationJSON = new List<Map<String, Object>>();
                                                    for (Object obj : aoeList) {
                                                        if (obj instanceof Map<String, Object>) {
                                                            attestationJSON.add((Map<String, Object>)obj);
                                                        }
                                                    }
                                                   
                                                    // Map<String, Object> attestationJSON = (Map<String, Object>) JSON.deserializeUntyped(test.Lab_Order_Panel__r.AOE__c.unescapeHtml4());

                                                    // List<Map<String, Object>> attestationJSON = new List<Map<String, Object>>();
                                                    // for (Object obj : aoeList) {
                                                    //     if (obj instanceof Map<String, Object>) {
                                                    //         attestationJSON.add((Map<String, Object>)obj);
                                                    //     }
                                                    // }
                                                    

                                                    gen.writeFieldName('aoes');
                                                        gen.writeStartArray();
                                                        for (Map<String, Object> aoe : attestationJSON) {

                                                            if((Boolean)aoe.get('isAoe'))
                                                            {
                                                                gen.writeStartObject(); 
                                                             
                                                            for (String fieldName : aoe.keySet()) {
                                                                Object value = aoe.get(fieldName);
                                                                if(value != null)
                                                                {
                                                                    if (value instanceof String) {
                                                                        gen.writeStringField(fieldName, (String)value);
                                                                    } else if (value instanceof Decimal) {
                                                                        gen.writeStringField(fieldName, String.valueOf(value));
                                                                    }  else if (value instanceof Boolean && fieldName != 'isAoe') {
                                                                        gen.writeBooleanField(fieldName, (Boolean)value);
                                                                    }
                                                                    else if(fieldName == 'isAoe')
                                                                    {
                                                                        Boolean isAOE = (Boolean) value;
                                                                        gen.writeStringField('questionType',isAOE ? 'AOE':'CONSENT');
                                                                    }
                                                                }
                                                            }
                                                            gen.writeEndObject();
                                                            }
                                                            
                                                        }                                           
                                                        gen.writeEndArray();
                                                }
                                            gen.writeEndObject();
                                        }                                    
                                    gen.writeEndArray();
                                gen.writeEndObject();
                            gen.writeEndArray();
                        gen.writeEndObject();
                    gen.writeEndArray();
                gen.writeEndObject();
            gen.writeEndArray();
        gen.writeEndObject();

            System.debug(gen.getAsString());
            
            serviceOutput = callHubService(gen.getAsString(),token,serviceInput.labOrderId);

        output.add(serviceOutput);
            

        }

        return output;

    }

    private static CancelLabHUBOrderOutput callHubService(String requestJSON,String token,String labOrderId)
    {
        CancelLabHUBOrderOutput serviceOutput= new CancelLabHUBOrderOutput();
        Http http = new Http();
        HttpResponse response;
        HttpRequest request = new HttpRequest();
        Integer statusCode;
        try{
            
            String endpoint = Label.OMS_Mule_Proxy_Ednpoint;
            
            
            request.setEndpoint(endpoint+'qdx-quanum-hub-proxy-api/orders');
            request.setMethod('PATCH');
            request.setHeader('Content-Type','application/json');
            request.setHeader('Authorization','Bearer ' + token);
            request.setTimeout(60000);
            request.setBody(requestJSON);
            System.debug('Request::'+request);
                    
                
                serviceOutput.labOrderId = labOrderId;
                serviceOutput.requestPayload = requestJSON;

                response = http.send(request); 
                statusCode = response.getStatusCode(); 

                Map<String, Object> jsonResponseMap = (Map<String, Object>)JSON.deserializeUntyped(response.getBody());
                
               
                
                serviceOutput.responsePayload = response.getBody();

                if(statusCode==201 || statusCode==200){
                    serviceOutput.responseCode=String.valueOf(statusCode);
                    serviceOutput.responseMessage='Success';
                    serviceOutput.Status='Success';
                }
                else if(statusCode==504){
                    serviceOutput.responseCode=String.valueOf(statusCode);
                    serviceOutput.responseMessage='Timeout';
                    serviceOutput.Status='Timeout Error';
                }
                else {      
                    String errorMessage='';          
                    if (jsonResponseMap.containsKey('error')) {
                        Map<String, Object> errorMap = (Map<String, Object>) jsonResponseMap.get('error');
                        Map<String, Object> faultMap = (Map<String, Object>) errorMap.get('fault');
                        List<Object> messageList = (List<Object>) faultMap.get('message');
                        errorMessage = String.join(messageList, ' ');
                    }
                    serviceOutput.responseCode=String.valueOf(statusCode);
                    serviceOutput.responseMessage=errorMessage;
                    serviceOutput.Status='Error';
                }

                
          }
          catch(Exception e){
            
            if(response != null)
            {
                serviceOutput.responseCode=String.valueOf(statusCode);
                serviceOutput.responseMessage=response.getStatus() + ' Message: ' + response.getBody();
                serviceOutput.responsePayload = response.getBody();
            }
            else {
                serviceOutput.responseMessage=e.getMessage();
                serviceOutput.responsePayload = e.getMessage();
                serviceOutput.responseCode='504';
            }
            
            serviceOutput.Status='Error';
            System.debug('Failed to create Transaction' + e.getMessage());
          }
          return serviceOutput;
    } 
}