force-app/main/default/objects/Lab_Order__c/Lab_Order__c.object-meta.xml
<CustomObject>
    <label>Lab Order</label>
    <nameField>
        <label>Lab Order ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lab Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lab_Order__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Lab Orders</relationshipLabel>
    <relationshipName>Lab_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Client_ID__c.field-meta.xml
<CustomField>
    <fullName>Client_ID__c</fullName>
    <label>Client ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Client_Name__c.field-meta.xml
<CustomField>
    <fullName>Client_Name__c</fullName>
    <label>Partner Client Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Order_Status__c.field-meta.xml
<CustomField>
    <fullName>Order_Status__c</fullName>
    <formula>IF(
    ISPICKVAL(Status__c, &apos;Cancelled&apos;),
    &apos;Cancelled&apos;,
    IF(
        ISPICKVAL(Status__c, &apos;PA Rejected&apos;),
        &apos;PA Rejected&apos;,
        IF(
            Is_Expired__c,
            &apos;Expired&apos;,
            IF(
                AND(
                    Total_TNP_Panels__c = 0,
                    Total_Resulted_Panels__c = 0,
                    Total_In_Progress__c = 0,
                    Total_Partial_Resulted_Panels__c =0,
                    !PWN_Success__c
                ),
                &apos;Registered&apos;,
                IF(
                    AND(
                        Total_TNP_Panels__c = 0,
                        Total_Resulted_Panels__c = 0,
                        Total_In_Progress__c = 0,
                        Total_Partial_Resulted_Panels__c =0,
                        PWN_Success__c,
                        !Is_PWN_Approved__c
                    ),
                    &apos;PA Acknowledged&apos;,
                    IF(
                        AND(
                            Total_TNP_Panels__c = 0,
                            Total_Resulted_Panels__c = 0,
                            Total_In_Progress__c = 0,
                            Total_Partial_Resulted_Panels__c =0,
                            Is_PWN_Approved__c
                        ),
                        &apos;PA Approved&apos;,
                        IF(
                            Total_Panels__c = Total_Resulted_Panels__c,
                            &apos;Results Ready&apos;,
                            IF(
                                Total_Panels__c = Total_TNP_Panels__c,
                                &apos;Results Ready&apos;,
                                IF(
                                    AND(
                                        Total_In_Progress__c = 0,
                                        Total_Partial_Resulted_Panels__c =0,
                                        Total_TNP_Panels__c &gt; 0,
                                        Total_Panels__c &lt;&gt; Total_Resulted_Panels__c,
                                        Total_Resulted_Panels__c &gt; 0
                                    ),
                                    &apos;Results Ready&apos;,
                                    IF(
                                        AND(
                                            OR(
                                                Total_Resulted_Panels__c &gt; 0,
                                                Total_TNP_Panels__c &gt; 0,
                                                Total_Partial_Resulted_Panels__c &gt; 0
                                            ),
                                            Total_In_Progress__c &gt;= 0
                                        ),
                                        &apos;Partial Results Ready&apos;,
                                        &apos;In Progress&apos;
                                    )
                                )
                            )
                        )
                    )
                )
            )
        )
    )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Order Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Partner_Client_Map__c.field-meta.xml
<CustomField>
    <fullName>Partner_Client_Map__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner Client Map</label>
    <referenceTo>PartnerClientMap__c</referenceTo>
    <relationshipLabel>Lab Orders</relationshipLabel>
    <relationshipName>Lab_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Partner_Order_Total__c.field-meta.xml
<CustomField>
    <fullName>Partner_Order_Total__c</fullName>
    <label>Partner Order Total</label>
    <summarizedField>Lab_Order_Panel__c.Panel_Price__c</summarizedField>
    <summaryForeignKey>Lab_Order_Panel__c.Lab_Order__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Payment_Transaction_Id__c.field-meta.xml
<CustomField>
    <fullName>Payment_Transaction_Id__c</fullName>
    <externalId>true</externalId>
    <label>Payment Transaction Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Person_Record__c.field-meta.xml
<CustomField>
    <fullName>Person_Record__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Person Record</label>
    <referenceTo>Person_Record__c</referenceTo>
    <relationshipLabel>Lab Orders</relationshipLabel>
    <relationshipName>Lab_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Registrant_Email__c.field-meta.xml
<CustomField>
    <fullName>Registrant_Email__c</fullName>
    <formula>Person_Record__r.Email__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Registrant Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Registrant_Name__c.field-meta.xml
<CustomField>
    <fullName>Registrant_Name__c</fullName>
    <description>Allows NCS team to see registrant info on the LO.</description>
    <formula>Person_Record__r.First_Name__c &amp;&quot; &quot;&amp; Person_Record__r.Last_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Registrant Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>PA Acknowledged</fullName>
            </value>
            <value>
                <fullName>PA Approved</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Partial Results Ready</fullName>
            </value>
            <value>
                <fullName>Results Ready</fullName>
            </value>
            <value>
                <fullName>PA Rejected</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>PWN Acknowledged</fullName>
                <isActive>false</isActive>
                <label>PWN Acknowledged</label>
            </value>
            <value>
                <fullName>PWN Approved</fullName>
                <isActive>false</isActive>
                <label>PWN Approved</label>
            </value>
            <value>
                <fullName>PWN Rejected</fullName>
                <isActive>false</isActive>
                <label>PWN Rejected</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lab_Order_Panel__c/Lab_Order_Panel__c.object-meta.xml
<CustomObject>
    <label>Lab Order Panel</label>
    <nameField>
        <displayFormat>PNID- {000000000}</displayFormat>
        <label>Lab Panel ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lab Order Panels</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Lab_Order_Panel__c/fields/Lab_Order__c.field-meta.xml
<CustomField>
    <fullName>Lab_Order__c</fullName>
    <label>Lab Order</label>
    <referenceTo>Lab_Order__c</referenceTo>
    <relationshipName>Lab_Order_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Lab_Order_Panel__c/fields/Panel_Code__c.field-meta.xml
<CustomField>
    <fullName>Panel_Code__c</fullName>
    <formula>Panel__r.Panel_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Panel Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lab_Order_Panel__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Results Ready</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>TNP</fullName>
            </value>
            <value>
                <fullName>PA Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Partial Results Ready</fullName>
            </value>
            <value>
                <fullName>PWN Rejected</fullName>
                <isActive>false</isActive>
                <label>PWN Rejected</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lab_Panel_Test__c/Lab_Panel_Test__c.object-meta.xml
<CustomObject>
    <label>Lab Panel Test</label>
    <nameField>
        <displayFormat>TID - {00000000}</displayFormat>
        <label>Lab Panel Test ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lab Panel Tests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Lab_Panel_Test__c/fields/Lab_Order__c.field-meta.xml
<CustomField>
    <fullName>Lab_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lab Order</label>
    <referenceTo>Lab_Order__c</referenceTo>
    <relationshipLabel>Lab Panel Tests</relationshipLabel>
    <relationshipName>Lab_Panel_Tests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lab_Panel_Test__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Test Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>TNP</fullName>
            </value>
            <value>
                <fullName>Results Ready</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>PA Rejected</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Partial Results Ready</fullName>
            </value>
            <value>
                <fullName>PWN Rejected</fullName>
                <isActive>false</isActive>
                <label>PWN Rejected</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Client_Id__c.field-meta.xml
<CustomField>
    <fullName>Client_Id__c</fullName>
    <label>Client_Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PartnerClientMap__c/PartnerClientMap__c.object-meta.xml
<CustomObject>
    <label>Partner Client Map</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PartnerClientMaps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PartnerClientMap__c/fields/Partner_Name__c.field-meta.xml
<CustomField>
    <fullName>Partner_Name__c</fullName>
    <label>Partner Name</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/PartnerClientMap__c/fields/Sales_Channel__c.field-meta.xml
<CustomField>
    <fullName>Sales_Channel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Channel</label>
    <referenceTo>SalesChannel</referenceTo>
    <relationshipLabel>PartnerClientMaps</relationshipLabel>
    <relationshipName>PartnerClientMaps</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PartnerOrdersRestAPITest.cls
@isTest
private class PartnerOrdersRestAPITest {

    @testSetup
    static void setupData() {
        Account account = new Account(Name = 'Partner Orders Test Account');
        insert account;

        Contact contact = new Contact(AccountId = account.Id, LastName = 'Tester');
        insert contact;

        Person_Record__c person = new Person_Record__c(
            First_Name__c        = 'Partner',
            Last_Name__c         = 'Tester',
            Email__c             = 'partner.orders@example.com',
            Address_Line_1__c    = '123 Main St',
            City__c              = 'Secaucus',
            Country__c           = 'USA',
            State__c             = 'NJ',
            Postal_Code__c       = '07094',
            Phone__c             = '1234567890',
            Gender__c            = 'Male',
            Date_of_Birth__c     = Date.newInstance(1990, 1, 1),
            Contact__c           = contact.Id,
            Unique_Identifier__c = 'partner.orders@example.com:1990-01-01:test'
        );
        insert person;

        SalesChannel salesChannel = new SalesChannel(SalesChannelName = 'Partner Orders Test');
        insert salesChannel;

        PartnerClientMap__c partnerMap = new PartnerClientMap__c(
            Name             = 'Test Partner',
            Partner_Name__c  = 'Test Partner',
            Client_ID__c     = 'TP001',
            Sales_Channel__c = salesChannel.Id
        );
        insert partnerMap;

        // Order_Status__c, Partner_Order_Total__c, Registrant_Name__c, Registrant_Email__c
        // are formula / externally-managed fields — not writable via DML
        List<Lab_Order__c> labOrders = new List<Lab_Order__c>{
            new Lab_Order__c(
                Name                      = 'LO-T001',
                Client_Name__c            = 'Test Partner',
                Client_ID__c              = 'TP001',
                Partner_Client_Map__c     = partnerMap.Id,
                Status__c                 = 'Results Ready',
                Payment_Transaction_Id__c = 'TXN-001',
                Person_Record__c          = person.Id,
                Account__c                = account.Id
            ),
            new Lab_Order__c(
                Name                  = 'LO-T002',
                Client_Name__c        = 'Test Partner',
                Client_ID__c          = 'TP001',
                Partner_Client_Map__c = partnerMap.Id,
                Status__c             = 'Registered',
                Person_Record__c      = person.Id,
                Account__c            = account.Id
            )
        };
        insert labOrders;

        Test.setCreatedDate(labOrders[0].Id, DateTime.now().addDays(-5));
        Test.setCreatedDate(labOrders[1].Id, DateTime.now().addDays(-3));

        // Panel_Code__c and Panel_Status__c are not writable — set only writable fields
        Lab_Order_Panel__c panel = new Lab_Order_Panel__c(
            Lab_Order__c   = labOrders[0].Id,
            Panel_Price__c = 49.99
        );
        insert panel;

        // Test_Code__c, Test_Name__c, Test_Description__c are not writable — set only writable fields
        Lab_Panel_Test__c lpt = new Lab_Panel_Test__c(
            Lab_Order_Panel__c = panel.Id,
            Lab_Order__c       = labOrders[0].Id,
            Status__c          = 'Results Ready'
        );
        insert lpt;
    }

    // ── Validation: missing parameters ────────────────────────────────────────

    @isTest
    static void getOrders_missingPartnerId_returns400() {
        setupContext(null, '2026-01-01', '2026-01-15', null, null);
        Test.startTest();
        PartnerOrdersRestAPI.getOrders();
        Test.stopTest();

        assertError(RestContext.response, 400, 'MISSING_PARAMETER');
    }

    @isTest
    static void getOrders_missingStartDate_returns400() {
        setupContext('TP001', null, '2026-01-15', null, null);
        Test.startTest();
        PartnerOrdersRestAPI.getOrders();
        Test.stopTest();

        assertError(RestContext.response, 400, 'MISSING_PARAMETER');
    }

    @isTest
    static void getOrders_missingEndDate_returns400() {
        setupContext('TP001', '2026-01-01', null, null, null);
        Test.startTest();
        PartnerOrdersRestAPI.getOrders();
        Test.stopTest();

        assertError(RestContext.response, 400, 'MISSING_PARAMETER');
    }

    // ── Validation: date errors ───────────────────────────────────────────────

    @isTest
    static void getOrders_invalidStartDateFormat_returns400() {
        setupContext('TP001', 'not-a-date', '2026-01-15', null, null);
        Test.startTest();
        PartnerOrdersRestAPI.getOrders();
        Test.stopTest();

        assertError(RestContext.response, 400, 'INVALID_DATE');
    }

    @isTest
    static void getOrders_invalidEndDateFormat_returns400() {
        setupContext('TP001', '2026-01-01', 'bad', null, null);
        Test.startTest();
        PartnerOrdersRestAPI.getOrders();
        Test.stopTest();

        assertError(RestContext.response, 400, 'INVALID_DATE');
    }

    @isTest
    static void getOrders_endDateBeforeStartDate_returns400() {
        setupContext('TP001', '2026-01-15', '2026-01-01', null, null);
        Test.startTest();
        PartnerOrdersRestAPI.getOrders();
        Test.stopTest();

        assertError(RestContext.response, 400, 'INVALID_DATE_RANGE');
    }

    @isTest
    static void getOrders_dateRangeExceeds31Days_returns400() {
        setupContext('TP001', '2026-01-01', '2026-02-15', null, null);
        Test.startTest();
        PartnerOrdersRestAPI.getOrders();
        Test.stopTest();

        assertError(RestContext.response, 400, 'DATE_RANGE_TOO_LARGE');
    }

    @isTest
    static void getOrders_sameDayRange_isAllowed() {
        setupContext('TP001', '2026-01-01', '2026-01-01', null, null);
        Test.startTest();
        PartnerOrdersRestAPI.getOrders();
        Test.stopTest();

        System.assertEquals(200, RestContext.response.statusCode);
    }

    // ── Validation: format and partner ────────────────────────────────────────

    @isTest
    static void getOrders_invalidFormat_returns400() {
        setupContext('TP001', '2026-01-01', '2026-01-15', null, 'xml');
        Test.startTest();
        PartnerOrdersRestAPI.getOrders();
        Test.stopTest();

        assertError(RestContext.response, 400, 'INVALID_FORMAT');
    }

    @isTest
    static void getOrders_unknownClientId_returns403() {
        setupContext('UNKNOWN-PARTNER-XYZ', '2026-01-01', '2026-01-15', null, null);
        Test.startTest();
        PartnerOrdersRestAPI.getOrders();
        Test.stopTest();

        assertError(RestContext.response, 403, 'PARTNER_NOT_FOUND');
    }

    @isTest
    static void getOrders_invalidRequestBody_returns400() {
        RestRequest req = new RestRequest();
        req.requestURI  = '/services/apexrest/partner/v1/orders';
        req.httpMethod  = 'POST';
        req.requestBody = Blob.valueOf('this is not json');
        req.addHeader('Content-Type', 'application/json');
        RestContext.request  = req;
        RestContext.response = new RestResponse();

        Test.startTest();
        PartnerOrdersRestAPI.getOrders();
        Test.stopTest();

        assertError(RestContext.response, 400, 'INVALID_REQUEST_BODY');
    }

    // ── Success: order-level JSON ─────────────────────────────────────────────

    @isTest
    static void getOrders_ordersJson_returns200WithCorrectStructure() {
        String startStr = String.valueOf(Date.today().addDays(-10));
        String endStr   = String.valueOf(Date.today());
        setupContext('TP001', startStr, endStr, null, 'json');

        Test.startTest();
        PartnerOrdersRestAPI.getOrders();
        Test.stopTest();

        RestResponse res  = RestContext.response;
        String       body = res.responseBody.toString();
        System.assertEquals(200, res.statusCode);
        System.assert(res.headers.get('Content-Type').contains('application/json'),
            'Content-Type must be application/json');
        System.assert(body.startsWith('['),                   'Response must be a JSON array');
        System.assert(body.contains('"orderId"'),             'Must include orderId key');
        System.assert(body.contains('"clientAccountNumber"'), 'Must include clientAccountNumber key');
        System.assert(body.contains('"partnerName"'),         'Must include partnerName key');
        System.assert(body.contains('"dateCreated"'),         'Must include dateCreated key');
        System.assert(body.contains('"wholesalePrice"'),      'Must include wholesalePrice key');
        System.assert(body.contains('"paymentTransactionId"'),'Must include paymentTransactionId key');
        System.assert(body.contains('TP001'),                 'Must include client ID value');
        System.assert(body.contains('LO-T001'),               'Must include order name');
        System.assert(body.contains('Test Partner'),          'Must include partner name');
        System.assert(body.contains('TXN-001'),               'Must include payment transaction ID');
    }

    @isTest
    static void getOrders_defaultFormatIsJson() {
        String startStr = String.valueOf(Date.today().addDays(-10));
        String endStr   = String.valueOf(Date.today());
        setupContext('TP001', startStr, endStr, null, null);

        Test.startTest();
        PartnerOrdersRestAPI.getOrders();
        Test.stopTest();

        RestResponse res = RestContext.response;
        System.assertEquals(200, res.statusCode);
        System.assert(res.responseBody.toString().startsWith('['),
            'Omitting format must default to JSON array');
    }

    @isTest
    static void getOrders_includeTestsFalse_excludesPanelKeys() {
        String startStr = String.valueOf(Date.today().addDays(-10));
        String endStr   = String.valueOf(Date.today());
        setupContext('TP001', startStr, endStr, false, 'json');

        Test.startTest();
        PartnerOrdersRestAPI.getOrders();
        Test.stopTest();

        String body = RestContext.response.responseBody.toString();
        System.assertEquals(200, RestContext.response.statusCode);
        System.assert(!body.contains('"panelCode"'), 'Order-level response must not include panelCode');
        System.assert(!body.contains('"testCode"'),  'Order-level response must not include testCode');
    }

    // ── Success: order-level CSV ──────────────────────────────────────────────

    @isTest
    static void getOrders_ordersCsv_returns200WithHeaderAndData() {
        String startStr = String.valueOf(Date.today().addDays(-10));
        String endStr   = String.valueOf(Date.today());
        setupContext('TP001', startStr, endStr, null, 'csv');

        Test.startTest();
        PartnerOrdersRestAPI.getOrders();
        Test.stopTest();

        RestResponse res  = RestContext.response;
        String       body = res.responseBody.toString();
        System.assertEquals(200, res.statusCode);
        System.assert(res.headers.get('Content-Type').contains('text/csv'),
            'Content-Type must be text/csv');
        System.assert(body.contains('clientAccountNumber'),   'Must include clientAccountNumber header');
        System.assert(body.contains('orderId'),               'Must include orderId header');
        System.assert(body.contains('paymentTransactionId'),  'Must include paymentTransactionId header');
        System.assert(body.contains('TP001'),                 'Must include client ID value in data row');
        System.assert(body.contains('LO-T001'),               'Must include order name in data row');
        System.assert(body.contains('TXN-001'),               'Must include transaction ID in data row');
    }

    // ── Success: empty results ────────────────────────────────────────────────

    @isTest
    static void getOrders_noOrdersInRange_returns200WithEmptyJsonArray() {
        setupContext('TP001', '2020-01-01', '2020-01-31', null, 'json');

        Test.startTest();
        PartnerOrdersRestAPI.getOrders();
        Test.stopTest();

        RestResponse res = RestContext.response;
        System.assertEquals(200, res.statusCode);
        System.assertEquals('[]', res.responseBody.toString(),
            'Empty result must return JSON empty array');
    }

    @isTest
    static void getOrders_noOrdersInRange_returns200WithCsvHeaderOnly() {
        setupContext('TP001', '2020-01-01', '2020-01-31', null, 'csv');

        Test.startTest();
        PartnerOrdersRestAPI.getOrders();
        Test.stopTest();

        RestResponse res  = RestContext.response;
        String       body = res.responseBody.toString();
        System.assertEquals(200, res.statusCode);
        System.assert(body.contains('clientAccountNumber'), 'Must return CSV header for empty result');
        System.assert(!body.contains('LO-T001'), 'Must not include data rows for empty result');
    }

    // ── Success: test-level JSON ──────────────────────────────────────────────

    @isTest
    static void getOrders_includeTestsJson_returns200WithPanelAndTestFields() {
        String startStr = String.valueOf(Date.today().addDays(-10));
        String endStr   = String.valueOf(Date.today());
        setupContext('TP001', startStr, endStr, true, 'json');

        Test.startTest();
        PartnerOrdersRestAPI.getOrders();
        Test.stopTest();

        RestResponse res  = RestContext.response;
        String       body = res.responseBody.toString();
        System.assertEquals(200, res.statusCode);
        System.assert(body.startsWith('['), 'Response must be a JSON array');
        System.assert(body.contains('"orderId"'),             'Must include orderId key');
        System.assert(body.contains('"clientAccountNumber"'), 'Must include clientAccountNumber key');
        System.assert(body.contains('LO-T001'),               'Must include order name value');
        System.assert(body.contains('"panelCode"'),   'Must include panelCode key');
        System.assert(body.contains('"panelPrice"'),  'Must include panelPrice key');
        System.assert(body.contains('"panelStatus"'), 'Must include panelStatus key');
        System.assert(body.contains('49.99'),         'Must include panel price value');
        System.assert(body.contains('"testCode"'),        'Must include testCode key');
        System.assert(body.contains('"testName"'),        'Must include testName key');
        System.assert(body.contains('"testDescription"'), 'Must include testDescription key');
        System.assert(body.contains('"testStatus"'),      'Must include testStatus key');
        System.assert(body.contains('Results Ready'),     'Must include test status value');
    }

    // ── Success: test-level CSV ───────────────────────────────────────────────

    @isTest
    static void getOrders_includeTestsCsv_returns200WithTestColumns() {
        String startStr = String.valueOf(Date.today().addDays(-10));
        String endStr   = String.valueOf(Date.today());
        setupContext('TP001', startStr, endStr, true, 'csv');

        Test.startTest();
        PartnerOrdersRestAPI.getOrders();
        Test.stopTest();

        RestResponse res  = RestContext.response;
        String       body = res.responseBody.toString();
        System.assertEquals(200, res.statusCode);
        System.assert(res.headers.get('Content-Type').contains('text/csv'),
            'Content-Type must be text/csv');
        System.assert(body.contains('panelCode'),  'Must include panelCode in CSV header');
        System.assert(body.contains('testCode'),   'Must include testCode in CSV header');
        System.assert(body.contains('testStatus'), 'Must include testStatus in CSV header');
        System.assert(body.contains('49.99'),      'Must include panel price value in CSV');
        System.assert(body.contains('Results Ready'), 'Must include test status value in CSV');
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    // Builds a POST body from the supplied params (null values are omitted)
    private static void setupContext(
        String partnerId, String startDate, String endDate,
        Object includeTests, Object format
    ) {
        Map<String, Object> bodyMap = new Map<String, Object>();
        if (partnerId    != null) bodyMap.put('partnerId',    partnerId);
        if (startDate    != null) bodyMap.put('startDate',    startDate);
        if (endDate      != null) bodyMap.put('endDate',      endDate);
        if (includeTests != null) bodyMap.put('includeTests', includeTests);
        if (format       != null) bodyMap.put('format',       format);

        RestRequest req = new RestRequest();
        req.requestURI  = '/services/apexrest/partner/v1/orders';
        req.httpMethod  = 'POST';
        req.requestBody = Blob.valueOf(JSON.serialize(bodyMap));
        req.addHeader('Content-Type', 'application/json');
        RestContext.request  = req;
        RestContext.response = new RestResponse();
    }

    private static void assertError(RestResponse res, Integer expectedStatus, String expectedCode) {
        System.assertEquals(expectedStatus, res.statusCode,
            'Expected HTTP ' + expectedStatus);
        System.assert(res.responseBody.toString().contains(expectedCode),
            'Expected errorCode ' + expectedCode + ' in: ' + res.responseBody.toString());
    }
}