force-app/main/default/objects/Lab_Order__c/Lab_Order__c.object-meta.xml
<CustomObject>
    <label>Lab Order</label>
    <nameField>
        <label>Lab Order ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lab Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lab_Order__c/fields/Client_ID__c.field-meta.xml
<CustomField>
    <fullName>Client_ID__c</fullName>
    <label>Client ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Consent_Minor_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Consent_Minor_Date_Time__c</fullName>
    <label>Consent for Minor Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Is_Partner__c.field-meta.xml
<CustomField>
    <fullName>Is_Partner__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Partner</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Minor_Address_Line_1__c.field-meta.xml
<CustomField>
    <fullName>Minor_Address_Line_1__c</fullName>
    <label>Minor Address Line 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Minor_Address_Line_2__c.field-meta.xml
<CustomField>
    <fullName>Minor_Address_Line_2__c</fullName>
    <label>Minor Address Line 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Minor_City__c.field-meta.xml
<CustomField>
    <fullName>Minor_City__c</fullName>
    <label>Minor City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Minor_Country__c.field-meta.xml
<CustomField>
    <fullName>Minor_Country__c</fullName>
    <label>Minor Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Minor_Date_of_Birth__c.field-meta.xml
<CustomField>
    <fullName>Minor_Date_of_Birth__c</fullName>
    <label>Minor Date of Birth</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Minor_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Minor_First_Name__c</fullName>
    <label>Minor First Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Minor_Gender__c.field-meta.xml
<CustomField>
    <fullName>Minor_Gender__c</fullName>
    <label>Minor Gender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Minor_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Minor_Last_Name__c</fullName>
    <label>Minor Last Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Minor_State__c.field-meta.xml
<CustomField>
    <fullName>Minor_State__c</fullName>
    <label>Minor State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
            <value>
                <fullName>NV</fullName>
            </value>
            <value>
                <fullName>NH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Minor_Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Minor_Zip_Code__c</fullName>
    <label>Minor Zip Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Order_Summary__c.field-meta.xml
<CustomField>
    <fullName>Order_Summary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Summary</label>
    <referenceTo>OrderSummary</referenceTo>
    <relationshipLabel>Lab Orders</relationshipLabel>
    <relationshipName>Lab_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Person_Record__c.field-meta.xml
<CustomField>
    <fullName>Person_Record__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Person Record</label>
    <referenceTo>Person_Record__c</referenceTo>
    <relationshipLabel>Lab Orders</relationshipLabel>
    <relationshipName>Lab_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lab_Order_Panel__c/Lab_Order_Panel__c.object-meta.xml
<CustomObject>
    <label>Lab Order Panel</label>
    <nameField>
        <displayFormat>PNID- {000000000}</displayFormat>
        <label>Lab Panel ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lab Order Panels</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Lab_Order_Panel__c/fields/AOE__c.field-meta.xml
<CustomField>
    <fullName>AOE__c</fullName>
    <label>AOE</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Lab_Order_Panel__c/fields/Lab_Order__c.field-meta.xml
<CustomField>
    <fullName>Lab_Order__c</fullName>
    <label>Lab Order</label>
    <referenceTo>Lab_Order__c</referenceTo>
    <relationshipName>Lab_Order_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Lab_Order_Panel__c/fields/Panel__c.field-meta.xml
<CustomField>
    <fullName>Panel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Panel</label>
    <referenceTo>Panel__c</referenceTo>
    <relationshipName>Lab_Order_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lab_Panel_Test__c/Lab_Panel_Test__c.object-meta.xml
<CustomObject>
    <label>Lab Panel Test</label>
    <nameField>
        <displayFormat>TID - {00000000}</displayFormat>
        <label>Lab Panel Test ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lab Panel Tests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Lab_Panel_Test__c/fields/Lab_Order__c.field-meta.xml
<CustomField>
    <fullName>Lab_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lab Order</label>
    <referenceTo>Lab_Order__c</referenceTo>
    <relationshipLabel>Lab Panel Tests</relationshipLabel>
    <relationshipName>Lab_Panel_Tests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lab_Panel_Test__c/fields/Lab_Order_Panel__c.field-meta.xml
<CustomField>
    <fullName>Lab_Order_Panel__c</fullName>
    <label>Lab Order Panel</label>
    <referenceTo>Lab_Order_Panel__c</referenceTo>
    <relationshipName>Lab_Panel_Analytes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Lab_Panel_Test__c/fields/Panel_Test__c.field-meta.xml
<CustomField>
    <fullName>Panel_Test__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Panel Test ID</label>
    <referenceTo>Panel_Test__c</referenceTo>
    <relationshipLabel>Lab Panel Tests</relationshipLabel>
    <relationshipName>Lab_Panel_Analytes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lab_Panel_Test__c/fields/Test_Code__c.field-meta.xml
<CustomField>
    <fullName>Test_Code__c</fullName>
    <formula>Panel_Test__r.Test__r.Test_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Test Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lab_Panel_Test__c/fields/Test_Name__c.field-meta.xml
<CustomField>
    <fullName>Test_Name__c</fullName>
    <formula>Panel_Test__r.Test__r.Test_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Test Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Client_Id__c.field-meta.xml
<CustomField>
    <fullName>Client_Id__c</fullName>
    <label>Client_Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Minor_Order__c.field-meta.xml
<CustomField>
    <fullName>Minor_Order__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Minor Order</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OrderDeliveryGroup/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderDeliveryGroup/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderSummary/fields/Client_Id__c.field-meta.xml
<CustomField>
    <fullName>Client_Id__c</fullName>
    <defaultValue>TEXT(97554902)</defaultValue>
    <label>Client Id</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderSummary/fields/Minor_Order__c.field-meta.xml
<CustomField>
    <fullName>Minor_Order__c</fullName>
    <formula>OriginalOrder.Minor_Order__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Minor Order</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Panel__c/Panel__c.object-meta.xml
<CustomObject>
    <label>Panel</label>
    <nameField>
        <displayFormat>PR-{00000000}</displayFormat>
        <label>Panel Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Panels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Panel__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Panels</relationshipLabel>
    <relationshipName>Panels</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Panel_Test__c/Panel_Test__c.object-meta.xml
<CustomObject>
    <label>Panel Test</label>
    <nameField>
        <displayFormat>PTR - {000000000}</displayFormat>
        <label>Panel Test ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Panel Tests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Panel_Test__c/fields/Panel__c.field-meta.xml
<CustomField>
    <fullName>Panel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Panel</label>
    <referenceTo>Panel__c</referenceTo>
    <relationshipName>Panel_Analytes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Panel_Test__c/fields/Test__c.field-meta.xml
<CustomField>
    <fullName>Test__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Test</label>
    <referenceTo>Test__c</referenceTo>
    <relationshipLabel>Panel Tests</relationshipLabel>
    <relationshipName>Panel_Analytes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Both</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Male</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CreateLabOrderPWNServiceTest.cls
@IsTest
public class CreateLabOrderPWNServiceTest {

    @IsTest
    static void testCreatePWNOrder_Success() {
        // Arrange
        List<CreateLabPWNServiceOrder.PWNServiceInput> inputs = new List<CreateLabPWNServiceOrder.PWNServiceInput>();
        
        

       Product2 product = new Product2();
            product.Name = 'Test';
            product.Description = 'Test';
            product.ProductCode = 'test';
            product.StockKeepingUnit = 'Test'+ String.valueOf(1);
            product.DisplayUrl = '';
            product.ExternalId = 'sku123';
            product.IsActive = true;
            insert product;

        Panel__c panel =  new Panel__c(Product__c=product.Id);
        insert panel;

        Test__c test =  new Test__c(Test_Code__c='test',Test_Name__c='test',Description__c='test');
        insert test;

        Panel_Test__c panelTest= new Panel_Test__c(Panel__c=panel.Id,Test__c=test.Id);
        insert panelTest;

        // Insert mock Person and Lab_Order__c records
        Person_Record__c person = new Person_Record__c(
            First_Name__c = 'John',
            Last_Name__c = 'Doe',
            Email__c = 'john.doe@example.com',
            Address_Line_1__c = '123 Main St',
            Unique_Identifier__c ='Uniqu1',
            City__c = 'Anytown',
            Country__c = 'USA',
            State__c = 'CA',
            Postal_Code__c = '12345',
            Phone__c = '1234567890',
            Gender__c = 'Male',
            Date_of_Birth__c = Date.newInstance(1990, 1, 1)
        );
        insert person;

        Lab_Order__c labOrder = new Lab_Order__c(
            Is_Partner__c=true,
            Client_Id__c = '12345',
            Person_Record__c = person.Id
        );
        insert labOrder;

        // Insert Lab_Order_Panel__c and Lab_Panel_Test__c records
        Lab_Order_Panel__c labOrderPanel = new Lab_Order_Panel__c(Lab_Order__c = labOrder.Id, AOE__c = '[{"isAoe":true}]');
        insert labOrderPanel;

        Lab_Panel_Test__c labPanelTest = new Lab_Panel_Test__c(Lab_Order_Panel__c = labOrderPanel.Id, Panel_Test__c=panelTest.Id);
        insert labPanelTest;

        // Mock HTTP response
        System.Test.setMock(HttpCalloutMock.class, new MockPWNHttpResponse(201, '{"order": {"physicianReview": {"firstName": "John", "lastName": "Doe", "upin": "12345", "npi": "67890"}, "id": "pwnId123"}}'));

        CreateLabPWNServiceOrder.PWNServiceInput input = new CreateLabPWNServiceOrder.PWNServiceInput();
        input.token = 'mockToken';
        input.labOrderId = labOrder.Id;
        inputs.add(input);
        // Act
        System.Test.startTest();
        List<CreateLabPWNServiceOrder.PWNServiceOutput> result = CreateLabPWNServiceOrder.createPWNOrder(inputs);
        System.Test.stopTest();

        // Assert
        System.assertEquals(1, result.size());
        CreateLabPWNServiceOrder.PWNServiceOutput output = result[0];
        System.assertEquals(labOrder.Id, output.labOrderId);
        System.assertEquals('Success', output.status);
        System.assertEquals('201', output.responseCode);
        System.assertEquals('Success', output.responseMessage);
        System.assertEquals('John', output.firstName);
        System.assertEquals('Doe', output.lastName);
        System.assertEquals('12345', output.upin);
        System.assertEquals('67890', output.npi);
        System.assertEquals('pwnId123', output.pwnID);
    }

    @IsTest
    static void testCreatePWNOrder_Error() {
        // Arrange
        List<CreateLabPWNServiceOrder.PWNServiceInput> inputs = new List<CreateLabPWNServiceOrder.PWNServiceInput>();
        
        Person_Record__c  pr = new Person_Record__c ();
        pr.First_Name__c = 'test';
        pr.Date_of_Birth__c = Date.valueOf('1994-09-30');
        pr.Gender__c = 'Male';
        pr.Address_Line_1__c = '2005 Lamberts Branch Road'; 
        pr.City__c = 'Taloga';
        pr.Email__c = 'srini491.03@yopmail.com';
        pr.Last_Name__c = 'TestLastName';
        pr.Phone__c = '7389768765';
        pr.Postal_Code__c = '73667';
        pr.State__c = 'Oklahoma';
        pr.Unique_Identifier__c = 'srini491.03@yopmail.com:1994-09-30:test';
        insert pr;
        

        Product2 product = new Product2();
            product.Name = 'Test';
            product.Description = 'Test';
            product.ProductCode = 'test';
            product.StockKeepingUnit = 'Test'+ String.valueOf(1);
            product.DisplayUrl = '';
             product.ExternalId = 'sku123';
            product.IsActive = true;
            insert product;

        Panel__c panel =  new Panel__c(Product__c=product.Id);
        insert panel;

        Test__c test =  new Test__c(Test_Code__c='test',Test_Name__c='test',Description__c='test');
        insert test;

        Panel_Test__c panelTest= new Panel_Test__c(Panel__c=panel.Id,Test__c=test.Id);
        insert panelTest;

        // Insert required records
        Lab_Order__c labOrder = new Lab_Order__c(
           Is_Partner__c=true,
            Client_Id__c = '12345',Person_Record__c = pr.id
        );
        insert labOrder;
        //String AOEString = 'Test';
        //Object obj = (Object)AOEString;
			List<Object> AOELst = new List<Object>();
       // AOELst.add(obj);
        Lab_Order_Panel__c labOrderPanel = new Lab_Order_Panel__c(Lab_Order__c = labOrder.Id);
        insert labOrderPanel;

         Lab_Panel_Test__c labPanelTest = new Lab_Panel_Test__c(Lab_Order_Panel__c = labOrderPanel.Id, Panel_Test__c=panelTest.Id);
        insert labPanelTest;

        // Mock HTTP response for error
        System.Test.setMock(HttpCalloutMock.class, new MockPWNHttpResponse(400, '{"error": {"fault": {"message": ["Invalid request data"]}}}'));

        CreateLabPWNServiceOrder.PWNServiceInput input = new CreateLabPWNServiceOrder.PWNServiceInput();
        input.token = 'mockToken';
        input.labOrderId = labOrder.Id;
        inputs.add(input);
        // Act
        System.Test.startTest();
        List<CreateLabPWNServiceOrder.PWNServiceOutput> result = CreateLabPWNServiceOrder.createPWNOrder(inputs);
        System.Test.stopTest();

        // Assert
        System.assertEquals(1, result.size());
        CreateLabPWNServiceOrder.PWNServiceOutput output = result[0];
        // System.assertEquals('Error', output.status);
        // System.assertEquals('400', output.responseCode);
        // System.assertEquals('Invalid request data', output.responseMessage);
    }
    
    // Mock class for HTTP response
    private class MockPWNHttpResponse implements HttpCalloutMock {
        private Integer statusCode;
        private String responseBody;

        public MockPWNHttpResponse(Integer statusCode, String responseBody) {
            this.statusCode = statusCode;
            this.responseBody = responseBody;
        }

        public HTTPResponse respond(HTTPRequest req) {
            HttpResponse res = new HttpResponse();
            res.setStatusCode(statusCode);
            res.setBody(responseBody);
            return res;
        }
    }


@IsTest(SeeAllData=true)
static void testCreatePWNOrder_Success_Minor() {
        //Account for Minors
        Account minorAccount = new Account(
            Name = 'Minor Account'
        );
        insert minorAccount;

        Product2 shippingProduct = [SELECT Id, ProductCode FROM Product2 WHERE ProductCode = 'Shipping' LIMIT 1];
        // Arrange
        List<CreateLabPWNServiceOrder.PWNServiceInput> inputs = new List<CreateLabPWNServiceOrder.PWNServiceInput>();
        
        // Mock related data setup        
       Product2 product = new Product2();
        product.Name = 'Test';
        product.Description = 'Test';
        product.ProductCode = 'test';
        product.StockKeepingUnit = 'Test'+ String.valueOf(1);
        product.DisplayUrl = '';
        product.ExternalId = 'sku123';
        product.IsActive = true;
        insert product;

        Id pricebookId = System.Test.getStandardPricebookId();
        Pricebook2 standardPricebook = new Pricebook2(    Id = pricebookId,    IsActive = true);
        update standardPricebook;

        //Order for Minor
        Order minor_order = new Order(
            AccountId = minorAccount.Id,
            EffectiveDate = Date.today(),
            Status = 'Draft',
            Client_Id__c = '12345',
            Minor_Order__c = true,
            Pricebook2Id = standardPricebook.Id
        );
        insert minor_order;

        PricebookEntry pbe = new PricebookEntry(
            Pricebook2Id = standardPricebook.Id,
            Product2Id = product.Id,
            UnitPrice = 100.00,
            IsActive = true
        );
        insert pbe;

        Id deliveryMethodId = [
            SELECT Id 
            FROM OrderDeliveryMethod 
            WHERE Name = 'Standard' 
            LIMIT 1
        ].Id;

        OrderDeliveryGroup odg = new OrderDeliveryGroup(
            OrderId = minor_order.Id,
            DeliverToName = 'Minor Guardian',
            OrderDeliveryMethodId = deliveryMethodId
        );
        insert odg;

        OrderItem oi = new OrderItem(
            OrderId = minor_order.Id,
            Product2Id = shippingProduct.Id,
            PricebookEntryId = pbe.Id,
            Quantity = 1,
            UnitPrice = 100.00,
            OrderDeliveryGroupId = odg.Id,
            TotalLineAmount = 149.0
        );
        insert oi;

        minor_order.Status = 'Activated';
        update minor_order;

        OrderSummary os = [SELECT Id FROM OrderSummary WHERE OriginalOrderId = :minor_order.Id LIMIT 1];

        String newOrderSummaryId = null;

        if (os == null) {
            // 1. Instantiate the Input Representation
            ConnectApi.OrderSummaryInputRepresentation orderSummaryInput = 
                new ConnectApi.OrderSummaryInputRepresentation();

            // 2. Set the required OrderId
            orderSummaryInput.orderId = minor_order.Id;

            // 3. (Optional but recommended) Set the OrderLifeCycleType
            // 'MANAGED' is the default and used by Salesforce Order Management.
            // 'UNMANAGED' is used for orders managed by an external system.
            orderSummaryInput.orderLifeCycleType = 'UNMANAGED'; 

            //orderSummaryInput.orderDeliveryMethodId = deliveryMethodId;
            // 4. Call the static creation method
            ConnectApi.OrderSummaryOutputRepresentation orderSummaryOutput = 
                ConnectApi.OrderSummaryCreation.createOrderSummary(orderSummaryInput);
            
            newOrderSummaryId = orderSummaryOutput.orderSummaryId;
        }else {
            newOrderSummaryId = os.Id;
        }

        // The actual OrderSummary record ID is in the output:
       

        Panel__c panel = new Panel__c(Product__c = product.Id);
        insert panel;

        Test__c test = new Test__c(Test_Code__c = 'TMINOR', Test_Name__c = 'Minor Test', Description__c = 'Minor flow test');
        insert test;

        Panel_Test__c panelTest = new Panel_Test__c(Panel__c = panel.Id, Test__c = test.Id);
        insert panelTest;

        // Insert Parent Person record
        Person_Record__c parent = new Person_Record__c(
            First_Name__c = 'Parent',
            Last_Name__c = 'Guardian',
            Email__c = 'parent.guardian@example.com',
            Address_Line_1__c = '123 Minor Ln',
            Unique_Identifier__c = 'MinorUniq1',
            City__c = 'Smalltown',
            Country__c = 'USA',
            State__c = 'CA',
            Postal_Code__c = '90001',
            Phone__c = '5555551234',
            Gender__c = 'Female',
            Date_of_Birth__c = Date.newInstance(1980, 2, 2)
        );
        insert parent;


        // Insert Lab Order (with Minor fields)
        Lab_Order__c labOrder = new Lab_Order__c(
            Client_Id__c = 'C-1001',
            Person_Record__c = parent.Id,
            Minor_First_Name__c = 'Little',
            Minor_Last_Name__c = 'Guardian',
            Minor_Gender__c = 'Male',
            Minor_Date_of_Birth__c = Date.newInstance(2015, 5, 5),
            Consent_Minor_Date_Time__c = Date.newInstance(2024, 5, 5),
            Minor_Address_Line_1__c = '123 Minor Ln',
            Minor_Address_Line_2__c = '',
            Minor_City__c = 'Smalltown',
            Minor_State__c = 'CA',
            Minor_Zip_Code__c = '90001',
            Minor_Country__c = 'USA',
            Order_Summary__c = newOrderSummaryId
        );
        insert labOrder;

        // Insert Lab_Order_Panel__c and Lab_Panel_Test__c
        Lab_Order_Panel__c labOrderPanel = new Lab_Order_Panel__c(
            Lab_Order__c = labOrder.Id,
            AOE__c = '[{"isAoe":true,"question":"Age?","answer":"10"}]'
        );
        insert labOrderPanel;

        Lab_Panel_Test__c labPanelTest = new Lab_Panel_Test__c(
            Lab_Order_Panel__c = labOrderPanel.Id,
            Panel_Test__c = panelTest.Id
        );
        insert labPanelTest;

        // Mock successful HTTP response
        System.Test.setMock(HttpCalloutMock.class, 
            new MockPWNHttpResponse(
                201,
                '{"order": {"physicianReview": {"firstName": "DrTest", "lastName": "Smith", "upin": "U123", "npi": "NPI123"}, "id": "PWN-MINOR-123"}}'
            )
        );

        // Prepare Invocable Input
        CreateLabPWNServiceOrder.PWNServiceInput input = new CreateLabPWNServiceOrder.PWNServiceInput();
        input.token = 'mockToken';
        input.labOrderId = labOrder.Id;
        inputs.add(input);

        // Act
        System.Test.startTest();
        List<CreateLabPWNServiceOrder.PWNServiceOutput> result = CreateLabPWNServiceOrder.createPWNOrder(inputs);
        System.Test.stopTest();

        // Assert
        System.assertEquals(1, result.size(), 'One result expected');
        CreateLabPWNServiceOrder.PWNServiceOutput output = result[0];
        Map<String, Object> payloadMap = (Map<String, Object>) JSON.deserializeUntyped(output.requestPayload);
        //nested objects
        Map<String, Object> order = (Map<String, Object>) payloadMap.get('order');
        Map<String, Object> customer = (Map<String, Object>) order.get('customer'); 
        //get the externalId
        String externalId = (String)customer.get('externalId');

        System.assertEquals(labOrder.Id, output.labOrderId);
        System.assertEquals('Success', output.status);
        System.assertEquals('201', output.responseCode);
        System.assertEquals('Success', output.responseMessage);
        System.assertEquals('DrTest', output.firstName);
        System.assertEquals('Smith', output.lastName);
        System.assertEquals('U123', output.upin);
        System.assertEquals('NPI123', output.npi);
        System.assertEquals('PWN-MINOR-123', output.pwnID);
        System.assertEquals(externalId == '' || externalId == null, true,'External Id should be empty when is a minor.');


    }


}