force-app/main/default/objects/Lab_Order__c/Lab_Order__c.object-meta.xml
<CustomObject>
    <label>Lab Order</label>
    <nameField>
        <label>Lab Order ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lab Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lab_Order__c/fields/Is_Refund_Error__c.field-meta.xml
<CustomField>
    <fullName>Is_Refund_Error__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Refund Error</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Order_Summary__c.field-meta.xml
<CustomField>
    <fullName>Order_Summary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Summary</label>
    <referenceTo>OrderSummary</referenceTo>
    <relationshipLabel>Lab Orders</relationshipLabel>
    <relationshipName>Lab_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Refund_Amount__c.field-meta.xml
<CustomField>
    <fullName>Refund_Amount__c</fullName>
    <label>Refund Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Refund_Attempts__c.field-meta.xml
<CustomField>
    <fullName>Refund_Attempts__c</fullName>
    <label>Refund Attempts</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/LabOrderRefundRetryBatchSchedule.cls
global with sharing class  LabOrderRefundRetryBatchSchedule implements Schedulable{
    global void execute(SchedulableContext sc) {   
        LabOrderRefundRetryBatch btch= new LabOrderRefundRetryBatch();
        btch.query = 'SELECT Id, Order_Summary__c,Refund_Amount__c,Refund_Attempts__c FROM Lab_Order__c WHERE Refund_Attempts__c < 4 and Is_Refund_Error__c = true ';
        Database.executeBatch(btch,1);
      }
}