force-app/main/default/objects/Lab_Order__c/Lab_Order__c.object-meta.xml
<CustomObject>
    <label>Lab Order</label>
    <nameField>
        <label>Lab Order ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lab Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lab_Order__c/fields/Full_Refund__c.field-meta.xml
<CustomField>
    <fullName>Full_Refund__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Full Refund</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Is_Kit__c.field-meta.xml
<CustomField>
    <fullName>Is_Kit__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Kit</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Is_PWN_Approved__c.field-meta.xml
<CustomField>
    <fullName>Is_PWN_Approved__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is PA Approved</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Kit_Detail__c.field-meta.xml
<CustomField>
    <fullName>Kit_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Kit Detail</label>
    <referenceTo>Kit_Details__c</referenceTo>
    <relationshipLabel>Lab Orders</relationshipLabel>
    <relationshipName>Lab_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/PWN_ID__c.field-meta.xml
<CustomField>
    <fullName>PWN_ID__c</fullName>
    <externalId>true</externalId>
    <label>PA External ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/PWN_Status_Date__c.field-meta.xml
<CustomField>
    <fullName>PWN_Status_Date__c</fullName>
    <label>PA Status Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>PA Acknowledged</fullName>
            </value>
            <value>
                <fullName>PA Approved</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Partial Results Ready</fullName>
            </value>
            <value>
                <fullName>Results Ready</fullName>
            </value>
            <value>
                <fullName>PA Rejected</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>PWN Acknowledged</fullName>
                <isActive>false</isActive>
                <label>PWN Acknowledged</label>
            </value>
            <value>
                <fullName>PWN Approved</fullName>
                <isActive>false</isActive>
                <label>PWN Approved</label>
            </value>
            <value>
                <fullName>PWN Rejected</fullName>
                <isActive>false</isActive>
                <label>PWN Rejected</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PWNPollingJob.cls
global with sharing class PWNPollingJob implements Database.Batchable<SObject>, Database.AllowsCallouts{
    public String query;
    public String type;
    public List<String> statusList;
    public String Id;

    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<Lab_Order__c> orders) {

        if(!orders.isEmpty())
        {
            List<Lab_Order__c> updatedLabOrders = new List<Lab_Order__c>();
            List<Kit_Details__c> updatedKits = new List<Kit_Details__c>();
            Set<String> labOrderId =  new Set<String>();
            Set<String> pwnIds = new Set<String>();
            Map<String,String> pwnIDLabOrderMap = new Map<String,String>();
            Map<String,String> labOrderIdKitMap = new Map<String,String>();
            for(Lab_Order__c order : orders)
            {
                if(labOrderId.add(order.Id))
                {
                    pwnIds.add(order.PWN_ID__c);
                    pwnIDLabOrderMap.put(order.PWN_ID__c,order.Id);
                    System.debug('pwnIDLabOrderMap: ' + pwnIDLabOrderMap);
                    if(order.Is_Kit__c)
                        labOrderIdKitMap.put(order.Id, order.Kit_Detail__c);
                }
                
            }

            String requestBody = '{"order_ids":' + JSON.serialize(pwnIds) + '}';

            System.debug(requestBody);

            String key = Label.PWN_API_KEY;
            String secret = Label.PWN_API_SECRET;
            String token = PWNTokenGeneration.generateToken(key,secret);    
            Http http = new Http();
            HttpRequest request = new HttpRequest();
            
            request.setMethod('POST');
            request.setEndpoint(Label.PWN_ORDER_STATUS_URL+'get_batch');
            request.setHeader('accept', 'application/json');
            request.setHeader('content-type', 'application/json');
            request.setHeader('Authorization','Bearer ' + token);
            request.setBody(requestBody);

             System.debug(request);
            
            HttpResponse response = http.send(request);
            
            if (response.getStatusCode() == 200) {
                System.debug('API Call Success: ' + response.getBody());

                Map<String, Object> responseMap = (Map<String, Object>) JSON.deserializeUntyped(response.getBody());
                List<Object> pwnOrders = (List<Object>) responseMap.get('orders');

                for (Object pwnOrder : pwnOrders) {
                    Map<String, Object> pwnOrderMap = (Map<String, Object>) pwnOrder;
                    String pwnId = String.valueOf(pwnOrderMap.get('id'));
                    String status = (String) pwnOrderMap.get('status');
                    if(status == 'approved')
                    {
                        Lab_Order__c loToUpdate = new Lab_Order__c();
                        loToUpdate.Id=pwnIDLabOrderMap.get(pwnId);
                        loToUpdate.Is_PWN_Approved__c=true;
                        loToUpdate.PWN_Status_Date__c = System.today();
                        updatedLabOrders.add(loToUpdate);
                        if(labOrderIdKitMap.get(pwnIDLabOrderMap.get(pwnId))!=null)
                        {
                            Kit_Details__c updatedKit = new Kit_Details__c();
                            updatedKit.Id = labOrderIdKitMap.get(pwnIDLabOrderMap.get(pwnId));
                            updatedKit.Is_PWN_Approved__c=true;
                            updatedKit.PWN_Status_Date__c = System.today();
                            updatedKits.add(updatedKit);
                        }
                    }
                    else if(status == 'rejected')
                    {
                        Lab_Order__c loToUpdate = new Lab_Order__c();
                        loToUpdate.Id=pwnIDLabOrderMap.get(pwnId);
                        loToUpdate.Status__c='PA Rejected';
                        loToUpdate.Full_Refund__c=true;
                        updatedLabOrders.add(loToUpdate);
                        if(labOrderIdKitMap.get(pwnIDLabOrderMap.get(pwnId))!=null)
                        {
                            Kit_Details__c updatedKit = new Kit_Details__c();
                            updatedKit.Id = labOrderIdKitMap.get(pwnIDLabOrderMap.get(pwnId));
                            updatedKit.Lab_Status__c='PA Rejected';
                            updatedKit.PWN_Status_Date__c = System.today();
                            updatedKits.add(updatedKit);
                        }
                    }
                    
                }            
            } 
            else {
            System.debug('Error: ' + response.getStatusCode() + ' ' + response.getBody());
        }

        update updatedLabOrders;
        update updatedKits;
            
            
        }

            
            
        
        }
    

    global void finish(Database.BatchableContext BC) {
       
    }
}