force-app/main/default/objects/Product2/fields/AOE_required__c.field-meta.xml
<CustomField>
    <fullName>AOE_required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>AOE required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Exclude_from_registration__c.field-meta.xml
<CustomField>
    <fullName>Exclude_from_registration__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Exclude from registration</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Excluded_State_codes__c.field-meta.xml
<CustomField>
    <fullName>Excluded_State_codes__c</fullName>
    <label>Excluded State codes</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>NY</fullName>
            </value>
            <value>
                <fullName>OK</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Both</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Male</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Max_age__c.field-meta.xml
<CustomField>
    <fullName>Max_age__c</fullName>
    <label>Max age</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Min_age__c.field-meta.xml
<CustomField>
    <fullName>Min_age__c</fullName>
    <label>Min age</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ProductData.cls
public class ProductData {
    public String productName;
    public String productCode;
    public Boolean aoeRequired;
    public String gender;
    public String excludedStateCodes;
    public String maxAge;
    public String minAge;
    public String testType;
    public Boolean excludeFromRegistration;
    
    public ProductData(Product2 prod){
        this.productName = prod.Name;
        this.productCode = prod.ProductCode;
        this.aoeRequired = prod.AOE_required__c;
        this.gender = prod.Gender__c;
        this.excludedStateCodes = prod.Excluded_State_codes__c;
        this.maxAge = prod.Max_age__c;
        this.minAge = prod.Min_age__c;
        this.excludeFromRegistration = prod.Exclude_from_registration__c;
    }
}